### ISSUE TITLE
Tomb Raider IV: The Times Exclusive - Script doesn't install the game files

### ISSUE THREAD

**Issue by Mephistople** [legluondunet/MyLittleLutrisScripts#1]
So I tried the times exclusive level script of yours, but when I start the .bat launcher and try to start the game it just closes.
 I checked the game folder it installed in:
"/home/your-username-here/Games/tomb-raider-iv-the-times-exclusive-level/drive_c/Program Files (x86)/Core Design/The Times - Exclusive Tomb Raider Level"
but only these files were present.
![Untitled](https://user-images.githubusercontent.com/53997310/63042064-c501cc00-beb8-11e9-9933-52d1b860a264.png)

After that i downloaded the times level from:
http://raidingtheglobe.com/downloads/tomb-raider-4-the-times-exclusive

And extracted it in /Games/tomb-raider-iv-the-times-exclusive-level/drive_c/Program Files (x86)/Core Design/The Times - Exclusive Tomb Raider Level

I see the level files you host on your github are the original installer,
the ones from raiding the globe seems to be already extracted.
At least I got this to work, not sure what the issue is thou.

**Comment by legluondunet** [comment]
Hello, thank you for your report. Could you make a new install following this steps:

1) start Lutris in debug mode, in a terminal type this command:
lutris -d > lutris.log
2) if already installed, uninstall (remove) "Tomb Raider IV: The Times Exclusive"
3) come back to the ["Tomb Raider IV: The Times Exclusive" Lutris page](https://lutris.net/games/tomb-raider-iv-the-times-exclusive-level/) and click "install"
4) at the end of the install, try to launch the game
5) if the issue persists, please post the lutris.log debug file to this thread
6) precise your computer config: OS name and version? 32 or 64 bits? GPU NVidia or AMD?

Thanks.

**Comment by Mephistople** [comment]
Heres my computer stats:
OS: Linux Mint 19.2 Tina x86_64
CPU: Intel i7-7700K (8) @ 4.500GHz 
GPU: NVIDIA GeForce GTX 1080 Ti 
Memory: 16025MiB 

And heres my logfile
hope that helps.

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/3503246/lutris.log)

**Comment by legluondunet** [comment]
It seems the Wine version you use is not standard
Could you try this:
1) install last Lutris Wine version 4.13
2) go to general wine runner option and verify Lutris Wine version 4.13 is the default version
3) remove and reinstall the game. If the issue persists, please post a new debug log

**Comment by Mephistople** [comment]
Well, I installed lutris-4.13 and set it as default wine version.
And what do you know it works just fine now :)
I wasn't aware it mattered that much that I used a proton version,
thanks for the help.
