### ISSUE TITLE
[Syberia] Black screen on game launch

### ISSUE THREAD

**Issue by DanWiseProgramming** [legluondunet/MyLittleLutrisScripts#100]
### Issue
Upon installing the game using the Syberia script in this repository, I tried launching the game but found that despite the applied fixes with nircmd.exe and dxwnd, the game still launched with a black screen.

### Steps to reproduce the behavior:
1. Install 'Syberia' from GoG
2. Launch game
3. See black screen

### Expected behaviour
No black screen

### Proposed fix
After doing some digging online, I found this: https://appdb.winehq.org/objectManager.php?sClass=version&iId=19734&iTestingId=100474

This specifies that the delay between hiding the game and bringing it back into focus using nircmd.exe should be 100ms or 0.1s.
After applying this change to `Syberia.bat`, I could now see the game screen.

**Comment by legluondunet** [comment]
Hello, I just tested the Syberia script installer, there two problems:

    nircmdc.exe takes too much time to launch
    I have only a black screen even with your modifications if I use an Intel GPU card and Wine with fshack patch

Script installer modified and I added a message about wine fshack incompatibility.
Thank you for your contribution.
