### ISSUE TITLE
Return to Castle Wolfenstein - RealRTCW - Error on last step

### ISSUE THREAD

**Issue by keenanweaver** [legluondunet/MyLittleLutrisScripts#102]
There is an error in the last step of the Return to Castle Wolfenstein - RealRTCW script. I've attached the log, but here is the error and the step where it fails.

DEBUG    2021-11-22 09:32:20,900 [command.start:139]:LUTRIS_GAME_UUID="bac1043e-3964-4249-a352-81a8dc7c9f5f"
Started initial process 25063 from /usr/bin/bash -c cd "/home/keenan/Games/gog/return-to-castle-wolfenstein/tmp"; /home/keenan/.cache/lutris/installer/return-to-castle-wolfenstein/innoextract/innoextract *.exe ; mv app/Main/*.pk3 /home/keenan/Games/gog/return-to-castle-wolfenstein/main/; cd app ; rm -f -r Main *.dll *.exe ; cd /home/keenan/Games/gog/return-to-castle-wolfenstein ; mv tmp/app RTCW_mods; rm -f -r tmp ;
Start monitoring process.
Could not open file "*.exe"
Done with 1 error.
mv: cannot stat 'app/Main/*.pk3': No such file or directory
/usr/bin/bash: line 1: cd: app: No such file or directory
mv: cannot stat 'tmp/app': No such file or directory
Monitored process exited.
Initial process has exited (return code: 0)

`- execute:
    command: cd "$GAMEDIR/tmp"; $CACHE/innoextract/innoextract *.exe ; mv app/Main/*.pk3
      $GAMEDIR/main/; cd app ; rm -f -r Main *.dll *.exe ; cd $GAMEDIR ; mv tmp/app
      RTCW_mods; rm -f -r tmp ;`

Screenshot of the latest RealRTCW zip file
![2021-11-22_09-51](https://user-images.githubusercontent.com/37268985/142892598-e9a454d6-771a-4856-90ed-4ab14cecca85.png)

Diagnostic info:

Linux arch-desktop 5.15.4-arch1-1 #1 SMP PREEMPT Sun, 21 Nov 2021 21:34:33 +0000 x86_64 GNU/Linux

LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/7582424/lutris.log)

**Comment by legluondunet** [comment]
Hello @keenanweaver , thank you for your report, I just finished updating Lutris RealRTCW script installer.
Can you test it and tell me if it works for you now?

**Comment by keenanweaver** [comment]
> Hello @keenanweaver , thank you for your report. I just finished updating Lutris RealRTCW script installer. Can you test it and tell me if it works for you now?

Works brilliantly. Thank you very much!
