### ISSUE TITLE
Tom Clancy's Splinter Cell: Install & Runtime Errors

### ISSUE THREAD

**Issue by rinnert** [legluondunet/MyLittleLutrisScripts#104]
The installer fails for two reasons:

1. Lutris strips the top level directory when extracting zip archives. This causes the files from the widescreen patch to end up in the wrong directory.  Adding "/system" to the dst field fixes this.
2. The installer tries to move the file "modupdater.asi" but the file is called "modupdater.ini".

After fixing the above the installation succeeds.  But then the game crashes after the intro before going to the main menu. This is fixed by adding "VideoCard: geforce_ti_4800" to the DirectX section of dgVoodoo.conf.

I already have submitted and edited installer for moderation at the lutris website.

**Comment by legluondunet** [comment]
Hello @rinnert , thank you for your report and contributions. I just validated your script installer updates.
Just one thing, is this line very necessary:
```
system:
  single_cpu: true
```

**Comment by rinnert** [comment]
I don't know whether the single CPU setting is necessary -- it was in the (your?) installer version that I edited. I just left it as it was.  But searching for it, I found it is suggested [here](https://www.pcgamingwiki.com/wiki/Tom_Clancy%27s_Splinter_Cell#Stuttering_during_gameplay) to avoid stuttering.

**Comment by legluondunet** [comment]
ok.
