### ISSUE TITLE
Warcraft 3: RoC stuck black screen on installation

### ISSUE THREAD

**Issue by tom-orchard** [legluondunet/MyLittleLutrisScripts#105]
Hi

I'm having an issue on installation of Reign of Chaos where after picking the language (leaving default of English), it goes fullscreen and it just remains black. This is a fresh installation of Ubuntu 21.10, but also had an issue on the latest of PopOS.

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/7656539/lutris.log)

Incase this is important, my specs are:

i5-11300H
NVIDIA GeForce GTX 1650 Mobile

Any suggestions on what I could try?

Thanks!

**Comment by andyliuhaowen** [comment]
Same issue here. I'm on Ubuntu 20.04 LTS.

**Comment by MatthiKrauss** [comment]
I got the same problem with the same error message. I changed to newest lutris version 0.5.10.1 (0.5.10 was buggy), which had the same behavior, but threw a different log messages, for example:

> (wine:48501): GStreamer-WARNING **: 14:28:34.008: Failed to load plugin '/homepath/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/lib64/gstreamer-1.0/libgstaiff.so': /homehomepath/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/lib64/gstreamer-1.0/libgstaiff.so: wrong ELF class: ELFCLASS64

However, I somehow managed to quit the black screen and after restarting the game, it worked fine.
But I somehow can't install 'The Frozen Throne' DLC after that. When choosing the install script in lutris, it asks if it should create shotcuts, but before you can select anything, it quickly switches to the `Installation completed!` window, which can close. The game is not installed afterwards...

**Comment by legluondunet** [comment]
Hello @tom-orchard @andyliuhaowen  @MatthiKrauss , is this issue still relevant?

**Comment by tom-orchard** [comment]
Hi @legluondunet, 

Just reinstalled PopOS to test, Warcraft 3 Reign of Chaos now works.

I was having issues at one point with a fonts package:
'https://web.archive.org/web/2000/https://deb.debian.org/debian/pool/main/f/fonts-baekmuk/fonts-baekmuk_2.2.orig.tar.gz"

It kept saying there was a cert issue (10% chance it could've been me, I've been playing with deep packet inspection on my Firewall)

So I manually downloaded the file from the link and placed it in the target directory: 
/home/{USER}/.var/app/net.lutris.Lutris/cache/winetricks/baekmuk/

Then was able to install and patch Reign of Chaos, patcher did go to a black screen but just closed the window and completed the install, loaded the game and was working!

Likely good to close this issue

**Comment by cewbdex** [comment]
I have the same issue, the installer is sometimes black and sometimes blue:
![image](https://github.com/legluondunet/MyLittleLutrisScripts/assets/9021297/5cd28557-3cfb-4d64-810e-5efe8e7b9fdc)
Should I open a new issue?

**Comment by legluondunet** [comment]
Hello @cewbdex , you need to open a new issue and provide a Lutris log.
To obtain a Lutris log:
lutris -d > lutris.log
then upload here lutris.log file

**Comment by cewbdex** [comment]
> Hello @cewbdex , you need to open a new issue and provide a Lutris log. To obtain a Lutris log: lutris -d > lutris.log then upload here lutris.log file

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/13279036/lutris.log)
I have closed the window with the X, it does not crash itself. There is some read error I don't know if is relevant, but I have the game in iso, I have tried installing it with the iso mounted and then extracted the contents, but it's the same.

**Comment by legluondunet** [comment]
please open a new issue

**Comment by cewbdex** [comment]
Very odd behavior indeed, but it's your repository after all... If you had problem with using old issue, you could tell me...

**Comment by legluondunet** [comment]
@cewbdex I asked you to open a new issue, please make an effort

**Comment by cewbdex** [comment]
> @cewbdex I asked you to open a new issue, please make an effort

Oh sorry then, I must have misread.
