### ISSUE TITLE
Rune Gold GOG Version won't install

### ISSUE THREAD

**Issue by Randune** [legluondunet/MyLittleLutrisScripts#106]
Hi all, when I try to install Rune Gold GOG Version, I select the local game directory to install to then click “Install” then the installer just hangs there and doesn’t install the game, here is the Lutris Traceback:

Traceback (most recent call last):
File “/usr/lib/python3.9/site-packages/lutris/gui/installerwindow.py”, line 294, in on_runners_ready
self.interpreter.installer.prepare_game_files()
File “/usr/lib/python3.9/site-packages/lutris/installer/installer.py”, line 149, in prepare_game_files
installer_files = self.service.get_installer_files(self, installer_file_id)
File “/usr/lib/python3.9/site-packages/lutris/services/gog.py”, line 393, in get_installer_files
downloads = self.get_downloads(installer.service_appid)
File “/usr/lib/python3.9/site-packages/lutris/services/gog.py”, line 306, in get_downloads
gog_data = self.get_game_details(gogid)
File “/usr/lib/python3.9/site-packages/lutris/services/gog.py”, line 282, in get_game_details
raise ValueError(“Missing product ID”)
ValueError: Missing product ID
2021-12-12 12:35:22,146: Cancelling installation of RUNE

Any help would be greatly appreciated, thanks in advance!

**Comment by legluondunet** [comment]
Hello @Randune , thank you for your report.
I can reproduce your issue and some minor others bugs.
It should be fixed now.

**Comment by Randune** [comment]
Hi @legluondunet I see that Rune Classic - GOG.txt was updated recently but Rune Gold - GOG.txt which is the version that I was not able to install was updated more than 2 years ago (See below).  Also, are the changes going to be submitted to lutris.net?..thanks again legluondunet !!

Rune Classic - GOG.txt Update Rune Classic - GOG.txt 6 days ago 
Rune Gold - GOG.txt modifié : Age of Empires/README.md 2 years ago

**Comment by legluondunet** [comment]
Oops, you are right, I just updated Rune Gold, could you tell me if it works for you now?

**Comment by Randune** [comment]
Hi @legluondunet thanks for publishing the updated install script on lutris.net, I tried it and it works fine..thanks again!
