### ISSUE TITLE
Blood Omen: Legacy of Kain 

### ISSUE THREAD

**Issue by TimeFreeze1337** [legluondunet/MyLittleLutrisScripts#109]
Since the game finally has a GOG version may i suggest an updated Script that uses the GOG version?

**Comment by legluondunet** [comment]
Hello @TimeFreeze1337 , I do not own this game. 
Do you own this game?

**Comment by TimeFreeze1337** [comment]
I own it yes. Do you need the setup file? If so i could share it if you want.

**Comment by legluondunet** [comment]
Ok, please send me a link to this game by mp to my twitter account: https://twitter.com/legluondunet
or by mp on Lutris forum: https://discordapp.com/invite/Pnt5CuY

**Comment by legluondunet** [comment]
@TimeFreeze1337 , I just finished writing script, tell me if it works for you:
GOG + Verok's GL Wrapper/Patch version 
https://lutris.net/games/blood-omen-legacy-of-kain/

**Comment by TimeFreeze1337** [comment]
I get an error when trying to install it. It happens when trying to extract the Wrapper/Patch. "command exited with code 32512" the log is telling this: 

lutris-wrapper: /usr/bin/bash
Started initial process 1706 from /usr/bin/bash -c cd "/home/timefreeze/Games/blood-omen-legacy-of-kain/drive_c"; mkdir "GOG Games"; mv "Blood Omen" "GOG Games"; cd "GOG Games/Blood Omen"; find "." -depth -exec sh -c 't=${0%/*}/$(printf %s "${0##*/}" | tr "[:lower:]" "[:upper:]"); [ "$t" = "$0" ] || mv -i "$0" "$t"' {} \;; cd "/home/timefreeze/Games/blood-omen-legacy-of-kain/drive_c/GOG Games/Blood Omen"; cp -R PATCH/* .; rm -f -r APP COMMONAPPDATA PATCH __REDIST __SUPPORT TMP GOGGAME-1837805079.*; MKDIR SAVED;
Start monitoring process.
mv: '.' and '././.' are the same file
/usr/bin/bash: line 1: MKDIR: command not found
Monitored process exited.
Initial process has exited (return code: 32512)
All processes have quit
Exit with return code 32512

**Comment by legluondunet** [comment]
fixed! could you try again?

**Comment by TimeFreeze1337** [comment]
It works now perfectly! Highly appreciate the work.
