### ISSUE TITLE
Genshin Impact

### ISSUE THREAD

**Issue by ArchieTNT** [legluondunet/MyLittleLutrisScripts#111]
Hi I'm trying to install genshin impact on linux via lutris (I assume it is your installer) however I don't know how to apply the patch as the instructions are vague and without the patch I just get a black screen.

**Comment by legluondunet** [comment]
Hello @ArchieTNT, I effectively wrote GenshinImpact new Lutris installer. To apply patch, in your Lutris interface, right click on the game icon/banner and choose "execute script". A xterm terminal window should appear with instructions.

**Comment by BlackDragonIX** [comment]
Unfortunately clicking "Execute Script" is having no effect for me. I have tried the script at each part of the installation process. Namely, before and after running the games' launcher and downloading the latest version of the game.

I noticed that the instructions say "You will need root rights to install this patch as it will modify /etc/hosts system file." I have not been prompted for my root password, so I am unsure how to go about this as running Execute Script appears to do nothing, not even producing a log output for the game in Lutris. Apologies for my ignorance.

**Comment by legluondunet** [comment]
How to apply patch:
![patch_Genshin_Impact](https://user-images.githubusercontent.com/325405/148694715-5c64cb78-5fb2-4440-8058-ff01b27b7670.gif)

If it doesn't work, verify that:
- you have xterm installed.
- in "games/genshin-impact/drive_c/gi_patch_230/" folder, "ex_apatch.sh" and "ex_rpatch.sh" files are executable.
% ls -l
total 24
-rwxr-xr-x 1 legluondunet legluondunet  197  6 janv. 00:15 ex_apatch.sh
-rwxr-xr-x 1 legluondunet legluondunet  204  6 janv. 00:15 ex_rpatch.sh
drwx------ 2 legluondunet legluondunet 4096  3 janv. 20:38 patch_files
-rw-r--r-- 1 legluondunet legluondunet 1533  3 janv. 20:38 patch_revert.sh
-rw-r--r-- 1 legluondunet legluondunet 4775  3 janv. 20:38 patch.sh

**Comment by BlackDragonIX** [comment]
Unfortunately this hasn't resolved my issue.

Xterm and Zenity are installed, and all files in the directory in question match the permissions you listed exactly. I have also performed a reboot since installing Xterm in Zenity, just in case.

Navigating to the directory and attempting to execute the files directly in my terminal yeilds the following results:
![image](https://user-images.githubusercontent.com/8507170/148695550-dc148115-c8c6-42a8-849c-26a673c08477.png)

**Comment by legluondunet** [comment]
Please be patient, a new Genshin Impact version 2.40 is out and I need to update script installer. Your issue could be cause that I need to update patch files for this new version.

**Comment by BlackDragonIX** [comment]
It didn't dawn on me that the "gi_patch_230" meant it was for Genshin version 2.3. Thanks for your help

**Comment by legluondunet** [comment]
script updated and it works (at least for me).
![Uploading ArcoLinux_2022-01-09_20-04-46.png…]()

**Comment by BlackDragonIX** [comment]
I was able to apple the patch! It worked, thanks again!

**Comment by panzerlop** [comment]
MHYPbase.dll error
