### ISSUE TITLE
Tomb Raider 1 - Game fails to start

### ISSUE THREAD

**Issue by kylemarkwilliams** [legluondunet/MyLittleLutrisScripts#112]
Game fails to start when selection option 1 or 2 from the menu. Other options work.

```
kyle@anubis:~$ uname -a
Linux anubis 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
kyle@anubis:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Neon
Description:    KDE neon User - Plasma 25th Anniversary Edition
Release:        20.04
Codename:       focal

```
[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/7834538/lutris.log)

**Comment by legluondunet** [comment]
Hello @kylemarkwilliams, use another Wine version in Lutris, try with a non fshack Wine version.

**Comment by kylemarkwilliams** [comment]
Hi @legluondunet 
I just tried lutris-6.21-6-x86_64 and same error. Nothing appears in the logs.

**Comment by kylemarkwilliams** [comment]
As a note, I just installed TR2 using the steam script and that game works flawlessly.

**Comment by legluondunet** [comment]
I can reproduce your issue with recent Lutris WIne version and GE-Proton version too.
Try with lutris-6.14-4-x86_64, works for me.

**Comment by kylemarkwilliams** [comment]
Works perfectly with lutris-6.14-4-x86_64!!

Thanks. Feel free to close if you're not using this to track the wine incompatibility issue.
