### ISSUE TITLE
Trying to install Warcraft III Reforged

### ISSUE THREAD

**Issue by OliverGeneser** [legluondunet/MyLittleLutrisScripts#113]
Hello,
When I try to install Warcraft III Reforged the installation screen is black and I get this error:

Start monitoring process.
015c:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFA, 02A9FEF4
0148:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0148:fixme:uiautomation:UiaClientsAreListening ()
0148:fixme:uiautomation:UiaClientsAreListening ()
0148:fixme:uiautomation:UiaClientsAreListening ()
0148:fixme:imm:ImeSetActiveContext (0xe80030, 1): stub
0148:fixme:imm:ImmReleaseContext (00010088, 00E80030): stub
0130:fixme:imm:ImeSetActiveContext (0x4803d0, 0): stub
0130:fixme:imm:ImmReleaseContext (000000000003005A, 00000000004803D0): stub

Intel i7-4790k
AMD Graphics

uname -a
Linux pop-os-main 5.15.8-76051508-generic #202112141040~1639505278~21.10~0ede46a SMP Tue Dec 14 22:38:29 U x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
Distributor ID:	Pop
Description:	Pop!_OS 21.10
Release:	21.10
Codename:	impish

**Comment by legluondunet** [comment]
Hello @OliverGeneser , Is this issue still relevant?

**Comment by legluondunet** [comment]
I tested this script installer and I can not repreduce.
