### ISSUE TITLE
Tomb Raider GoG with TombATI HD - won't run game with script installed wine, HD FMVs don't play, can't load DLL.

### ISSUE THREAD

**Issue by SegaGameBoyStation** [legluondunet/MyLittleLutrisScripts#116]
`uname -a
Linux MidgeMong 5.15.0-18.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.15-22ubuntu1~impish (2022-01-29) x86_64 x86_64 x86_64 GNU/Linux`

`lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish`

I am trying to run the game however the menu will not work to play the game only to chose HD pack and quit.
Changing the wine version as shown in earlier closed issue will play the game but FMVs don't work.
I get an error about not being able to load a DLL, I can't find a DLL in winetricks to match.
Log doesn't look useful but I will attach when I figure out how to.

**Comment by SegaGameBoyStation** [comment]
Log file as comment:
`INFO     2022-01-31 01:17:11,039 [startup.check_driver:61]:Running AMD Mesa driver 21.3.5 on AMD RENOIR (DRM 3.42.0, 5.15.0-18.1-liquorix-amd64, LLVM 13.0.0) (0x1636)
INFO     2022-01-31 01:17:11,040 [startup.check_driver:73]:GPU: 1002:1636 1043:87E7 (amdgpu drivers)
DEBUG    2022-01-31 01:17:12,241 [lutriswindow.update_store:451]:Showing 10 games
DEBUG    2022-01-31 01:17:16,763 [xrandr._get_vidmodes:14]:Retrieving video modes from XrandR
DEBUG    2022-01-31 01:17:16,799 [xrandr._get_vidmodes:14]:Retrieving video modes from XrandR
DEBUG    2022-01-31 01:17:16,810 [xrandr._get_vidmodes:14]:Retrieving video modes from XrandR
DEBUG    2022-01-31 01:17:16,821 [xrandr._get_vidmodes:14]:Retrieving video modes from XrandR
INFO     2022-01-31 01:17:49,991 [game_actions.on_show_logs:150]:No log for game Tomb Raider - GOG (wine)
DEBUG    2022-01-31 01:17:53,185 [xrandr._get_vidmodes:14]:Retrieving video modes from XrandR
DEBUG    2022-01-31 01:17:53,196 [prefix.set_virtual_desktop:190]:Enabling wine virtual desktop with default resolution of 3840x2160
DEBUG    2022-01-31 01:17:53,221 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/dxgi.dll with DXVK version
DEBUG    2022-01-31 01:17:53,221 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3d11.dll with DXVK version
DEBUG    2022-01-31 01:17:53,222 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3d10core.dll with DXVK version
DEBUG    2022-01-31 01:17:53,223 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3d9.dll with DXVK version
DEBUG    2022-01-31 01:17:53,223 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/dxgi.dll with DXVK version
DEBUG    2022-01-31 01:17:53,223 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3d11.dll with DXVK version
DEBUG    2022-01-31 01:17:53,224 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3d10core.dll with DXVK version
DEBUG    2022-01-31 01:17:53,225 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3d9.dll with DXVK version
DEBUG    2022-01-31 01:17:53,225 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3d12.dll with VKD3D version
DEBUG    2022-01-31 01:17:53,226 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/nvapi64.dll with DXVK-NVAPI version
DEBUG    2022-01-31 01:17:53,226 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/nvml.dll with DXVK-NVAPI version
DEBUG    2022-01-31 01:17:53,226 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/nvapi.dll with DXVK-NVAPI version
DEBUG    2022-01-31 01:17:53,226 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/nvml.dll with DXVK-NVAPI version
ERROR    2022-01-31 01:17:53,226 [nvidia.get_nvidia_glx_path:42]:Unable to load libGLX_nvidia.so.0
WARNING  2022-01-31 01:17:53,226 [nvidia.get_nvidia_dll_path:90]:Unable to locate libGLX_nvidia
DEBUG    2022-01-31 01:17:53,227 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dcompiler_42.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,227 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dcompiler_43.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,227 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dcompiler_46.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,227 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dcompiler_47.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,227 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx10_33.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,227 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx10_34.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,227 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx10_35.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,227 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx10_36.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,227 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx10_37.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,227 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx10_38.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,227 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx10_39.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,227 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx10_40.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,228 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx10_41.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,228 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx10_42.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,228 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx10_43.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,228 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx10.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,228 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx11_42.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,228 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx11_43.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,228 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_24.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,228 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_25.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,228 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_26.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,228 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_27.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,228 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_28.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,228 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_29.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,228 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_30.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,229 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_31.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,229 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_32.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,229 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_33.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,229 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_34.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,229 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_35.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,229 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_36.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,229 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_37.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,229 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_38.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,229 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_39.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,229 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_40.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,229 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_41.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,229 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_42.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,230 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/system32/d3dx9_43.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,230 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dcompiler_42.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,230 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dcompiler_43.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,230 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dcompiler_46.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,230 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dcompiler_47.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,230 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx10_33.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,230 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx10_34.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,230 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx10_35.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,230 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx10_36.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,230 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx10_37.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,230 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx10_38.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,230 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx10_39.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,230 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx10_40.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,231 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx10_41.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,231 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx10_42.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,231 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx10_43.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,231 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx10.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,231 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx11_42.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,231 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx11_43.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,231 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_24.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,231 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_25.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,231 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_26.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,231 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_27.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,231 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_28.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,231 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_29.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,231 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_30.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,232 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_31.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,232 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_32.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,232 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_33.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,232 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_34.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,232 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_35.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,232 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_36.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,232 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_37.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,232 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_38.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,232 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_39.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,232 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_40.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,232 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_41.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,232 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_42.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,232 [dll_manager.enable_dll:131]:Replacing /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/d3dx9_43.dll with D3D Extras version
DEBUG    2022-01-31 01:17:53,263 [xrandr._get_vidmodes:14]:Retrieving video modes from XrandR
DEBUG    2022-01-31 01:17:53,276 [command.start:139]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2022-01-31 01:17:53,276 [command.start:139]:SDL_VIDEO_FULLSCREEN_DISPLAY="off"
DEBUG    2022-01-31 01:17:53,276 [command.start:139]:LD_LIBRARY_PATH="/home/nightfiend6/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/lib:/home/nightfiend6/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/lib64:/lib/x86_64-linux-gnu:/lib/i386-linux-gnu:/lib:/lib32:/lib/i386-linux-gnu/sse2:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib64:/lib64:/usr/lib:/usr/lib64:/usr/lib32:/usr/lib64:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/nightfiend6/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/nightfiend6/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/nightfiend6/.local/share/lutris/runtime/steam/i386/lib:/home/nightfiend6/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/nightfiend6/.local/share/lutris/runtime/steam/i386/usr/lib:/home/nightfiend6/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/nightfiend6/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/nightfiend6/.local/share/lutris/runtime/steam/amd64/lib:/home/nightfiend6/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/nightfiend6/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH"
DEBUG    2022-01-31 01:17:53,276 [command.start:139]:MESA_GL_VERSION_OVERRIDE="3.3"
DEBUG    2022-01-31 01:17:53,276 [command.start:139]:WINEDEBUG="-all"
DEBUG    2022-01-31 01:17:53,276 [command.start:139]:WINEARCH="win64"
DEBUG    2022-01-31 01:17:53,276 [command.start:139]:WINE="/home/nightfiend6/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/bin/wine"
DEBUG    2022-01-31 01:17:53,277 [command.start:139]:GST_PLUGIN_SYSTEM_PATH_1_0="/home/nightfiend6/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/lib64/gstreamer-1.0/:/home/nightfiend6/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/lib/gstreamer-1.0/"
DEBUG    2022-01-31 01:17:53,277 [command.start:139]:WINEPREFIX="/home/nightfiend6/Games/tomb-raider-i-HD-GOG"
DEBUG    2022-01-31 01:17:53,277 [command.start:139]:WINEESYNC="1"
DEBUG    2022-01-31 01:17:53,277 [command.start:139]:WINEFSYNC="0"
DEBUG    2022-01-31 01:17:53,277 [command.start:139]:DXVK_NVAPIHACK="0"
DEBUG    2022-01-31 01:17:53,277 [command.start:139]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d9,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2022-01-31 01:17:53,277 [command.start:139]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2022-01-31 01:17:53,277 [command.start:139]:game_name="Tomb Raider - GOG"
DEBUG    2022-01-31 01:17:53,277 [command.start:139]:PYTHONPATH="/usr/lib/lutris:/usr/games:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/home/nightfiend6/.local/lib/python3.9/site-packages:/usr/local/lib/python3.9/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.9/dist-packages"
DEBUG    2022-01-31 01:17:53,277 [command.start:139]:LUTRIS_GAME_UUID="ca430caa-3455-47ed-a8ae-fe9d07bb812e"
Started initial process 28438 from gamemoderun /home/nightfiend6/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/bin/wine /home/nightfiend6/Games/tomb-raider-i-HD-GOG/drive_c/windows/syswow64/wineconsole.exe c:\tr1.bat
Start monitoring process.
gamemodeauto: 
esync: up and running.
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
DEBUG    2022-01-31 01:18:15,653 [command.on_stop:193]:Process 28436 has terminated with code 0
DEBUG    2022-01-31 01:18:23,306 [game.beat:588]:Game thread stopped
WARNING  2022-01-31 01:18:23,306 [game.on_game_quit:614]:Game still running (state: running)
INFO     2022-01-31 01:18:23,306 [game.stop:599]:Stopping Tomb Raider - GOG (wine)
DEBUG    2022-01-31 01:18:23,307 [game.stop_game:554]:Tomb Raider - GOG (wine) has run for 30 seconds
INFO     2022-01-31 01:18:32,035 [application.do_shutdown:631]:Shutting down Lutris
`

**Comment by SegaGameBoyStation** [comment]
If I change the wine version to lutris-6.10-7-x86_64 the game runs, however if the TombATI FMV upscales are installed in the TOMBATI FMV directory I get a wine pop-up error of `0x80040227`

**Comment by legluondunet** [comment]
Hello @SegaGameBoyStation , thank you for your report.
It's a know issue: a lot of old Windows games do not work with fshack Lutris Wine version. Use a non fshack Wine version instead.
TombATI FMV upscales are not supported.
