### ISSUE TITLE
Genshin Impact 2.5

### ISSUE THREAD

**Issue by 0x6DD8** [legluondunet/MyLittleLutrisScripts#119]
Due to 2.5 update and mihoyo changing their domain (now hoyoverse), script/patch probably stopped working. Reinstalling did not help

`uname -a --> Linux void 5.15.22_1 #1 SMP Tue Feb 8 18:31:39 UTC 2022 x86_64 GNU/Linux`

`lsb_release -a -->
LSB Version:    1.0
Distributor ID: VoidLinux
Description:    Void Linux
Release:        rolling
Codename:       void`

**Comment by legluondunet** [comment]
Hello @0x6DD8 , thank you for your report, Lutris script installer just updated with 2.5 patch.
Tell me if it works as expected for you.
