### ISSUE TITLE
Future Pinball, missing NewTable.tbl template

### ISSUE THREAD

**Issue by arthurlutz** [legluondunet/MyLittleLutrisScripts#12]
For some reason, the NewTable.fpt is not shipped with the Future Pinball install via lutris. 

You get  `There was a problem loading that file`

![Screenshot from 2019-11-13 13-31-49](https://user-images.githubusercontent.com/108437/68765464-1c7d1880-061d-11ea-94bd-93b37d013608.png)

Copying the file solves this : 

```
cp ~/.PlayOnLinux/wineprefix/futurepinball/drive_c/Games/Future\ Pinball/NewTable.fpt ~/Games/future-pinball/drive_c/Future\ Pinball/
```

**Comment by legluondunet** [comment]
Hello @arthurlutz , I just added this file. Thank you for your report.
