### ISSUE TITLE
Syberia - Game files don't install

### ISSUE THREAD

**Issue by asder216** [legluondunet/MyLittleLutrisScripts#121]
Hello, I think there's a problem with Syberia's installer.
When I install the game (choosing italian in the installer) and go to /drive_c/GOG Games/Syberia/ I can only find nircmd files, syberia.bat and a few other files which I think come from `setup_syberia_1.0.0_hotfix4_(italian)_(53936)-1.bin`
If I download the installer from gog, install in another folder and copy the game files the game works perfectly.

```
uname -a
Linux LUCA-PC 5.13.0-30-generic #33-Ubuntu SMP Fri Feb 4 17:03:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish
```
[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/8199962/lutris.log)

Thank you tons!

**Comment by yeppey** [comment]
Hi, seems to have the same problem here with french installer "setup_syberia_1.0.0_hotfix4_(french)_(53936)".
When launching install from lutris, a popup "Could not retrieve game installer." appear at the same time as the main installer dialog "GOG + DxWnd. But, when proceeding with installation, the button "View source" gives the script as expected.

Just after selecting language I spotted this message :
"mv: impossible d'évaluer '__support/userdocs/Syberia Saves': Aucun fichier ou dossier de ce type"

At the end of installation, like asde216 I have nircmd files in "drive_c/GOG Games/Syberia", along with selected language from syberia_multi5 ; and Dxwnd in "drive_c/dxwnd" ; but no game data from gog-installer. Obviously the game can't launch.

Manual install in other wineprefix, and copy game files (without overwriting existing ones) works great. Just a minor annoyance is when quitting game, wine stay on a black screen and must be manually stopped.

Note : I'm running lutris 0.5.9.1 on debian stable.

Thanks for your scripts/workaround/tweaks for games to be played in the best conditions !

Cheers.

**Comment by legluondunet** [comment]
Hello @asder216  and @yeppey , thank you for your report. Gog has recently changed "Syberia" package. I just updated Lutris script installer. Does it finally resolved your issue? Don't use a fshack Wine version for this game.

**Comment by asder216** [comment]
Yes, just tried reinstalling it and it works now! Thank you tons!

**Comment by yeppey** [comment]
The new installer works for me too (french installer), as I can see, it needed a new version of innoextract. Thanks @legluondunet.
