### ISSUE TITLE
Unreal Gold (GOG + Patch 227i) doesn't start on Void Linux

### ISSUE THREAD

**Issue by LupertEverett** [legluondunet/MyLittleLutrisScripts#122]
Since Void Linux uses runit, it doesn't come with systemd, nor it is available in their repos. So when for some reason libSDL2.so.0 tries to look up for libsystemd.so.0, it cannot find it, thus resulting in game not starting at all.

**Comment by legluondunet** [comment]
Hello @LupertEverett , I'm sorry but this Linux distribution is not supported. You could find the supported Linux distributions list by my project on the Readme.md file.
