### ISSUE TITLE
New 2.6 patch just came out. Please update the script. Thank you!

### ISSUE THREAD

**Issue by rbnxytt** [legluondunet/MyLittleLutrisScripts#123]
Hello, to report your issue, please follow this steps:
    
    1) start Lutris in debug mode, in a terminal type this command:
    lutris -d > lutris.log
    2) if already installed, uninstall (remove) your game
    3) now come back to your game Lutris page installer and reinstall it. 
    At the end of the install, try to launch the game. 
    If the issue persists, please post the lutris.log debug file to this thread
    4) copy/paste the results of this 2 commands:
    uname -a
    lsb_release -a
    5) put the game name in the issue report title

Thank you for your issue report.

**Comment by MathieuPIN** [comment]
This post is probably about Genshin Impact. Due to its recent 2.6 update. I also encounter issues when I try to launch the game since the new release.

**Comment by legluondunet** [comment]
Hello @rbnxytt  @MathieuPIN  , I inform you that Lutris script installer for Genshin Impact is now updated with 2.6 patch
If you already installed Genshin Impact with Lutris, you do not need to reinstall the game, just install " Update patch to 2.60 version" script installer. Then be sure you updated the game to 2.6 (option 2 in menu) and patch the game.

**Comment by rbnxytt** [comment]
> Hello @rbnxytt @MathieuPIN , I inform you that Lutris script installer for Genshin Impact is now updated with 2.6 patch If you already installed Genshin Impact with Lutris, you do not need to reinstall the game, just install " Update patch to 2.60 version" script installer. Then be sure you updated the game to 2.6 (option 2 in menu) and patch the game.

Thank you so much. Your effort is greatly appreciated.
