### ISSUE TITLE
 Silent Hill 2 Director's Cut Install Script Locking Folder 

### ISSUE THREAD

**Issue by k-e-i-z-a-i** [legluondunet/MyLittleLutrisScripts#125]
When I use the Silent Hill 2 Director’s Cut install script, every time the script creates or interacts with the sh2dccd folder, it changes the Owner permissions of that folder to “Access files” only. As a result, the install script fails because it isn’t able to perform the required actions on this folder (i.e. no write access).

I’ve managed to get around this problem for the second CD by manually changing the permissions after making use of the first CD, but can’t do so for the third because it changes permissions after “inserting” the third CD.

Any help in resolving this would be greatly appreciated!

**Logs**
[https://paste.ubuntu.com/p/9mQNJsk5Vm/](https://paste.ubuntu.com/p/9mQNJsk5Vm/)

 **uname -a**
Linux pop-os 5.16.19-76051619-generic #202204081339~1649696161~21.10~091f44b SMP PREEMPT Mon Apr 11 17 x86_64 x86_64 x86_64 GNU/Linux

**lsb_release -a**
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 21.10
Release:	21.10
Codename:	impish

**Comment by k-e-i-z-a-i** [comment]
The main install script works now! Thank you so much! I had trouble booting the game after running the FMV and audio script, so I wiped it all, reran the main script and did a manual install of the FMV and audio and it works now. Not sure if the problem was with the FMV and audio script or not. Thank you again so much for your help with this!

**Comment by legluondunet** [comment]
- use latest packages from SI2E OK
- verified all two Lutris script installer OK
