### ISSUE TITLE
Indiana Jones Fate of Atlantis - MULTI 5

### ISSUE THREAD

**Issue by dacanizares** [legluondunet/MyLittleLutrisScripts#126]
I'm trying to install Indiana Jones Fate of Atlantis - Multi 5. It works until it asks me for the subtitles language. I select spanish, but then the process fails saying:

```
lutris-wrapper: /usr/bin/bash
Started initial process 10812 from /usr/bin/bash -c cd /home/dacanizares/Games/gog/indiana-jones-and-the-fate-of-atlantis; cp other/ATLANTIS.ICO other/HELPME.DOC . ; rm -f -r app commonappdata other __redist scummvm __support tmp goggame-1207666293.* ; if [ "sp" == "keep" ]; then  exit ; fi ; echo "lang = sp"; patch < /home/dacanizares/.cache/lutris/installer/indiana-jones-and-the-fate-of-atlantis/sp/ATLANTIS.000.patch ATLANTIS.000; patch < /home/dacanizares/.cache/lutris/installer/indiana-jones-and-the-fate-of-atlantis/sp/ATLANTIS.001.patch ATLANTIS.001;
Start monitoring process.
lang = sp
/usr/bin/bash: line 1: patch: command not found
/usr/bin/bash: line 1: patch: command not found
Monitored process exited.
Initial process has exited (return code: 32512)
All processes have quit
Exit with return code 32512
```

My system:

```
uname -a
Linux fedora-dacan 5.17.9-300.fc36.x86_64 #1 SMP PREEMPT Wed May 18 15:08:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Fedora 36
```

Attached lutris.log.

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/8788842/lutris.log)

**Comment by legluondunet** [comment]
Hello @dacanizares , I updated the script.
I added in the description:

> - Careful: to use this script, you have firstly to download game file installation in Windows exe format and US language on GOG. Then select local file during install instead of "automatic download".

and now script verify "patch" binary is installed.
Could you verify and tell me if it installs now correctly for you?

**Comment by dacanizares** [comment]
Hi, thanks for the update. I tried but it doesn't let me choose the file, it directly shows this dialog and it just let me cancel: 
![image](https://user-images.githubusercontent.com/5238966/172079858-5e72a652-0fde-4c87-a058-76ce2fde1ca1.png)

**Comment by legluondunet** [comment]
You need to install "patch" on your system.

**Comment by dacanizares** [comment]
Thanks. I was able to install it. It worked with a manually downloaded file and with the automatic option. It patched to spanish without any problems.

The only issue is that when I tried to play it, the internal scummvm throws some errors because of missing dependencies: SDL_net and libjpeg.so.

I decided to run the installed version with my own ScummVM installation and it worked.

**Comment by legluondunet** [comment]
> The only issue is that when I tried to play it, the internal scummvm throws some errors because of missing dependencies: SDL_net and libjpeg.so.
All Linux distributions provide sdl_net  and libjpeg libraries, it's better to install them, in 64 and 32 bits.

**Comment by legluondunet** [comment]
Happy to see this game finally works for you. I can close this issue.
