### ISSUE TITLE
genshin impact new patch 2.7

### ISSUE THREAD

**Issue by lecasusbellis** [legluondunet/MyLittleLutrisScripts#127]
Hi, please update the genshin impact patch version 2.7
![image](https://user-images.githubusercontent.com/98593549/171114911-24841ea1-182a-41b2-946e-eafa2500e0ea.png)

**Comment by FailedCaptchx** [comment]
Please update it... even though it isn't maintained anymore, it's still got at least two users here, right?

**Comment by ArchieTNT** [comment]
Could you send a link to the upstream source of the patch

**Comment by KGAT1W** [comment]
I believe that it will happen

**Comment by 0x6DD8** [comment]
>or pls give for us tutorial how to update patch, pls !
I know it's to match but pls, help us... Last time.

Since it's modifying game files its better not to show the modifying method because mihoyo might fix this method or even harden their anti-cheat in future

**Comment by KGAT1W** [comment]
> > or pls give for us tutorial how to update patch, pls !
> > I know it's to match but pls, help us... Last time.
> 
> Since it's modifying game files its better not to show the modifying method because mihoyo might fix this method or even harden their anti-cheat in future

Forgot about it

**Comment by luiz-orlandi** [comment]
The 2.6 patch works like a charm, thanks for that ! eagerly waiting for version 2.7 pathc version !

**Comment by PacaPop** [comment]
please 2.7.0 patch!

**Comment by MoshiBar** [comment]
[270.zip](https://github.com/legluondunet/MyLittleLutrisScripts/files/8836086/270.zip)
from [https://notabug.org/Krock/dawn/src/master](url)
you're welcome

**Comment by cybik** [comment]
The developer of the patch *requests* that you do not share the link.

@MoshiBar @legluondunet delete the message with the link or be responsible for ruining it for the Linux playerbase.

**Comment by cybik** [comment]
Literally:

![Screenshot_20220604_124846](https://user-images.githubusercontent.com/387759/172023451-346c9496-10de-4c13-88e7-4207bc8b0c14.png)

**Comment by legluondunet** [comment]
Hello all, I'm working on it, please be patient.

**Comment by legluondunet** [comment]
@MoshiBar  please delete quickly your message or I will block you from my Github page.

**Comment by legluondunet** [comment]
GI Lutris script just updated with latest patch 2.70.
