### ISSUE TITLE
Updates to Silent Hill 2 Directors cut

### ISSUE THREAD

**Issue by chrisgix** [legluondunet/MyLittleLutrisScripts#128]
Hello. I would like to make a suggestion to improve your silent hill 2 Directors cut lutris script.

The enhanced edition project has seen some updates since the script was last published, and I believe incorporating these changes would be beneficial. The biggest change that came out a few days ago, is that the enhanced edition project now uses a dedicated installer that will grab the latest version of all the necessary files. 

In addition, there has been work being done over on the following thread to improve support for Linux (specifically the steam deck), so some of the steps this installer uses may no longer be necessary.

https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/505

**Comment by legluondunet** [comment]
Hello @chrisgix , thank you for your report.
I just wrote a new Silent Hill 2 Director's cut Lutris installer script to include latest changes and sh2ee new setup tool.
Could you test it and tell me if it works for you?

**Comment by chrisgix** [comment]
@legluondunet awesome! I'll give it a try later today and report back 👍

**Comment by chrisgix** [comment]
@legluondunet I just tested it out and its great! Works fantastic out of the box. Thanks for updating this!
