### ISSUE TITLE
Moto Racer 1: Low Memory Warning when starting a race

### ISSUE THREAD

**Issue by 7HEPOW** [legluondunet/MyLittleLutrisScripts#13]
When starting a race, the game shows an ingame info box with a low video memory warning. It's easily fixed by passing the setting "vidmemorysize=512" through protontricks.

Current Specs: https://gist.github.com/7HEPOW/8e16a67cfe7864492abd4cb4f6988f1f

**Comment by legluondunet** [comment]
I can not reproduce this issue on Ubuntu. But on my virtual Manjaro I obtain the same issue as you. I have to find why this issue appears on Manjaro and not on Ubuntu.

**Comment by legluondunet** [comment]
MR1 script installer now uses GOG default options:
-DoRealLock -OpaqueBlackLevel3 -TextureSquareOnly -Pal16 -CorrectRatioTextures -NoDither -TextureVideoMem268435456
Tested on Manjaro: OK
