### ISSUE TITLE
Genshin Impact patch script does not support new Genshin version (2.8)

### ISSUE THREAD

**Issue by jmyrick02** [legluondunet/MyLittleLutrisScripts#130]
Since Genshin updated, I need to apply the patches again. However, the new version's checksum is different and so the patch can't be applied. I tried to fix this myself but it was beyond my ability. Is this going to be updated? I see it's in the OBSOLETE UNMAINTAINED folder so not sure. If not, or if it will take a while, could I help get a patch running for 2.8? I tried myself but was unable since it's not documented how you created the zip file that was added by upload.

Error from xterm:
![image](https://user-images.githubusercontent.com/63320517/178649031-0aedba97-b252-4985-a794-530c1a629a0b.png)

**Comment by waffleboi9000** [comment]
@legluondunet

**Comment by legluondunet** [comment]
Hello, thank you for your report, I will update GI script installer in this next days.  Please be patient.

**Comment by waffleboi9000** [comment]
Sorry about the mention, just wanted to make sure it was called to your attention. As always, incredibly grateful for the work you do.

**Comment by linkian209** [comment]
Hey! I want to thank you so much for you diligence in doing this. I would be happy to help you with Genshin Impact in particular if you teach me how you do the deltas.

**Comment by legluondunet** [comment]
Hello @linkian209 , I'm not the GI patch dev, only the GI Lutris installer script maintainer.

**Comment by legluondunet** [comment]
Patch and Lutris installers updated to 2.80.
Enjoy!
