### ISSUE TITLE
Genshin impact can't get any input after lost focus

### ISSUE THREAD

**Issue by Soggy-Pancake** [legluondunet/MyLittleLutrisScripts#133]
OS: Manjaro kde 1.18.12-3

how to recreate: launch game the alt tab or click on another window

error code: 0618:fixme:win:NtUserGetKeyboardLayout cpuldn't return keyboard layout for thread 0078

**Comment by UkaiNejasaki** [comment]
Have the same problem.  It's fixable by alt+tabing back to Genshin, then hit esc, b, c, or anything that brings up the in game cursor, then closing said menu

**Comment by legluondunet** [comment]
Hello,
sorry, I no more maintain this Lutris script.
