### ISSUE TITLE
Genshin impact closes on installation

### ISSUE THREAD

**Issue by AuthFailed** [legluondunet/MyLittleLutrisScripts#134]
Hi, the download is successful, but after the unpacking phase the file verification phase begins. At this stage, the GI Launcher closes along with Lutris completely. 

**uname -r:** 
_Linux fedora 5.18.11-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jul 12 22:52:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux_
**lsb_release -a:** 
_LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 36 (Thirty Six)
Release:	36
Codename:	ThirtySix_

**Comment by AuthFailed** [comment]
[lutris_log.txt](https://github.com/legluondunet/MyLittleLutrisScripts/files/9158338/lutris_log.txt)
Uploading lutris log

**Comment by waffleboi9000** [comment]
As a workaround, you can use the update game option (2), and hit update in the launcher, it should detect the files and resume the unzipping process.

**Comment by AuthFailed** [comment]
> As a workaround, you can use the update game option (2), and hit update in the launcher, it should detect the files and resume the unzipping process.

Yes, that helped. In the settings you should have selected "Repair game files". Tried several times to install from scratch, but the download kept crashing.

**Comment by legluondunet** [comment]
Hello @AuthFailed , could  you explain us why you closed this ticket? Did you find a solution for your issue?

**Comment by AuthFailed** [comment]
> Hello @AuthFailed , could you explain us why you closed this ticket? Did you find a solution for your issue?

Yes, [In the settings you should have selected "Repair game files"](https://github.com/legluondunet/MyLittleLutrisScripts/issues/134#issuecomment-1191296540)
