### ISSUE TITLE
Genshin Impact Update Patch to version 3.0

### ISSUE THREAD

**Issue by jitoxx** [legluondunet/MyLittleLutrisScripts#138]
I knew that the new version of Genshin Impact will be release tomorrow, but i ask legluondunet if you can update the patch for Genshin Impact soon as possible. And i write this now because i know that a few people play this game also and want that patch.

**Comment by jitoxx** [comment]
Oh sry for the mention that was my autocompletion

**Comment by FOREVEREALIZE** [comment]
Yes, please update the patch

**Comment by malinkb** [comment]
Would be cool if you could provide the steps on how to build the patches, so we don't rely on one person.
That said. Thanks for making this patches in the first place :)

**Comment by FOREVEREALIZE** [comment]
Maybe someone with more knowledge could reverse-engineer how the patches work.

May try that

**Comment by calvinthefreak** [comment]
Or at least build a Pipeline, that automatically patches the game and release it here on to the Git.

It's propably good that OP doesn't release the patch, because then Mihoyo could patch the patch and make it impossible to play on Linux.

But please at least build an Auto-Pipe that updates the things.

**Comment by calvinthefreak** [comment]
@malinkb I think that this would not be a good idea like I said above to release the "Source" of the Patched Patch.

**Comment by FOREVEREALIZE** [comment]
I am trying to figure out what it does (the patch)

**Comment by malinkb** [comment]
> 

yeah, that would also be much appreciated.
I tried to edit the script by adding the md5sum from the new UnityPlayer.dll file but still xdelta3 gave info about mismatch in checksum, so I tried to edit the script to disable checksuming in xdelta3 but it still don't get the game to start, so there must be more under the hood that is beyond my understanding.

**Comment by malinkb** [comment]
> @malinkb I think that this would not be a good idea like I said above to release the "Source" of the Patched Patch.

yeah, I totally agree :)

**Comment by calvinthefreak** [comment]
> so I tried to edit the script to disable checksuming in xdelta3 but it still don't get the game to start
@malinkb 

Yes, that definitively will not work, because the Patch is for the old version, it just verifies the Version and Patch and applies a different File per Version.

**Comment by martroxxx** [comment]
@legluondunet 
Sorry for the ping.

**Comment by codedetermination** [comment]
YES,I try run genshin impact using 2.80 script,but it seems not work ,please update,thanks!

**Comment by Snurf08** [comment]
This was added in a fork by [zeroday0619](https://github.com/zeroday0619) (use the fork till legluondunet updates) 

[[PATCH]](https://github.com/zeroday0619/MyLittleLutrisScripts)

**Comment by legluondunet** [comment]
Hello, I have no more interest to maintain this Lutris script as I do not play this game. 
If someone want to maintain thie Genshin Impact Lutris script, take my code and modify yourself the script on this page:
https://lutris.net/games/genshin-impact/
As a Lutris admin, I could validate your changes or your own script.
Don't forget to not talk about this patch on Discord or other public places and keep the patch original link secret, as his coder asked.

**Comment by legluondunet** [comment]
I just updated the Genshin Impact Lutris script page with @zeroday0619 updated link.

**Comment by martroxxx** [comment]
Well, thanks for your efforts, then.
Creating new patches would require us to know how they are made.

I would be able to step up, but would need to know details.

Could you please contact me on Discord about this?
 

Martroxxx#4196

Thanks for your contributions:
