### ISSUE TITLE
Moto Racer 2: Not launching after installation

### ISSUE THREAD

**Issue by 7HEPOW** [legluondunet/MyLittleLutrisScripts#14]
Freshly installed it didn't start. Applied "vidmemorysize=512" through protontricks and got to the intro video, but on a black screen without taking any input. Added -skipintro to the command line in dxwnd and now the game runs perfectly fine, but unfortunately misses the videos.

I'll have a look at it at later point to see, if I can get the videos working.

Here's my new ini file: [dxwnd.ini.zip](https://github.com/legluondunet/MyLittleLutrisScripts/files/3883078/dxwnd.ini.zip)

Current Specs: https://gist.github.com/7HEPOW/8e16a67cfe7864492abd4cb4f6988f1f

**Comment by legluondunet** [comment]
Fixed using this MR2 launch options:
 -d3d -KeepAvailableVram1073741824

**Comment by d-damien** [comment]
Hi ! Thanks for these Lutris scripts.

Where do you add these options ? In Game options > Executable or Arguments ? These seem to expect windows-like `/options`

Can't they be added to the default script ?
