### ISSUE TITLE
Tomb Raider III: The Lost Artefact 

### ISSUE THREAD

**Issue by tehradamant** [legluondunet/MyLittleLutrisScripts#140]
Hello! First of all, thank you for doing these scripts, I've trying to get other Tomb Raider games running for ages (2 and 3) and your scripts just worked for me. But now I'm getting an issue with The Lost Artifact expansion. Basically what happens is I launch the game and it crashes. Mostly I get to see the setup window, then the game starts, logos play fine and then I hear the first 0.1 seconds of the music and the game crashes. Tomb Raider 2, 3 and 4 seem to work fine (didn't try the other ones).
Here's the info about my system:
```
uname -a
Linux sam 5.19.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Sep 2022 18:09:09 +0000 x86_64 GNU/Linux
```
```
lsb_release -a
LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

Here's my lutris log
[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/9542553/lutris.log)

**Comment by legluondunet** [comment]
Hello @tehradamant , thank you for your report.
I fixed 2 bugs in my script, I just updated it on Lutris website.
Tell me if your issue is now resolved.
