### ISSUE TITLE
Genshin patch needs to be updated to 3.1

### ISSUE THREAD

**Issue by A-begger** [legluondunet/MyLittleLutrisScripts#141]
You can use [zeroday0619's patch](https://github.com/legluondunet/MyLittleLutrisScripts/compare/master...zeroday0619:MyLittleLutrisScripts:master#diff-ee67ffe7a67961b9b39b5ada677071bbbafb959055125992dfb8ca683d8c82a1)

**Comment by waffleboi9000** [comment]
For those who are impatient, you can apply the patch by downloading the 310 patch zip, extracting it, and using it to replace the old patch folder, located at /Games/genshin-impact/drive_c/.

**Comment by rekyuu** [comment]
Guess this issue can be updated for 3.2.
What entails into creating the patch files? I'd be happy to contribute if it isn't too complicated. Is there a community (ie, Discord, IRC, Reddit) around playing on Linux and where updates to patches are posted or discussed anywhere?

Thanks for the 3.1 patch by the way, it worked great!

**Comment by pjpmosteiro** [comment]
> For those who are impatient, you can apply the patch by downloading the 310 patch zip, extracting it, and using it to replace the old patch folder, located at /Games/genshin-impact/drive_c/. From there, just go to lutris, execute script, and patch it using the new files.

Where I  can find that file?

**Comment by legluondunet** [comment]
sorry, I no more support this game.
