### ISSUE TITLE
Rune - no sound

### ISSUE THREAD

**Issue by Helias** [legluondunet/MyLittleLutrisScripts#142]
uname -a `Linux helias-X580VN 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

lsb_release -a
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

Hi, I do not understand but using your lutris script for Rune or following [this guide](https://archive.org/details/Rune_Halls_of_Valhalla_Linux) the audio does not work on Rune, is it normal?

In particular, in the terminal I get
```
Bound to ALAudio.so
open /dev/dsp: Input/output error
open /dev/dsp: Input/output error
Audio initialization failed.
```

Before this, there were the error `/dev/dsp no such file or directory` and I fixed it installing `osspd osspd-pulseaudio`

**Comment by Helias** [comment]
I solved with:
```bash
sudo apt-get install libpulsedsp:i386
```

and adding this at the top of the `rune` content file
```bash
if [ x"$LD_PRELOAD" = x ] ; then
   LD_PRELOAD="/usr/lib/i386-linux-gnu/pulseaudio/libpulsedsp.so"
else
   LD_PRELOAD="$LD_PRELOAD /usr/lib/i386-linux-gnu/pulseaudio/libpulsedsp.so"
fi
export LD_PRELOAD
```
I changed the latency from `latency=40` to `latency=0` as suggested here https://askubuntu.com/a/1075572/1053352 to reduce the audio delay but I still experience some audio delay

**Comment by lfom** [comment]
For anyone coming here looking for a solution in the future, the above solution may work but will also add a delay to the sound, and OP noted. The correct solution is adding OSS support in your distro, as explained [here](https://www.alsa-project.org/wiki/Matrix:Module-hda-intel#modules.conf) (for the most common snd-hda-intel, make sure your kernel has the OSS modules). For Arch and derivatives (don't forget to also install lib32-alsa-oss):

https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture#OSS_compatibility

**Comment by Helias** [comment]
I discovered that the oss packages are "broken", so to solve the issue about the sound delay, you need to install the debian packages from this source https://packages.debian.org/search?suite=bullseye&searchon=names&keywords=osspd

**Comment by lfom** [comment]
I have just came across this, it is a good option if full OSS support via ALSA is not working (ALSA has builti-in emulation for OSS while osspd kind of redirects OSS to ALSA or PulseAudio using CUSE, usually available as kernel module) works pretty well with PulseAudio but I could not make it work with ALSA, and it seems that Debian/Ubuntu has it packaged:

https://github.com/libfuse/osspd

**Comment by legluondunet** [comment]
Hello,
I just reinstalled the game and made some tests, this game has aged badly.
The issues I found:
- no sound
- mouse can not access some part of the screen in fullscreen
- can not fully turn 380° with the mouse in fullscreen
- some missing characters (J of Join in Multiplayer)
- I tried to join several party online without success, connection failed for all games I tried to join on  master.333networks.com
- multiplayer joining window: news tab is empty
- can not access advanced options
...

Before testing the Linux version, I tested the "Rune Classic" version with Wine, available on GOG:
- not enough stable
- can not join all games online on master.333networks.com
- render still D3D7, sometimes framerate is very bad
- you have to launch an old RUNE version to play on network
- it misses several maps
- it misses the animated intro, replaced by a title video
It's a bad port that does not look as "finished".

Then I payed the "Rune Gold" version available on GOG, still on Linux with Wine.  
I had the best gaming experience with this version:
- very stable during several hours with solo game or online games
- you can update renderer to D3D9/10/11 (but use the D3D9 for better stability and less bugs)
- you can join all online games master.333networks.com, very nice stability and compatibility in multiplayer mode
I had a lot of fun with this version, enough to forgot I did play the game on Linux and not on the OS the game was developed for.

I don't want to maintain Lutris scripts for games that does not give a good game experience to user, so I decided to maintain only the "Rune Gold" script. You can still find Lutris scripts and related files in "OBSOLETE NO MORE MAINTAINED" folder.

**Comment by Helias** [comment]
thank you a lot for your job!

**Comment by lfom** [comment]
> * can not fully turn 380° with the mouse in fullscreen

This is the main problem I have now when trying to play the native Linux version. I tried to change the mouse multiplier in the game config file, and while it somewhat helped, it did not fix the problem. If anyone has any idea about to how to fix this issue, or what causes it, please let me know.

And thank you for the work done in this repo!
