### ISSUE TITLE
Silent Hill EE

### ISSUE THREAD

**Issue by HamConcerto** [legluondunet/MyLittleLutrisScripts#143]
Hi !
New on GitHub, so maybe it's not the good place to post.
It's not really a problem, but a related file that I can't find here.

I try  to install Silent Hill 2 EE with the latest patches, but SH2PC_Enhanced_EXE_NA_v1.0 is no longer available on the site.
I saw a link on Lutris that sent me here to find this patch.

I can't find it anymore on Silent Hill 2 section, did I miss something ?

Merci d'avance.

**Comment by legluondunet** [comment]
Hello, 
on  Silent Hill 2 EE website you will find only setup file that will download all necessary files to run the game on modern PC with enhanced assets and resolved bugs.
But if you only need the nocd exe, you can still download it here:
https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Enhanced_EXE_NA_v1.0.zip

**Comment by HamConcerto** [comment]
Wow, thanks for your quick answer, it's exactly what I was searching for !
No way to find the file on the site, I’m not very smart this time...

This file allows me to finally have the signs, streets or map names translated in French, and not only interface and text.
More convenient to discover the game for the first time I think.

Big thanks again.

**Comment by legluondunet** [comment]
de rien
