### ISSUE TITLE
Genshin Impact for update 3.5 broken

### ISSUE THREAD

**Issue by Ash3781** [legluondunet/MyLittleLutrisScripts#144]
Hey, please update the script so users can play genshin impact on the latest update

**Comment by Ash3781** [comment]
![2023-03-02_17-30](https://user-images.githubusercontent.com/37660156/222491358-5ec3613d-69ee-4cc6-ab49-32925924441b.png)
It still says you do :c
still thank you for doing the previous updates tho

**Comment by legluondunet** [comment]
it's an error, thank you to report me that.
Last time came from @zeroday019 https://github.com/zeroday0619
