### ISSUE TITLE
Warcraft III: Reforged - black screen or stuck on Lion head

### ISSUE THREAD

**Issue by AndrewDavis** [legluondunet/MyLittleLutrisScripts#146]
Hi, just wanted to report on how I fixed the black screen (with audio) problem when running WC3 Reforged on Linux in Lutris, using your script:

```
Lutris:
  install Warcraft III Reforged (Battle.net comes with it)
  configure settings->Runner options->Wine version->lutris-GE-Proton7-35-x86_64 (unsure if required)

Terminal:
  WINEPREFIX=/home/<user>/Games/warcraft-iii-reforged winetricks
    //Runs winetricks ON your SPECIFIC Warcraft III Reforged WINE PREFIX! Very important you use the right prefix!
    select the default prefix, which will now be the right one from this terminal
    open winecfg from the options
      set the Windows Version to Windows 7 (unsure if required)
      add "C:\Program Files (x86)\Warcraft III\_retail_\x86_64\BlizzardBrowser" to Applications
        select BlizzardBrowser in Applications then click Libraries
        in Libraries, add d3d11 and dxgi to the Existing overrides section (unsure if required)
          //This is probably what actually fixes the problem.

Lutris:
  launch "Warcraft III Reforged" (Battle.net)
  Battle.net:
    in the settings, set it to windowed mode using "-windowedmode windowed" in the options for the game (unsure if required)
    in the settings, set it to close when the game is launched (unsure if required)
    finally, launch actual Warcraft III Reforged

Also, the two paths you're gonna want to know are:

/home/<user>/Games/warcraft-iii-reforged/drive_c/Program Files (x86)/Warcraft III
/home/<user>/Games/warcraft-iii-reforged/drive_c/users/<user>/Documents/Warcraft III/Maps
```

**Comment by legluondunet** [comment]
Hello, thank you for your report.
In Lutris menu, Preferences, Hardware information, could you post your config info here?
I suspect a different behavior between Nvidia and AMD Gpu with this game.

**Comment by AndrewDavis** [comment]
Can do:

```
[System]
OS:              Linux Mint 21 Vanessa
Arch:            x86_64
Kernel:          5.15.0-67-generic
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 1400 Quad-Core Processor
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             15.6 GB
Swap:            2.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 515.86.01
OpenGL Core:     4.6.0 NVIDIA 515.86.01
OpenGL ES:       OpenGL ES 3.2 NVIDIA 515.86.01
Vulkan:          Supported
```

I've had very good success with Steam Proton/Vulkan games, and some success with other games like Mirror's Edge Catalyst and SC2. Also used to run BNet and WC3 just fine in years past, though I don't remember if that was Lutris or Wine or what, maybe both.

**Comment by legluondunet** [comment]
I still can not get W3R works with Lutris, even following your tweaks.
W3R works OK with:
- Bottles: just set Wine OS to Windows 7.
- Steam with Proton experimental: add a non steam game (I used my Lutris Battle.net install), select battle.net exe, launch it one time, close it. Launch protontricks and set Proton WIneprefix to WIndows 7.

I would like to understand why it doesn't work with Lutris and you can help me.
I need you:
- send me screenshots of your Lutris battle.net install configuration, all tabs (runner, system...).
- send me screenshots of your Wine runner configuration, all tabs.

In a second step, after took this screenshots, I need you try to reproduce W3R launching from zero:
- install a second Battle.net with Lutris (be carefull, use a different location than the first install or it will overwriting it).
- open battle.net and localize your W3R install to add it in your second battle.net install.
- now could you launch W3R correctly, it works? Without your tweaks? With your tweaks?
Thank you for help me debugging this Lutris installer.

**Comment by AndrewDavis** [comment]
Yeah no I'm not reinstalling it all over again.

I can tell you this:
- Make sure to actually follow all the directions as described, in order. E.g. select BlizzardBrowser before clicking the Libraries tab and adding the libraries, I was told that it's weird and actually only sets the libraries for the selection.
- I'm not 100%, but I think the BlizzardBrowser part was the most important or possibly the only necessary to solve the black screen problem. I mainly base this off of it not working before doing that and those being the steps to fix it that others mentioned in various internet locations pertaining to this problem.
- I am up-to-date. I also have all those Ubuntu pre-W3R updates that were listed I think in the Lutris installer link? The Github page.
- I'll say it again: Make sure to follow all the instructions I gave exactly and in order. Each of them was listed as solving this problem, so it might be a combination thing. The only one that I had to figure out without the internet telling me explicitly was the WINEPREFIX command to **make sure it's using the correct wine prefix** (the settings don't work if they're on the wrong prefix...).
- The lion head takes like 10s before moving on. I think even when it didn't work it still went away and I only heard audio and saw a black screen.

I bet if you do all that it will work. I'm 98% I did nothing else.

**Comment by AndrewDavis** [comment]
Oh and I've never actually bought Reforged (only the old game from way back when), not sure if that affects things. I installed your Reforged script but I'm using the free Reforged. Can't explain better than that because I don't understand it myself. It's Reforged but it's not the purchased Reforged.....

But yeah make sure to follow each item in the instructions... Close BNet once the game is launched, that's another that fixed it for some... Etc.

**Comment by AndrewDavis** [comment]
Here was the Github page: https://github.com/lutris/docs/blob/master/InstallingDrivers.md

Note that they say to reboot after to apply.

Also there are multiple Lutris scripts for Reforged, not sure if that changes things? If you tell me how I can figure out which one I used, obviously it installed BNet. https://lutris.net/games/warcraft-iii-reforged/

**Comment by legluondunet** [comment]
Could you at least post here this two files:
- /home/your_user_profile/.config/lutris/runners/wine.yml
- /home/your_user_profile/.config/lutris/system.yml
- /home/your_user_profile/.config/lutris/games/warcraft-iii-reforged.yml
Thanks.

**Comment by legluondunet** [comment]
Which script did you install on this page:
https://lutris.net/games/warcraft-iii-reforged/
"Battle.Net version" or "Another version"?

**Comment by AndrewDavis** [comment]
> Which script did you install on this page

Don't know.

> If you tell me how I can figure out which one I used, obviously it installed BNet.

^

---

> - /home/your_user_profile/.config/lutris/runners/wine.yml

`/runners/` is empty.

> - /home/your_user_profile/.config/lutris/system.yml

Also doesn't exist.

> - /home/your_user_profile/.config/lutris/games/warcraft-iii-reforged.yml

```
game:
  arch: auto
  exe: drive_c/Program Files (x86)/Warcraft III/Warcraft III Launcher.exe
  prefix: /home/<user>/Games/warcraft-iii-reforged
system:
  disable_compositor: true
wine:
  Desktop: true
  dxvk: true
  system_winetricks: true
  version: lutris-GE-Proton7-35-x86_64
```

**Comment by legluondunet** [comment]
I finally found why W3R do not launch on my two different computer with Lutris, each time it was related to Lutris discrete GPU parameters and ICD loader. After all my tests and serches, I think there are only two must-haves on your list:  set Wine OS to Windows 7 and use a recent lutris-proton-ge wine version. I am now certain that the other options are not necessary. I can now update Battle.net and W3R Lutris scripts. Thank you again for your help and contribution.

**Comment by AndrewDavis** [comment]
That may be true in your case but not necessarily for others.

**Comment by AndrewDavis** [comment]
By the way, do you know why Battle.net is always having me update before I launch? Is there some sort of false file storage operation not coming through? It doesn't take long but it happens every time.
