### ISSUE TITLE
The Secret of Monkey Island - Special Edition - GOG

### ISSUE THREAD

**Issue by tyjuji** [legluondunet/MyLittleLutrisScripts#15]
I ran the installer from https://lutris.net/games/the-secret-of-monkey-island-special-edition/
Installer reports: `RuntimeError('specified exe is not an archive or GOG setup file')`

Lutris log: https://pastebin.com/ZwjtkAkV

Uname -a:
`Linux tyjuji-mj 5.4.2-1-MANJARO #1 SMP PREEMPT Thu Dec 5 09:55:57 UTC 2019 x86_64 GNU/Linux`

lsb_release -a:
```
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	18.1.4
Codename:	Juhraya
```

**Comment by legluondunet** [comment]
I can reproduce this issue on Manjaro.

**Comment by legluondunet** [comment]
added innoextract, solved.

**Comment by rayrapetyan** [comment]
https://github.com/lutris/website/issues/402
