### ISSUE TITLE
Little scripts are not so little...

### ISSUE THREAD

**Issue by rayrapetyan** [legluondunet/MyLittleLutrisScripts#153]
Hello, I wanted to express my appreciation for your repository, as I've recently forked it. While cloning the repository, I noticed that it occupied 4.6GB of disk space, which appears to be quite substantial. I understand that this might be due to the storage of binary data required by games at runtime.

Would you mind moving all binary files elsewhere? I know there are not so many options. But these few worth to check:

1. Cloudflare's R2 storage (similar to AWS S3, 10 GB / month free);
2. Git LFS (native to git, but requires a wrapper script to download directly);
3. AWS S3, google storage etc - these may cost few bucks per month

Thank you for your consideration, and please let me know if you have any questions or concerns.

**Comment by legluondunet** [comment]
Hello @rayrapetyan,
when the files are too large, I have no choice but to store them elsewhere. 
But I prefer to store my code and files in the same place, for reasons of practicality, simplicity and saving time.
