### ISSUE TITLE
Jazz Jackrabbit 2 - Fullscreen widescreen support

### ISSUE THREAD

**Issue by rea987** [legluondunet/MyLittleLutrisScripts#155]
Greetings,

Recent releases of JJ2+ support additional resolutions such as 800×450 which fits 16:9 widescreen monitor natively. Can this resolution and fullscreen widescreen support added to the script for Jazz Jackrabbit 2 please? Thank you!

Kind regards,
REA

**Comment by legluondunet** [comment]
Hello @rea987 , I wrote two scripts for Jazz Jackrabbit 2 game. Which one are you talking about?

**Comment by rea987** [comment]
@legluondunet This one;

https://lutris.net/games/install/31468/view

Also, the script seems to install and launch vanilla game instrad of JJ2+ v5.12 bundled installer. It would be great to have JJ2+ as default with 800×450 resolution in 16:9 aspect ratio in fullscreen mode

**Comment by legluondunet** [comment]
>the script seems to install and launch vanilla game instrad of JJ2+
It's was the objectif of this script, play vanilla version of this game.

I already tried to write a JJ2+ script installer with wine but it didn't work.

To have a JJ2+ experience, I wrote a second script using "Jazz2 Resurrection" open source project, you should try it.

**Comment by rea987** [comment]
Unfortunately J2R doesn't support online multiplayer right now. Thanks for the script anyway!

**Comment by legluondunet** [comment]
Hello again @rea987 , I just tried again to install and play JJ2+ with Wine and it seems Wine has now better compatibility for this game. This point still needs to be verified but I will try again to write a Lutris installer script for it. It will replace my actual Wine Lutris script that is today redundant with script installer using J2R open source project.
But J2R does not support yet Multiplayer games so it could be interesting to have a Wine version to benefit this feature.
GOG provides 3 JJ2+ version: 
![image](https://github.com/legluondunet/MyLittleLutrisScripts/assets/325405/89e35c95-75fb-4e1b-9b96-09e9ec7abb0c)
I will use the most recent one: 5.12
So you will need to own the JJ2+ GOG version to play.

**Comment by legluondunet** [comment]
@rea987 , could you test new script called "DxWnd + JJ2+ version" and report here 
>Will there be fullscreen 800×450 resolution with 16:9 aspect ration support?

I think you can choose this resolution in graphic menu options.

**Comment by rea987** [comment]
@legluondunet I can do that next month when I return home. I will let you know once I try it. Cheers!

**Comment by rea987** [comment]
> I think you can choose this resolution in graphic menu options.

@legluondunet I finally managed to try the script. It runs JJ2+ v5.12 just fine. However, it supports only 800x600 DirectDraw (4:3) and 640x480 DirectDraw (4:3) resolutions fullscreen. Actually, those are the only resolutions available in default options menu. Other resolutions can be seen in top menu brought by JJ2+ but cannot be chosen with your script. In its current form, the game's resolution is stretched in widescreen monitors. Is there a way to support 800×450 (16:9) fullscreen?
![resim](https://github.com/legluondunet/MyLittleLutrisScripts/assets/1547646/86d35b2a-71ae-4277-b928-3e6d5b5b16c9)

**Comment by legluondunet** [comment]
I updated script installer without any wrapper, so no videos intro or cinematics.
But you should now  play this game in widescreen mode.

**Comment by legluondunet** [comment]
I updated script installer again but this time I use cnc-draw. After submitted a bug report to cnc-draw dev, JJ2+ works now very well on Linux/Wine with this wrapper:
- better stability, no more crash or freeze
- widescreen enabled
- 4:3 ratio enabled for video and 16:9 for the game interface
- alt+enter to access menu
- alt+backspace to change fullscreen/window

I made several test (and crash tests), this work very well, tell me if it is the same result for you.

**Comment by rea987** [comment]
@legluondunet Works beautifully, finally I will be able to play JJ2 coop with my wife. Thanks, merci!
