### ISSUE TITLE
Starcraft : ddraw dans le mauvais répertoire

### ISSUE THREAD

**Issue by Fromstream** [legluondunet/MyLittleLutrisScripts#156]
Bonjour Legluondunet,
et bravo pour tes scripts Lutris ! Ils sont vraiment très impressionnants.
Sur ton dernier script pour Stracraft, j'ai néanmoins noté que les petits ajouts (ddraw, *.mpq) sont installés dans "Program Files (x86)" alors que chez moi l'installation de Starcraft se fait dans le réperoire "Program Files". J'ai donc dû déplacer les fichiers manuellement du premier répertoire vers le deuxième pour que tout fonctionne correctement (idem pour Brood War).
Saurais-tu d'où peut venir cette différence à l'installation ?

**Comment by legluondunet** [comment]
Salut @Fromstream , tu utilises la version anglaise ou française de Starcraft? As-tu également installé l'extension Brood War?

**Comment by Fromstream** [comment]
Salut Legluondunet. J'ai installé la version française, pour être précis celle téléchargée sur le site abandonware-france. J'ai également installé Brood War qui a le même type de problématique. Mais une fois tout repositionné dans "Program Files", tout fonctionne parfaitement.
Je n'ai pas vérifié mais de mémoire la différence entre le répertoire "Program Files" et "Program Files (x86)" était lié à des histoires de 32 bits Vs 64 bits.

**Comment by legluondunet** [comment]
Alors, pour l'explication, suivant les versions des CD, le jeu s'installe dans le répertoire "Program Files/Starcraft" ou "Program Files (x86)/Starcraft". J'ai modifié le script pour gérer les deux cas et même corrigé quelques bugs. Pourrais-tu réessayer de l'installer et me faire un retour? Merci.

**Comment by Fromstream** [comment]
Ça fonctionne nickel. Un lien symbolique ! C'est très élégant ! Merci et encore bravo. Tes scripts sont très inspirants.
Pour ma culture générale, pourrais-tu me conseiller de la documentation sur cnc-ddraw ?

**Comment by legluondunet** [comment]
Aucune idée, à part contacter son développeur sur cette page: https://github.com/FunkyFr3sh/cnc-ddraw
