### ISSUE TITLE
Warcraft III installation stuck at black screen

### ISSUE THREAD

**Issue by cewbdex** [legluondunet/MyLittleLutrisScripts#157]
When I try to install WCIII, the installer starts and is either all black or all blue.

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/13317540/lutris.log)
[distribution.txt](https://github.com/legluondunet/MyLittleLutrisScripts/files/13317557/distribution.txt)
[config.txt](https://github.com/legluondunet/MyLittleLutrisScripts/files/13317602/config.txt)

Sorry for my previous post, I must have missed it.

**Comment by tom-orchard** [comment]
I'm really new to lutris and wine so forgive me if this isn't correct.

Reading through the lutris.log I can see on line 114:
wine: Read access denied for device L"\\??\\F:\\", FS volume label and serial are not available.

Maybe could come down to a permission error with wine accessing the storage location you're trying to install to?

**Comment by cewbdex** [comment]
Yes, I was wondering too, but I already installed a dozen of games into ~/Games and I was installing from an ISO and then I tried extracting it and installing from there and still the same. However the setup above worked when I did not use the install script and selected manual installation from exe in Lutris. But thanks for the idea. I forgot to include the details here.

**Comment by legluondunet** [comment]
Hello,
please mount your WC3 iso, open a terminal and execute this command:
find "path_to_your_warcraft3_CD">w3cd.txt

Finaly upload "w3cd.txt" here.

**Comment by cewbdex** [comment]
Hello, here:
[w3cd.txt](https://github.com/legluondunet/MyLittleLutrisScripts/files/13342500/w3cd.txt)

**Comment by legluondunet** [comment]
Your CD looks fine. Could you install Warcraft III from your CD without Lutris?

**Comment by cewbdex** [comment]
I have installed from the ISO on my other Windows 10 machine before. I have tried this:
![obrazek](https://github.com/legluondunet/MyLittleLutrisScripts/assets/9021297/9aee2e4b-c58b-40bd-ab58-00fc236a9801)
And the menu displays correctly.

Czech.

**Comment by legluondunet** [comment]
I never tested my script with a Warcraft III CD Czech version, only French and English/International.

**Comment by legluondunet** [comment]
@cewbdex  do you know where I can download a Warcraft III czech version?

**Comment by cewbdex** [comment]
Sorry, I tried to download English one and didn't find it, so I put it for later when I have more time for this. I believe one of those should work: https://gozofinder.com/cse/ulozto/cz?query=warcraft+III+iso if, not, I can provide mine.

**Comment by legluondunet** [comment]
I can not access your link:
![image](https://github.com/legluondunet/MyLittleLutrisScripts/assets/325405/82819b89-d99b-49e0-bd7c-e4e51594d587)

**Comment by legluondunet** [comment]
I can not help you without a Warcraft III iso with czech language. 
You could reopen this issue if you find one.
