### ISSUE TITLE
Age of Empires - Unable to load libGLX_nvidia.so.0

### ISSUE THREAD

**Issue by TheFrenchGhosty** [legluondunet/MyLittleLutrisScripts#158]
Hello, while trying to install age-of-empires-gold-cd-edition-dxwn the installer errors out and "crashes" 

This happens after the game installer itself is finished and just after selecting the language in lutris.

Pressing back from the error, and continuing from there make it so the install finish, but the game never open after that.

Using Lutris' flatpak on a machine with an Intel Ivy bridge APU (could this old APU be the issue?).

Log:

```
[INFO:2023-12-31 21:13:33,967:files_box]: All files available
[INFO:2023-12-31 21:13:33,968:installerwindow]: All files are available, continuing install
[INFO:2023-12-31 21:13:33,997:wine]: Creating a win64 prefix in /home/<username>/Games/age-of-empires
[INFO:2023-12-31 21:13:55,298:wine]: win64 Prefix created in /home/<username>/Games/age-of-empires
[ERROR:2023-12-31 21:13:55,457:nvidia]: Unable to load libGLX_nvidia.so.0
[WARNING:2023-12-31 21:13:55,457:nvidia]: Unable to locate libGLX_nvidia
[ERROR:2023-12-31 21:14:13,767:nvidia]: Unable to load libGLX_nvidia.so.0
[WARNING:2023-12-31 21:14:13,768:nvidia]: Unable to locate libGLX_nvidia
[WARNING:2023-12-31 21:15:00,792:interpreter]: No template string given
[WARNING:2023-12-31 21:15:00,799:interpreter]: No template string given
[WARNING:2023-12-31 21:15:00,800:interpreter]: No template string given
[WARNING:2023-12-31 21:15:00,814:interpreter]: No template string given
[ERROR:2023-12-31 21:15:05,175:nvidia]: Unable to load libGLX_nvidia.so.0
[WARNING:2023-12-31 21:15:05,176:nvidia]: Unable to locate libGLX_nvidia
[ERROR:2023-12-31 21:15:12,197:errors]: Command exited with code 256
[ERROR:2023-12-31 21:15:12,197:exceptions]: Command exited with code 256
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/exceptions.py", line 67, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/installer/commands.py", line 450, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 256
[INFO:2023-12-31 21:15:20,716:interpreter]: Cancelling installation of Age of Empires
```

**Comment by TheFrenchGhosty** [comment]
Follow up:

I tried to install this on a Steam Deck (with Lutris' flatpak) and even though the install didn't error out, the game never started (it was running according to htop but nothing was appearing) -> Nothing special in the game logs

I then tried, on the Ivy Bridge PC, Lutris from the Debian repository: the install didn't error out, but the game never started (like on the Steam Deck, it was running according to htop but nothing was appearing) -> Nothing special in the game logs

Looks like it's broken no matter what :(

**Comment by legluondunet** [comment]
Hello @TheFrenchGhosty , thank you for your report.
I don't own a Steam Deck but if a Lutris script works on Linux, should work on SteamOS too.
Perhaps this script needs an update.
I will test it this week.

> Lutris is awful...

Lutris help a lot of people to install a their games on Linux, it facilitates their gamer life.
Don't be so ungrateful ;)

**Comment by legluondunet** [comment]
Hello, I fixed 2 bugs in this script installer, could you try again?
- use a multi5 édition (English, Franche-Comté etc...)
- after install finished, configure the game to use Wine version from your system, not Lutris one (I do not know if it is possible on Steam Deck?)

**Comment by TheFrenchGhosty** [comment]
I just reinstalled on the Steam Deck:

The installation didn't error out.

I ran the game with the "default" wine version -> like last time  the game never started (it was running according to htop but nothing was appearing) 

I changed the Wine version to "System (8.0.2) = it worked instantly

**Comment by TheFrenchGhosty** [comment]
I just reinstalled on the Ivy Bridge PC (Lutris from the Debian repository):

Same as on the Steam Deck, the default wine version is broken, and the system wine works.

Could it be that the wine you choose is now broken?

**Comment by legluondunet** [comment]
@TheFrenchGhosty  I just wrote a BIG update to the AOE Gold Edition Lutris script, could you test it? And if everything works as expected for you, don't forget to close your issue.
