### ISSUE TITLE
Unreal Gold Linux Script not working sometimes.

### ISSUE THREAD

**Issue by TimeFreeze1337** [legluondunet/MyLittleLutrisScripts#16]
So i dont really know whats wrong there. When i start it and type 2 for Linux sometimes nothing happens. Windows works always but the Linux Script sometimes refuses to run in the .bat i guess. When i run it manually in the folder it starts without an issue. So my guess it could be something with the .bat? 

No LSB modules are available.
Distributor ID: neon
Description:    KDE neon Testing Edition
Release:        18.04
Codename:       bionic

Linux timefreeze-ThinkPad-X200 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/4008258/lutris.log)

**Comment by legluondunet** [comment]
I can not reproduce your issue.
