### ISSUE TITLE
Splinter cell install fails when picking english

### ISSUE THREAD

**Issue by ZinZalo** [legluondunet/MyLittleLutrisScripts#161]
When I pick English in the Splinter Cell installer I get an error saying  "$CACHE/sc1_multi5_int.zip does not exit" and then the install doesn't finish. If I pick a different language (like German) then the install is successful.

**Comment by legluondunet** [comment]
Hello @ZinZalo , thank you for your report, should be fixed now, could you try to install it again and confirm me it works for you?

**Comment by ZinZalo** [comment]
Tested it and now it works. Thanks!
