### ISSUE TITLE
Game Won't Start - Silent Hill 2 EE

### ISSUE THREAD

**Issue by Badzilla4lyfe** [legluondunet/MyLittleLutrisScripts#162]
Hello, first I'd like to thank you for all you do with Lutris and retaining old games. I'm very new to all this so bear with me. I am attempting to install SH2 EE on a 64gb Steam Deck, on a micro SD.

1. The second download of your lutris pack, the knife cursor, doesn't seem to work properly. At the end of the installation, Lutris states it can't find that file. I had to manually download it, then create a location within the SH2 file where Lutris was looking to get past that point of the installation process.
2. The game simply won't start. I've tried different versions of wine. I've tried uninstalling and reinstalling. I keep getting wine code 13568. I know that you work with Lutris and not wine so perhaps my issue is with wine but I'm not sure.

Thank you for all  your help.

**Comment by legluondunet** [comment]
Hello,
I can not reproduce your issue on a classic Linux distribution and I don't own a SteamDeck.
To help you, I need logs!
To create a log, first close Lutris completely. Then, open your terminal application, execute 
lutris -d 
and try to reproduce your issue.
After that, you need to copy the output in the terminal in a text file and join it here.

**Comment by Badzilla4lyfe** [comment]
Hello!

Thanks for reaching out. I attempted what you said (I'm assuming you mean the terminal app on the steam deck, which is the konsole) and entered the command. The response I got was bash: lutris: command not found.

**Comment by legluondunet** [comment]
On Steamdeck you use Lutris Flatpak package, so type this command in your terminal instead:
flatpak run net.lutris.Lutris -d
