### ISSUE TITLE
Theme Hospital (CorsixTH) Code 256

### ISSUE THREAD

**Issue by Mumrik93** [legluondunet/MyLittleLutrisScripts#163]
**lutris.txt and distribution.txt at the very bottom!**

I've tried to install Theme Hospital (with CorsixTH) a few times now and and I keep getting an error message (code: 256) The download seems to work great but the error comes up during installation, the install never finishes, it simply stops after the error message.
 
**-------------------------------------------------------
System info
-------------------------------------------------------**
[System]
OS:              Linux Mint 21.3 Virginia
Arch:            x86_64
Kernel:          6.5.0-26-generic
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3600 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.6 GB
Swap:            29.8 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.161.07
OpenGL Core:     4.6.0 NVIDIA 535.161.07
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.161.07
Vulkan:          Supported

[lutris.txt](https://github.com/legluondunet/MyLittleLutrisScripts/files/14856698/lutris.txt)
[distribution.txt](https://github.com/legluondunet/MyLittleLutrisScripts/files/14856699/distribution.txt)

**Comment by legluondunet** [comment]
> INFO     2024-04-03 20:16:14,558 [startup.init_lutris:173]:Starting Lutris 0.5.10.1

Hello @Mumrik93  ,
your Lutris version is obsolete.
You can download latest version here:
https://github.com/lutris/lutris/releases

Tell me if you can reproduce your issue with latest Lutris version.
