### ISSUE TITLE
Wolfenstein 3D - Spear of Destiny gog, not installing

### ISSUE THREAD

**Issue by coffandro** [legluondunet/MyLittleLutrisScripts#169]
I try to run the Wolfenstein 3D - Spear of Destiny install script and it fails with the below failure, seems the cache files are named M1 and not m1 which are causing the issue.

[lutris.txt](https://github.com/user-attachments/files/16168754/lutris.txt)

![image](https://github.com/legluondunet/MyLittleLutrisScripts/assets/75324436/c6e62d7a-de05-4b86-88a6-90eaf3e0521b)

**Comment by legluondunet** [comment]
Hello, thank you for your report, I just updated the script installer, does it work for you now?

**Comment by coffandro** [comment]
Did you remember to push?
![image](https://github.com/user-attachments/assets/6620229e-227b-4893-aa68-3be21f4ad5bf)

**Comment by legluondunet** [comment]
I updated code on the Lutris site, not here, there is no sync between them. 
I will update my code here when I will be sure the script installer is totally functionnal.

**Comment by coffandro** [comment]
Same issue :/

**Comment by legluondunet** [comment]
you click install button from this page right? gog version?
https://lutris.net/games/wolfenstein-3d-spear-of-destiny/

**Comment by legluondunet** [comment]
please try again and download again the setup file (do not use cache)
and post here Lutris log, tk

**Comment by coffandro** [comment]
I downloaded the script from the website, it didn't work and I couldn't get logging working.
simply changing every instance of m1 with M1 fixed it completely and now it dosen't have any issues, attached is the working version.
[wolfenstein-3d-spear-of-desti-gog-ecwolf.json](https://github.com/user-attachments/files/16184152/wolfenstein-3d-spear-of-desti-gog-ecwolf.json)
