### ISSUE TITLE
Can not install StarCraft 1998

### ISSUE THREAD

**Issue by rkarpuzov** [legluondunet/MyLittleLutrisScripts#173]
Hello,

I have Mageia 9 64 bit, but I have trying with both wine32 and win64 bit version  without success.

Best regards,
Rossen

P.S. Next report files are while I have only wine32 installed:

[distribution.txt](https://github.com/user-attachments/files/17048358/distribution.txt)
[config.txt](https://github.com/user-attachments/files/17048450/config.txt)
[lutris.txt](https://github.com/user-attachments/files/17048555/lutris.txt)

**Comment by legluondunet** [comment]
Hello, thank you for your report, I need full Lutris log, yours is incomplete.
All the Lutris scripts I wrote are only compatible with OS and Wine 64 bits.

**Comment by legluondunet** [comment]
no answer, I close.
