### ISSUE TITLE
Rayman 2 (GOG) - Sound FX and some music triggers disappear mid-level

### ISSUE THREAD

**Issue by GChetard** [legluondunet/MyLittleLutrisScripts#174]
Hi,

This is a weird issue in Rayman 2 which I could reproduce on two different PC, both running Linux Mint.

The game runs flawlessly, but after a while in a level, all sound effects suddenly turn off. It seems to happen after triggering certain background music changes or changing level sections. The background music then stays the same until the end of the level, even when it should change again.

The bug stops and the game switches back to normal sound when leaving a level into the hub world, either by quitting or reaching finish.

Could this have anything to do with the dsoal?

Thanks in advance. Despite that, this is a great install script.

[config.txt](https://github.com/user-attachments/files/17451978/config.txt)
[distribution.txt](https://github.com/user-attachments/files/17451979/distribution.txt)
[lutris.txt](https://github.com/user-attachments/files/17451980/lutris.txt)

**Comment by legluondunet** [comment]
Hello, thank you for  your report. Could you reproduce this issue if you rename dsound.dll to dsound.bak?

**Comment by GChetard** [comment]
Hi, thank you for responding so quickly.

Two things:
- Before switching to dsound.bak, I played more. It is not only sound effects. All sounds in the game go silent one after the other, music included. In long levels, the game is basically muted.
- I just tried switching to dsound.bak. First impressions: I still have in-game music, but no sound effects play at all. I'll keep playing and see if music turns itself off again.

**Comment by GChetard** [comment]
Seems like dsound.bak deactivates all sound effects, but preserves music cues. I have played a bunch of levels that way now.

**Comment by legluondunet** [comment]
In Lutris, right click on the game and choose "configure".
Then, in third tab, remove "dsound":
![image](https://github.com/user-attachments/assets/5e0ff72a-a387-4349-a880-0aea0529c054)

**Comment by legluondunet** [comment]
I can finally reproduce your issue, I'm working on it.

**Comment by GChetard** [comment]
Great! Thank you so much for your work on this :D

**Comment by legluondunet** [comment]
In "drive_c/GOG Games/Rayman 2/DLL/"
folder, delete this files:
SND_CPA.INI
WAVa1BVR.dll
then replace them by the files from this archive:
[raysound.zip](https://github.com/user-attachments/files/17492596/raysound.zip)
does this resolve your issue? Do you hear now ambiant audio and sound effect?

**Comment by legluondunet** [comment]
fixed!

**Comment by GChetard** [comment]
I confirm this is fixed now, thank you again!
