### ISSUE TITLE
Unable to install Warcraft II: Battle.net Edition

### ISSUE THREAD

**Issue by ed168** [legluondunet/MyLittleLutrisScripts#177]
I just installed Lutris from Flathub, see below for the computer system information report from the client.
When initiating the wine install script for the game titled Battle.net launcher it states the blizzard-battlenet-standard is missing and asks if I want to install it. 
Selecting "yes" just produces a pop-up message saying "No installer available" and nothing else further can be done.
I then installed the Battle.net client from Lutris and retried the game install but still get the missing dependency message.
Not sure what else  to try.

Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: YES
[System]
OS: GNOME 45 Flatpak runtime
Arch: x86_64
Kernel: 6.11.10-300.fc41.x86_64
Desktop: GNOME
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
Physical cores: 2
Logical cores: 4
[Memory]
RAM: 11.6 GB
Swap: 8.0 GB
[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 4000 (IVB GT2)
OpenGL Version: 4.2 (Compatibility Profile) Mesa 24.2.5 (git-3b9fcb7e4d)
OpenGL Core: 4.2 (Core Profile) Mesa 24.2.5 (git-3b9fcb7e4d)
OpenGL ES: OpenGL ES 3.0 Mesa 24.2.5 (git-3b9fcb7e4d)
Vulkan Version: 1.3.261
Vulkan Drivers: Intel(R) HD Graphics 4000 (IVB GT2) (1.2.289), NVIDIA GeForce GT 640M LE (1.2.175)

**Comment by legluondunet** [comment]
Hello, thank you for your report, should be fixed now.
