### ISSUE TITLE
Tomb Raider 1 (Wine + GOG + TombATI HD)

### ISSUE THREAD

**Issue by GruenTentakel** [legluondunet/MyLittleLutrisScripts#19]
Is there a way to use this script with the german version of Tomb Raider I (GOG)?
I can't get it to work.

In combination withe the english version of the game the script works fine.

**Comment by legluondunet** [comment]
Hello, I have french and english version, but not german.

Le dim. 9 févr. 2020 à 08:04, GruenTentakel <notifications@github.com> a
écrit :

**Comment by legluondunet** [comment]
Hello,
I just finished update TR1 script installer:
- compatibility with GOG German setup file
- added translations (interface + cutscenes) for  English, French and German
- added translations (cutscenes) for Japanese
- added translations (interface) for Spanish, Finish, Hungarian, Indonesian, Italian, Dutch, Portuguese and Swedish

Could you give it a try and tell me if:
- it fixes your issue? 
- you have interface and audio in german?

Translations credits:
https://www.tombraiderforums.com/showthread.php?t=213154
Credits:
Alejandro Cambronero Albaladejo, Andreu O.R., b122251, barracuda415, Dankó Roland, Daviz, Eurico Andrade, Fernando D.S., Gyurka Balázs, Joey79100, Joonas, JvR, Kerrie B., Kevin Villar, Riccardo Galeotti, Rubén V.C., Rui Cassio Camisão, Taufan Atalarik & Ville Reinikainen.

**Comment by GruenTentakel** [comment]
Hi,

it seems the script doesn't work anymore. Lutris says after all downloads are done: "Source does not exist: /home/myname/.cache/lutris/installer/tomb-raider-i/app/DATA".

Then I'am forced to abort the installation.

I let all options by default

In my GOG-Libary i have two versions of Tomb Raider I:

english version:
setup_tomb_raider_1_20180105_(17652).exe

german version:
setup_tomb_raider_1_german_20180105_(17652).exe

Is there a way to force your script to take the german version of the game (setup_tomb_raider_1_german_20180105_(17652).exe)?
[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/4270932/lutris.log)

**Comment by legluondunet** [comment]
I updated again my TR1 installer script, please try again, with english or german setup file.

**Comment by GruenTentakel** [comment]
I have deleted all cache- and config-files, but i still get this error-message after all files are downloaded:

"Source does not exist: /home/myname/.cache/lutris/installer/tomb-raider-i/app/DATA"

Then I'am forced to abort the installation.

I let all options by default.

**Comment by legluondunet** [comment]
I just tried to install GOG TR1 again, on different computer and distribution, it works. I can not reproduce your issue.
What is your distribution: Name, version, 32 or 64 bits? 
Coud you post the result of this command here:
lutris -d
copy/paste the lines in the terminal and then I should obtain enough info to help you.

**Comment by legluondunet** [comment]
I finally reproduced your issue.
Please follow this steps:
1) launch Lutris, go to  "import games" and disconnect from GOG
2) uninstall TR1 from Lutris,
3) launch TR1 install
4) if you correctly disconnected GOG in Lutris, Lutris will ask you for the GOG setup file.
5) choose english or german setup file

It seems there is a Lutris bug with automatic  GOG setup file download.

**Comment by legluondunet** [comment]
What Lutris version are you using?

**Comment by legluondunet** [comment]
Please update Lutris to last version or wait your distribution provide you the last version with this issue fixed:
https://github.com/lutris/lutris/issues/2638

**Comment by GruenTentakel** [comment]
The last version of Lutris fixes everything for me.

Your script works like a dream.

Thank you very much.
