### ISSUE TITLE
Warcraft: Orcs & Humans Mouse Issues

### ISSUE THREAD

**Issue by NathanHannon** [legluondunet/MyLittleLutrisScripts#2]
The mouse won't integrate with the game window after launch

**Comment by legluondunet** [comment]
Hello Nathan, I just tested:
effectively per default the game launched in window mode and the mouse was not integrated, even if I press ctrl+f10.
Then I pressed alt+enter, the mouse integrated correctly in fullscreen.
Lutris uses Dosbox-CE runner, I tried again with a more recent version and I can not reproduce this bug.
I asked Lutris dev team to update  Dosbox-CE to a more recent version. https://github.com/lutris/lutris/issues/2346

**Comment by NathanHannon** [comment]
Excellent! Thanks for the quick reply.

**Comment by legluondunet** [comment]
Should be resolved now (cf issue lutris/lutris#2346).
