### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by lenywan** [legluondunet/MyLittleLutrisScripts#21]
Hi !
When i start to install the scripts for tomb raider 2 on the lutris website, it starts well then a few seconds after the download is interrupted on:
Downloading https://github.com/legluondunet/MyLittleLutrisScripts/raw/master/Tomb Raider II/TR2M1.BAT

Do you have any ideas on what am i suppose to do ?

Hello, to report your issue, please follow this steps:
    
    1) start Lutris in debug mode, in a terminal type this command:
    lutris -d > lutris.log
    2) if already installed, uninstall (remove) your game
    3) now come back to your game Lutris page installer and reinstall it. 
    At the end of the install, try to launch the game. 
    If the issue persists, please post the lutris.log debug file to this thread
    4) copy/paste the results of this 2 commands:
    uname -a
    lsb_release -a
    5) put the game name in the issue report title

Thank you for your issue report.

**Comment by legluondunet** [comment]
Hello, I found and corrected a bug in my script installer, should work now.
