### ISSUE TITLE
Tomb raider 2 :  "I can't move /home/lenywan/.cache/lutris/installer/tomb-raider-ii/app, it does not exist"

### ISSUE THREAD

**Issue by lenywan** [legluondunet/MyLittleLutrisScripts#22]
Hi ! 
The message error when i install tomb II: "I can't move /home/lenywan/.cache/lutris/installer/tomb-raider-ii/app, it does not exist" 

This is the terminal log ! That's what you want to see?

```
lenywan@lenywan:~$ lutris -d > lutris.log
DEBUG    2020-02-17 16:45:11,384 [http]:GET https://lutris.net/api/runtime
DEBUG    2020-02-17 16:45:11,572 [runtime]:Runtime Ubuntu-18.04-i686 is already up to date (locally updated on sam. 01 févr. 2020 16:09:38 GMT, remote created on jeu. 09 janv. 2020 18:39:38 )
DEBUG    2020-02-17 16:45:11,572 [runtime]:Runtime Ubuntu-18.04-x86_64 is already up to date (locally updated on sam. 01 févr. 2020 16:09:38 GMT, remote created on jeu. 09 janv. 2020 18:39:36 )
DEBUG    2020-02-17 16:45:11,572 [runtime]:Runtime winetricks is already up to date (locally updated on sam. 01 févr. 2020 16:09:36 GMT, remote created on ven. 27 déc. 2019 14:50:49 )
DEBUG    2020-02-17 16:45:11,573 [runtime]:Runtime p7zip is already up to date (locally updated on sam. 01 févr. 2020 16:09:36 GMT, remote created on mar. 03 sept. 2019 03:31:01 )
DEBUG    2020-02-17 16:45:11,573 [runtime]:Runtime x360ce is already up to date (locally updated on mar. 08 janv. 2019 17:33:17 GMT, remote created on sam. 15 déc. 2018 11:33:12 )
DEBUG    2020-02-17 16:45:11,573 [runtime]:Runtime dumbxinputemu is already up to date (locally updated on mar. 08 janv. 2019 17:33:22 GMT, remote created on sam. 15 déc. 2018 11:32:50 )
DEBUG    2020-02-17 16:45:11,573 [runtime]:Runtime gamecontrollerdb is already up to date (locally updated on mar. 08 janv. 2019 17:33:13 GMT, remote created on sam. 15 déc. 2018 09:35:14 )
DEBUG    2020-02-17 16:45:11,573 [runtime]:Runtime steam is already up to date (locally updated on mar. 08 janv. 2019 17:53:21 GMT, remote created on sam. 03 nov. 2018 03:11:04 )
DEBUG    2020-02-17 16:45:11,573 [runtime]:Runtime lib64 is already up to date (locally updated on mar. 08 janv. 2019 21:43:53 GMT, remote created on lun. 08 oct. 2018 03:29:56 )
DEBUG    2020-02-17 16:45:11,574 [runtime]:Runtime lib32 is already up to date (locally updated on mar. 08 janv. 2019 17:52:02 GMT, remote created on lun. 08 oct. 2018 03:29:40 )
DEBUG    2020-02-17 16:45:11,575 [api]:Fetching game library
DEBUG    2020-02-17 16:45:11,699 [steam]:Watching Steam folder /home/lenywan/.local/share/Steam/steamapps
DEBUG    2020-02-17 16:45:11,699 [steam]:Watching Steam folder /home/lenywan/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files (x86)/Steam/steamapps
INFO     2020-02-17 16:45:11,787 [lutriswindow]:Setting up view for first run
DEBUG    2020-02-17 16:45:11,788 [lutriswindow]:Syncing 1 icons
DEBUG    2020-02-17 16:45:11,789 [resources]:No icon are missing
INFO     2020-02-17 16:45:15,005 [application]:Shutting down Lutris
INFO     2020-02-17 16:45:15,011 [application]:Shutting down Lutris


```

**Comment by legluondunet** [comment]
Please launch again "lutris -d>lutris log" and install TR2 with Lutris.
Then post log here like you did above.

**Comment by legluondunet** [comment]
@lenywan , could ou post your lutris.log file here?

**Comment by legluondunet** [comment]
Hello @lenywan, is your issue still actual?
If so please follow this steps:

1) launch Lutris, go to "import games" and disconnect from GOG
2) uninstall TR2 from Lutris,
3) launch TR2 install

    if you correctly disconnected GOG in Lutris, Lutris will ask you for the GOG setup file.
    choose english or german setup file

It seems there is a Lutris bug with automatic GOG setup file download.

**Comment by lenywan** [comment]
Sorry for the long time without answer !
I have still the same problem, even if i disconect lutris to gog, and select the executable GOG setup.
From the lutris installer, i have this again "I can't move /home/lenywan/.cache/lutris/installer/tomb-raider-ii/app, it does not exist"
I forgot to say that i bought TR2 in a special pack with TR1 and TR3, but there is a GOG setup file download for each TR so i don't think it's the problem.
I have the same problem with TR3, but with TR 1 it's a bit different, the message error is : "Source does not exist: /home/lenywan/.cache/lutris/installer/tomb-raider-i/app/DATA" but i saw there is already a reported issue on your github. So let's concentrate on TR2 x)

My Lutris version is: lutris (0.5.4)

I speak english because maybe somebody will have the same issue, but we can talk french if you prefer because i'm not very good ^^

Results of commands:
uname -a : Linux lenywan 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
lsb_release -a : No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

Good week ! :)

**Comment by legluondunet** [comment]
Could you update Lutris to a more recent version?

**Comment by legluondunet** [comment]
Please update Lutris to last version or wait your distribution provide you the last version with this issue fixed:

**Comment by lenywan** [comment]
My lutris is already updated to the more recent version !

Thx for all anyways !

**Comment by legluondunet** [comment]
New Lutris version should be available for your distribution.
After updating, you should not be able to reproduce this bug.
