### ISSUE TITLE
Rayman: unable to install game from mounted ISO

### ISSUE THREAD

**Issue by CubeTheThird** [legluondunet/MyLittleLutrisScripts#23]
There appear to be various issues when attempting to install the game from a mounted ISO (using a mounted disc works correctly)

The following is the log obtained:

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/4228572/lutris.log)

Also, these errors appear in the terminal:

```
/usr/lib/python3.8/subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/lib/python3.8/subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
```

There were also issues parsing paths when there were spaces in the name, e.g. /path/to my/disc/

Uname -a: 

Linux arch-desktop 5.5.4-arch1-1 #1 SMP PREEMPT Sat, 15 Feb 2020 00:36:29 +0000 x86_64 GNU/Linux

lsb_release -a:

LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

**Comment by legluondunet** [comment]
Hello,
Rayman original CD is an extra CD, meaning it should have one data and several audio tracks. This CD structure can not be copied in .iso format which stores only data files. For a right image CD extra copy, you have to use the .bin/.cue or .bin/.toc format.
You can use Brasero for this operation or this command line:
`$ cdrdao read-cd --read-raw --datafile "cdname.bin" --driver generic-mmc:0x20000 --device /dev/sr0 "cdname.toc"`
Where /dev/sr0 is your CD device (could be /dev/sr1, /dev/sr2...).
It's not a bug, it's just you use a wrong image CD format for this game.

**Comment by CubeTheThird** [comment]
Gotcha, thanks! I think there is still an issue if the .bin/.cue file has a path with a space in it, but this corrects the problem I had.
