### ISSUE TITLE
Unreal Gold first run critical error "Failed to enter Entry: Can't find file Entry. History: UGameEngine::Init <- InitEngine"

### ISSUE THREAD

**Issue by mucsiistvan** [legluondunet/MyLittleLutrisScripts#24]
I get a critical error window, when trying to start windows version (button1), button2 for linux version doesn't even do anything noticeable (nothing happens).
Description:
"Failed to enter Entry: Can't find file Entry.
History: UGameEngine::Init <- InitEngine"

I use ubuntu mate with MATE desktop environment 1.20.1
uname -a:
Linux zschni-MS-7A33 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
lsb_release -a: 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/4317124/lutris.log)

**Comment by legluondunet** [comment]
Hello @mucsiistvan , thank you for your report.
Actually Lutris suffers from a bug that avoid GOG games to install.
We have to wait until the next version before to investigate yours.
Please tell me when you will obtain the new version on your distribution.

**Comment by legluondunet** [comment]
New Lutris version should be available for your distribution.
After updating, you should not be able to reproduce this bug.
