### ISSUE TITLE
tombraider i gog

### ISSUE THREAD

**Issue by manosmic** [legluondunet/MyLittleLutrisScripts#25]
hello im having a problem with the installation it gives me an error Source does not exist: /home/manosmic/.cache/lutris/installer/tomb-raider-i/app/DATA

uname -a inux laptop 5.3.0-42-generic #34-Ubuntu SMP Fri Feb 28 05:49:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux 
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/4356537/lutris.log)

**Comment by legluondunet** [comment]
Hello @manosmic  , thank you for your report.
Actually Lutris suffers from a bug that avoid GOG games to install https://github.com/lutris/lutris/issues/2638.

I saw in your lutris.log:
```
2020-03-11 09:59:51,574: Adding GOG file download as gog_file_0
2020-03-11 09:59:51,574: Adding GOG file download as gog_file_1
```

We have to wait until the next version before to investigate yours.
Please tell me when you will obtain the new version on your distribution.

**Comment by manosmic** [comment]
yes i will inform you,i manage to install it with the copy file trick that  GruenTentakel say in the other post.i hope for the fix thank you.

**Comment by legluondunet** [comment]
New Lutris version should be available for your distribution.
After updating, you should not be able to reproduce this bug.

**Comment by manosmic** [comment]
the installation works great but i dont have sound / could be the script ???

**Comment by legluondunet** [comment]
Hello Manosmic, do you still haven't sound?
