### ISSUE TITLE
AOE Gold No Music

### ISSUE THREAD

**Issue by linuxhelper** [legluondunet/MyLittleLutrisScripts#26]
Hi. I am unable to get any music to play after installing AOE Gold Edition. I thought it might be related to the upatch installer - so I opted to uninstall and try again w/o the patch. Same issue unfortunately. I had zero issues months ago before the installer was updated running on an older machine - but have since built a new PC. Thanks :)!!

uname -a
Linux The-Adjudicator 5.3.0-42-generic #34-Ubuntu SMP Fri Feb 28 05:49:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/4357491/lutris.log)

**Comment by linuxhelper** [comment]
I think I uploaded an old log file. It was the only one in my home folder.

**Comment by linuxhelper** [comment]
Sorry, here is the output from the terminal.

[Lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/4357519/Lutris.log)

**Comment by legluondunet** [comment]
Hello @linuxhelper , thank you for your report. 
I saw this in your log:

```
Playing cdda://2.
011e:fixme:ntdll:server_ioctl_file Unsupported ioctl 24038 (device=2 access=1 func=e method=0)
Can't open disc.
Failed to open cdda://2.


Exiting... (End of file)
MPlayer sherpya-r38135+gb272d5b9b6-8.3-win32 (C) 2000-2019 MPlayer Team

Playing cdda://3.
0120:fixme:ntdll:server_ioctl_file Unsupported ioctl 24038 (device=2 access=1 func=e method=0)
Can't open disc.
Failed to open cdda://3.


Exiting... (End of file)
MPlayer sherpya-r38135+gb272d5b9b6-8.3-win32 (C) 2000-2019 MPlayer Team

Playing cdda://4.
0122:fixme:ntdll:server_ioctl_file Unsupported ioctl 24038 (device=2 access=1 func=e method=0)
Can't open disc.
Failed to open cdda://4.


Exiting... (End of file)
MPlayer sherpya-r38135+gb272d5b9b6-8.3-win32 (C) 2000-2019 MPlayer Team

Playing cdda://5.
0124:fixme:ntdll:server_ioctl_file Unsupported ioctl 24038 (device=2 access=1 func=e method=0)
Can't open disc.
Failed to open cdda://5.


Exiting... (End of file)
MPlayer sherpya-r38135+gb272d5b9b6-8.3-win32 (C) 2000-2019 MPlayer Team

Playing cdda://6.
0126:fixme:ntdll:server_ioctl_file Unsupported ioctl 24038 (device=2 access=1 func=e method=0)
Can't open disc.
Failed to open cdda://6.


Exiting... (End of file)
MPlayer sherpya-r38135+gb272d5b9b6-8.3-win32 (C) 2000-2019 MPlayer Team

Playing cdda://7.
0128:fixme:ntdll:server_ioctl_file Unsupported ioctl 24038 (device=2 access=1 func=e method=0)
Can't open disc.
Failed to open cdda://7.


Exiting... (End of file)
MPlayer sherpya-r38135+gb272d5b9b6-8.3-win32 (C) 2000-2019 MPlayer Team
```
etc...

It's the moment where MPlayer rip your AOE CD audio tracks.
I have some questions:
1°) do you have the original CD or are you using an image? Other?
2°) What is the original language of your AOE CD?
3°) When you insert AOE CD, could you read audio tracks in your files explorer?

**Comment by linuxhelper** [comment]
1. I am using an original disc from the Collector's Edition (2006). AOE Gold Edition & AOE II/Conqueror's Expansion. CD insert stated versions are AOE 1.0B & ROR 1.0.
2. English.
3. Yes, files in both .mid and .wav formats under AOE/game/sound.

**Comment by legluondunet** [comment]
I don't have tested this version. That the reason why my script is not yet compatible with it.
Only audio misses? That right? The game launched ok and you can play?
Could you list audio files from AOE/game/sound/ and post the result here?
Could you post here the cover of your version?

**Comment by legluondunet** [comment]
Could you type this command in a terminal:

$ find /media/your_profile_name/AOE/ > disque.txt

or wherever your disc is mounted and post the disque.txt here.

**Comment by legluondunet** [comment]
Close as "No answer".
