### ISSUE TITLE
Diablo 1 - 2 different install scripts

### ISSUE THREAD

**Issue by gwaters** [legluondunet/MyLittleLutrisScripts#27]
lutris.log - https://gist.github.com/gwaters/a44db9a3d1ae46fe78eeb6616f4601c3

Linux mycomputer 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

Scripts
Installing Diablo - GOG - Tchernobog
Installing Diablo - GOG + DevilutionX Linux x64 version 

Error:
I can't move /home/user/.cache/lutris/installer/diablo/DIABDAT.MPQ, it does not exist

Issues -
Issue 1: innoextract too old to extract gog file. 
Install scrips fail with the same error below.
Real Issues: 
After updating the innoextract I can extract the GOG file manually but the script does not.  Version used to extract GOG file: https://constexpr.org/innoextract/files/snapshots/innoextract-1.9-dev-2020-01-12/innoextract-1.9-dev-2020-01-12-linux.tar.xz

Lutris script issue: N/A: Please select file etc etc - doesnt prompt the user! So I  think that is why innnoextract is failing 

Cancel installation issue: "unchecking Remove game files" still deletes the entire install directory lol.

**Comment by legluondunet** [comment]
Hello @gwaters,
thank you for your report.
Please follow this steps:

1°) Download Diablo setup file directly from GOG site.
2°) launch Lutris, go to "import games" and disconnect from GOG
3°) try again to install Diablo (Tchernobog or DevilutionX script). If a window ask you for GOG credentials, just press escape to close it. Then Lutris will ask you for location where you stored  the Diablo GOG setup file.

Do you obtain, by this way, a different result?

**Comment by gwaters** [comment]
3. Sorry I have been trying to get this work for a few hours probably ran the install 20 times, and I finally got it installed by skipping the innoextract. The script works after the innoextract just fine. Note, GOG gives 2 files gog_download_0/download, gog_download_1/download. download_1 is the actual compressed file, download_0 is a list I think. 

What I did to install it was this. During a failed install, and before it autoremoves the install directory, I innoextracted the GOG file, and and tar'd up the results and moved it out of the install directory.
Then I went back to install the game again. This time, I copied in the tar file while its downloading the GOG files again. I extracted the tar ball where the innoextract would have extracted the file and the rest script works just fine and its finally installed. Hope this all helps.

-Gary

**Comment by legluondunet** [comment]
I can not reproduce your bug but I have a more recent Lutris version than yours.

Actually 0.5.4 Lutris suffers from a bug that avoid GOG games to install correctly lutris/lutris#2638.

this lines in lutris.log:

2020-03-11 09:59:51,574: Adding GOG file download as gog_file_0
2020-03-11 09:59:51,574: Adding GOG file download as gog_file_1

are not normal.

We have to wait until the next version.
Please tell me when you will obtain the new version on your distribution.

**Comment by gwaters** [comment]
Bah, lucky. Oh well, but at least we can update the innoextract. Thanks legluondunet!
