### ISSUE TITLE
ScummVM doesn't recognize `riven-en`

### ISSUE THREAD

**Issue by AndrewKvalheim** [legluondunet/MyLittleLutrisScripts#31]
After installing Riven in Lutris 0.5.5, ScummVM 2.1.0 failed to launch with:

    scummvm: Unrecognized game target 'riven-en'

Changing the game identifier to just `riven` seems to have resolved it.

**Comment by legluondunet** [comment]
Hello @AndrewKvalheim , thank you for your report. I will inspect that issue.

**Comment by legluondunet** [comment]
just fixed!

**Comment by legluondunet** [comment]
nota: 
Finally a duplicate of #34
