### ISSUE TITLE
The Secret of Monkey Island - Special Edition - GOG - Wine

### ISSUE THREAD

**Issue by TheAndrewSAMA** [legluondunet/MyLittleLutrisScripts#32]
After clicking "Play", the screen turns black, then white and then the game crashes.
Here the requested infos:

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/4459452/lutris.log)

Linux sammy-archer 5.5.16-1-ck-skylake #1 SMP PREEMPT Wed, 08 Apr 2020 17:02:29 +0000 x86_64 GNU/Linux

LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

The same thing is happening with Monkey Island 2 - Special Edition - LeChuck’s Revenge - GOG - Wine

Thanks :)

**Comment by legluondunet** [comment]
Hello @TheAndrewSAMA, thank you for your report.
I can reproduce your issue with Lutris WIne >= 5.4.
Solution: change Lutris Wine version to a version <= 5.2.
I modified my script installer to use Lutris Wine version 5.0 until this regression will be fixed in future Lutris Wine version.

**Comment by TheAndrewSAMA** [comment]
I can confirm that now it's working. Thank you!

**Comment by legluondunet** [comment]
does not work with Lutris Wine >5.2 or <= Lutris WIne 5.7
I tried with last wine-staging 5.7: it works
