### ISSUE TITLE
Twitch App - gets stuck on dotnet installation

### ISSUE THREAD

**Issue by mpumalanga** [legluondunet/MyLittleLutrisScripts#33]
Installation repeatedly got stuck whilst installing DotNet 4.8 sp1. Waited long enough to see the same timeout message a lot. Didn't change any properties when prompted for installation, just clicked install. Lutris Log appended. 

003d:err:ntdll:RtlpWaitForCriticalSection section 0x100a8 "/home/ubuntu/buildbot/runners/wine/wine-src/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 003d, blocked by 01cb, retrying (60 sec)
[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/4523577/lutris.log)

    uname -a
Linux XXX 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

    lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

Thx alot!

**Comment by legluondunet** [comment]
Hello, dotnet could take very long time to install, depends your computer hardware config it could take 10, 20 or even 30 mn.
Other thing: it could happen dotnet does not finished installing correctly.
In this case you can try to kill manually the wine processes:
`killall -9 explorer.exe services.exe plugplay.exe mscorsvw.exe winedevice.exe regedit.exe`
and then launch this command:
`ps aux |grep .exe`
to see if some wine processes staying active.

**Comment by legluondunet** [comment]
I just updated my script and it now uses Dotnet 4.6, tell me if it changes something for you. You will need to fully uninstall and reinstall Twitch from Lutris.

**Comment by legluondunet** [comment]
Added this to description:
Known issue: if Dotnet 4.8 never ending install, open a terminal and execute this command:
killall -9 explorer.exe services.exe plugplay.exe mscorsvw.exe winedevice.exe regedit.exe
If Dotnet did not install correctly, you can reinstall it later using Winetricks.

**Comment by mpumalanga** [comment]
Thanks! Your exe kill workaround worked for me. I had to kill some more exe processes but then installatoin finished and twitch is usable again!
