### ISSUE TITLE
Warcraft III PTR

### ISSUE THREAD

**Issue by KoryMac** [legluondunet/MyLittleLutrisScripts#35]
I think you've perhaps overlooked a naming discrepancy in your Warcraft III PTR installer. Lutris is giving me a 404 because it's looking for a file called "warcraftiii_utf8.reg", but I notice that you have a very similarly named file in your repository presently named "warcraft_iii_ptr_utf8.reg". I have a hunch that the installer would work fine as I have heard other people saying that it does if this were corrected. I'm going to try substituting out the names here on my end, and see if I can get this game going. Regardless, thank you for your effort in trying to help us linux users have access to oldschool wc3.

**Comment by legluondunet** [comment]
Hello, I updated Warcraft III PTR Lutris script installer recently, that's why you couldn't use it the last 24 hours.
I just finished, tell me if it works as expected. Me too I prefer to play oldschool wc3, that's why I wrote this script. And soon I will write a script for CD version. Have fun ;)
