### ISSUE TITLE
Tomb Raider I Lutris script broken?

### ISSUE THREAD

**Issue by DoomRaid** [legluondunet/MyLittleLutrisScripts#36]
I install Tomb Raider 1 on steam as instructed, downloading the files goes fine, then it needs GAME.GOG. It's not possible to mount? I see it in the folder, but don't know what to do with it. Tried copying folder to documents and browsing, sometimes installer starts but is stuck forever extracting the first thing. 

Arch Linux, Gtx 1080, i7-8700k, 16 GB RAM, 500 GB NVMe SSD.

**Comment by legluondunet** [comment]
Hello @DoomRaid,
I just tested my scritpt and I can not reproduce your issue.
Could you start Lutris in a terminal with this command:
`lutris -d>lutris.log`
then launch again "Tomb Raider I" Steam Lutris script installer
and once finished, post the lutris.log file here.
Do you use the last Lutris version?

**Comment by DoomRaid** [comment]
Hi. I have been messing around with it all day. I ended up adding the game to Lutris and now all of a sudden it finds and runs no problem, but I haven't needed to do so before now. Now that I got it working I'd rather just leave it at that because it was quite frustrating. Thanks for your time. :)

**Comment by legluondunet** [comment]
nota: could be related to issue https://github.com/lutris/lutris/issues/2809
