### ISSUE TITLE
Theme Hospital Ubuntu 20.04 with Corsix does not find the game's data files

### ISSUE THREAD

**Issue by rsf92** [legluondunet/MyLittleLutrisScripts#39]
After running the installer I ls the folder ~/Games/theme-hospital and get this
Corsix-TH  corsix-th.desktop  corsix-th.sh  TH  Wildmidi

I assume that the game's files should be on TH, right? But that folder is empty... as you can see on the image below

![imagen](https://user-images.githubusercontent.com/33062572/84547423-d0559c00-ad03-11ea-9c9e-a1c7ab01433a.png)

Am I missing something or is there any problem with the installer?

**Comment by legluondunet** [comment]
Hello @rsf92,
I just tested my script and I can not reproduce your issue.
Did you use the last install file version available on your GOG account?
Did you download the install file in another language than english?

**Comment by rsf92** [comment]
HI, sorry, it was my bad, i thougth the script automatically downloaded the exe file from gog, as happens with other gog games i have.

I'll close the issue, my apologies
