### ISSUE TITLE
age of empires gold edition install stuck

### ISSUE THREAD

**Issue by jolitp** [legluondunet/MyLittleLutrisScripts#4]
installer is stuck with message:
Source does not exist: /media/jolitp/AOE/game/AVI

only choices are cancel and eject

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/3684548/lutris.log)

**Comment by legluondunet** [comment]
Hello @jolitp, thank you for your report, could you mount your "AOE Gold" CD, open a terminal and type this command:
lstree /path_to_your_mounted_cd/ > AOElstree.log
then post the "AOElstree.log" file here.

**Comment by jolitp** [comment]
I don't have lstree in my system, even after installing "tree" did it with tree instead

[AOElstree.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/3688560/AOElstree.log)

**Comment by legluondunet** [comment]
I modified my installer to be less case sensitive.
Could you try again ["AOE Gold edition" installer](https://lutris.net/games/age-of-empires/):
1°) launch lutris in debug mode:
`lutris -d>lutris.log`
2°) launch AOE Gold edition installer and post the "lutris.log" file here.

Thanks.

**Comment by legluondunet** [comment]
@jolitp could I close this issue?

**Comment by jolitp** [comment]
yes it installs now, but when launching the game it shows a black screen and the windows taskbar below and then it closes.

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/3720078/lutris.log)
this is the log of me trying to open the game

**Comment by legluondunet** [comment]
I need more info about your configuration:

```
uname -a

lsb_release -a
```

then could you try this:
1°) launch lutris in debug mode:
lutris -d>lutris.log
2°) delete and reinstall the game
3°) right click on the game, configure, runner options tab, choose a more recent Wine version <4.16 (not 4.16) and in the same tab set "output debugging info" to "enable".
4°) launch the game and when it will exit, close Lutris and join the log file.

**Comment by jolitp** [comment]
$ uname -a
Linux ryzen-mint 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.2 Tina
Release:	19.2
Codename:	tina

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/3735573/lutris.log)

**Comment by legluondunet** [comment]
Hello @jolitp , I recently updated my AOE installer.
Could you give it a test?

**Comment by jolitp** [comment]
we are getting somewhere, the installer changed this time, now it's manual.
the game was installed on lutris.
but now I get a cmd prompt asking me to choose the version, however I can't input anything.

![Screenshot from 2019-10-23 14-01-13](https://user-images.githubusercontent.com/8359524/67310649-8d288d80-f4d4-11e9-9b68-7c8c9ade5d9a.png)

**Comment by legluondunet** [comment]
the cmd promptwindow does not have the focus per default, so click on it and choose an option.

**Comment by jolitp** [comment]
Yes that did the trick, however to select the window it needs to be from the tittle bar for it to work.

you can close this now.

**Comment by jolitp** [comment]
thank you very much
