### ISSUE TITLE
Warcraft III The Frozen Throne no longer installs

### ISSUE THREAD

**Issue by WandeingLagomorph793** [legluondunet/MyLittleLutrisScripts#40]
If I run the Reign of Chaos script, that runs fine. But Frozen Throne does not.

It does not pop up the CD key entry screen, it just skips that and goes to the select language, then it won't install TFT, it loads ROC after but not TFT, checking the prefix directory shows it didn't even install.

**Comment by legluondunet** [comment]
Hello,
what is your CD version/language?
could you type this command in a terminal:
`$ find /media/your_profile_name/TheFrozenThrone/ `

and copy the command result here.
For me:
```
$ find /media/legluondunet/TheFrozenThrone/
/media/legluondunet/TheFrozenThrone/
/media/legluondunet/TheFrozenThrone/Installer Tome.mpq
/media/legluondunet/TheFrozenThrone/Installer.exe
/media/legluondunet/TheFrozenThrone/autorun.inf
/media/legluondunet/TheFrozenThrone/war3tft.ico
```

**Comment by WandeingLagomorph793** [comment]
It is the initial unpatched CD copy, in english, I tried it both mounted and extracted it's contents but none of those worked. Everything worked for Reign of Chaos but Frozen Throne says "Invalid Runner", only fix I had was a previous install on another system and transferring TFTs contents.

**Comment by legluondunet** [comment]
I can't help you without debug info and logs.

**Comment by legluondunet** [comment]
I tested all this scripts install again (chaos + frozen) and I can not reproduce your issue.
If you don't send me debug logs and info, I will close this issue.

**Comment by WandeingLagomorph793** [comment]
/run/media/chao/CDROM
/run/media/chao/CDROM/autoplay.exe
/run/media/chao/CDROM/autorun.inf
/run/media/chao/CDROM/directx
/run/media/chao/CDROM/directx/dsetup.dll
/run/media/chao/CDROM/directx/dsetup32.dll
/run/media/chao/CDROM/install.exe
/run/media/chao/CDROM/setup.mpq
/run/media/chao/CDROM/support
/run/media/chao/CDROM/support/battlene
/run/media/chao/CDROM/support/battlene/chathelp.htm
/run/media/chao/CDROM/support/battlene/clanhelp.htm
/run/media/chao/CDROM/support/battlene/_mac_000.htm
/run/media/chao/CDROM/support/battlene/_mac_bne.htm
/run/media/chao/CDROM/support/battlene/_pc_b000.htm
/run/media/chao/CDROM/support/battlene/_pc_bnet.htm
/run/media/chao/CDROM/support/images
/run/media/chao/CDROM/support/images/blizz.jpg
/run/media/chao/CDROM/support/images/blwidget.jpg
/run/media/chao/CDROM/support/images/bnet.jpg
/run/media/chao/CDROM/support/images/brepeat.jpg
/run/media/chao/CDROM/support/images/brwidget.jpg
/run/media/chao/CDROM/support/images/bspacer.jpg
/run/media/chao/CDROM/support/images/bwidget.jpg
/run/media/chao/CDROM/support/images/clanicon
/run/media/chao/CDROM/support/images/clanicon/initiate.jpg
/run/media/chao/CDROM/support/images/clanicon/leader.jpg
/run/media/chao/CDROM/support/images/clanicon/member.jpg
/run/media/chao/CDROM/support/images/clanicon/officer.jpg
/run/media/chao/CDROM/support/images/crepeat.jpg
/run/media/chao/CDROM/support/images/itemmark.jpg
/run/media/chao/CDROM/support/images/logo.jpg
/run/media/chao/CDROM/support/images/lrepeat.jpg
/run/media/chao/CDROM/support/images/maclogo.jpg
/run/media/chao/CDROM/support/images/nav
/run/media/chao/CDROM/support/images/nav/nav_00.jpg
/run/media/chao/CDROM/support/images/nav/nav_01.jpg
/run/media/chao/CDROM/support/images/nav/nav_02.jpg
/run/media/chao/CDROM/support/images/nav/nav_03.jpg
/run/media/chao/CDROM/support/images/nav/nav_04.jpg
/run/media/chao/CDROM/support/images/nav/nav_05.jpg
/run/media/chao/CDROM/support/images/nav/nav_10.jpg
/run/media/chao/CDROM/support/images/nav/nav_11.jpg
/run/media/chao/CDROM/support/images/nav/nav_12.jpg
/run/media/chao/CDROM/support/images/nav/nav_13.jpg
/run/media/chao/CDROM/support/images/nav/nav_14.jpg
/run/media/chao/CDROM/support/images/nav/nav_15.jpg
/run/media/chao/CDROM/support/images/nav/nav_20.jpg
/run/media/chao/CDROM/support/images/nav/nav_21.jpg
/run/media/chao/CDROM/support/images/nav/nav_22.jpg
/run/media/chao/CDROM/support/images/nav/nav_23.jpg
/run/media/chao/CDROM/support/images/nav/nav_24.jpg
/run/media/chao/CDROM/support/images/nav/nav_25.jpg
/run/media/chao/CDROM/support/images/nav/nav_30.jpg
/run/media/chao/CDROM/support/images/nav/nav_31.jpg
/run/media/chao/CDROM/support/images/nav/nav_32.jpg
/run/media/chao/CDROM/support/images/nav/nav_33.jpg
/run/media/chao/CDROM/support/images/nav/nav_34.jpg
/run/media/chao/CDROM/support/images/nav/nav_35.jpg
/run/media/chao/CDROM/support/images/nav/nav_40.jpg
/run/media/chao/CDROM/support/images/nav/nav_41.jpg
/run/media/chao/CDROM/support/images/nav/nav_42.jpg
/run/media/chao/CDROM/support/images/nav/nav_43.jpg
/run/media/chao/CDROM/support/images/nav/nav_44.jpg
/run/media/chao/CDROM/support/images/nav/nav_45.jpg
/run/media/chao/CDROM/support/images/nav/nav_50.jpg
/run/media/chao/CDROM/support/images/nav/nav_51.jpg
/run/media/chao/CDROM/support/images/nav/nav_52.jpg
/run/media/chao/CDROM/support/images/nav/nav_53.jpg
/run/media/chao/CDROM/support/images/nav/nav_54.jpg
/run/media/chao/CDROM/support/images/nav/nav_55.jpg
/run/media/chao/CDROM/support/images/rrepeat.jpg
/run/media/chao/CDROM/support/images/splash.jpg
/run/media/chao/CDROM/support/images/tlwidget.jpg
/run/media/chao/CDROM/support/images/trepeat.jpg
/run/media/chao/CDROM/support/images/trwidget.jpg
/run/media/chao/CDROM/support/images/twidget.jpg
/run/media/chao/CDROM/support/images/winlogo.jpg
/run/media/chao/CDROM/support/layout
/run/media/chao/CDROM/support/layout/cspacer.htm
/run/media/chao/CDROM/support/layout/detector.js
/run/media/chao/CDROM/support/layout/splash.htm
/run/media/chao/CDROM/support/layout/styles.css
/run/media/chao/CDROM/support/layout/thescrip.js
/run/media/chao/CDROM/support/layout/worldedi.htm
/run/media/chao/CDROM/support/layout/_mac_000.htm
/run/media/chao/CDROM/support/layout/_mac_bsp.htm
/run/media/chao/CDROM/support/layout/_mac_ind.htm
/run/media/chao/CDROM/support/layout/_mac_lbo.htm
/run/media/chao/CDROM/support/layout/_mac_nav.htm
/run/media/chao/CDROM/support/layout/_mac_rbo.htm
/run/media/chao/CDROM/support/layout/_mac_tbo.htm
/run/media/chao/CDROM/support/layout/_mac_weh.htm
/run/media/chao/CDROM/support/layout/_pc_bspa.htm
/run/media/chao/CDROM/support/layout/_pc_inde.htm
/run/media/chao/CDROM/support/layout/_pc_lbor.htm
/run/media/chao/CDROM/support/layout/_pc_nav.htm
/run/media/chao/CDROM/support/layout/_pc_rbor.htm
/run/media/chao/CDROM/support/layout/_pc_tbor.htm
/run/media/chao/CDROM/support/layout/_pc_wehi.htm
/run/media/chao/CDROM/support/layout/_pc_weht.htm
/run/media/chao/CDROM/support/layout/_weh_nav.htm
/run/media/chao/CDROM/support/readme
/run/media/chao/CDROM/support/readme/bntou.htm
/run/media/chao/CDROM/support/readme/contact.htm
/run/media/chao/CDROM/support/readme/eula.htm
/run/media/chao/CDROM/support/readme/games.htm
/run/media/chao/CDROM/support/readme/_mac_add.htm
/run/media/chao/CDROM/support/readme/_mac_for.htm
/run/media/chao/CDROM/support/readme/_mac_ing.htm
/run/media/chao/CDROM/support/readme/_mac_pat.htm
/run/media/chao/CDROM/support/readme/_mac_rea.htm
/run/media/chao/CDROM/support/readme/_mac_sta.htm
/run/media/chao/CDROM/support/readme/_mac_uim.htm
/run/media/chao/CDROM/support/readme/_pc_adde.htm
/run/media/chao/CDROM/support/readme/_pc_fore.htm
/run/media/chao/CDROM/support/readme/_pc_inga.htm
/run/media/chao/CDROM/support/readme/_pc_patc.htm
/run/media/chao/CDROM/support/readme/_pc_read.htm
/run/media/chao/CDROM/support/readme/_pc_star.htm
/run/media/chao/CDROM/support/readme/_pc_uima.htm
/run/media/chao/CDROM/support/readme.htm
/run/media/chao/CDROM/support/support
/run/media/chao/CDROM/support/support/_mac_ins.htm
/run/media/chao/CDROM/support/support/_mac_lan.htm
/run/media/chao/CDROM/support/support/_mac_loc.htm
/run/media/chao/CDROM/support/support/_mac_pat.htm
/run/media/chao/CDROM/support/support/_mac_sup.htm
/run/media/chao/CDROM/support/support/_pc_inst.htm
/run/media/chao/CDROM/support/support/_pc_lan.htm
/run/media/chao/CDROM/support/support/_pc_lock.htm
/run/media/chao/CDROM/support/support/_pc_patc.htm
/run/media/chao/CDROM/support/support/_pc_supp.htm
/run/media/chao/CDROM/support/worldedi
/run/media/chao/CDROM/support/worldedi/aieditor.htm
/run/media/chao/CDROM/support/worldedi/campaign.htm
/run/media/chao/CDROM/support/worldedi/creation.htm
/run/media/chao/CDROM/support/worldedi/features.htm
/run/media/chao/CDROM/support/worldedi/importma.htm
/run/media/chao/CDROM/support/worldedi/intro.htm
/run/media/chao/CDROM/support/worldedi/location.htm
/run/media/chao/CDROM/support/worldedi/menus.htm
/run/media/chao/CDROM/support/worldedi/objected.htm
/run/media/chao/CDROM/support/worldedi/objectma.htm
/run/media/chao/CDROM/support/worldedi/soundedi.htm
/run/media/chao/CDROM/support/worldedi/terraine.htm
/run/media/chao/CDROM/support/worldedi/triggere.htm
/run/media/chao/CDROM/support/worldedi/unitedit.htm
/run/media/chao/CDROM/support/worldedi/worldedi.htm
/run/media/chao/CDROM/support/worldedi/_mac_wor.htm
/run/media/chao/CDROM/support/worldedi/_pc_worl.htm
/run/media/chao/CDROM/support/worldedi/_weh_wor.htm
/run/media/chao/CDROM/trailers
/run/media/chao/CDROM/trailers/ghost.blz
/run/media/chao/CDROM/trailers/wowgamep.blz
/run/media/chao/CDROM/war3tft.ico

Contents of the log file when I check it (Had weird drive issues so sorry for the time gap)

**Comment by legluondunet** [comment]
My script search for installer.exe file and your CD has install.exe.
I published a new script called "CD_install + patch 1.27b + WS version", could you test it please?
For a better test result, please reinstall the game from scratch.

**Comment by WandeingLagomorph793** [comment]
> My script execute installer.exe file and your CD has install.exe.
> I published a new script called "CD_install + patch 1.27b + WS version", could you test it please?
> For a better test result, please reinstall the game from scratch.

Just got back from some drive management, but yeah I'll give it a shot.

**Comment by legluondunet** [comment]
Should be fixed now.
