### ISSUE TITLE
Dragon Age Origins - DLC not installed

### ISSUE THREAD

**Issue by DocKDE** [legluondunet/MyLittleLutrisScripts#41]
Hi there,
I used the install script via Lutris and the game runs fine, however it appears not to have installed all the DLCs and the Addon, so it's effectively not the ultimate edition. I read that as a workaround I could obtain files from a Windows installation which is unfortunately not possible for me. I'd really like some help on this!

**Comment by legluondunet** [comment]
Hello @DocKDE, thank you for your report, I 'm working on it.

**Comment by legluondunet** [comment]
I just updated the script, could you try it and tell me if your issue is resolved.

**Comment by DocKDE** [comment]
Tried it again and works perfectly. All DLCs installed. Thanks a lot for the quick fix!
