### ISSUE TITLE
Dragon Age Origins DLC not integrated properly

### ISSUE THREAD

**Issue by DocKDE** [legluondunet/MyLittleLutrisScripts#42]
Hello there,
I reported a few days ago that the DLCs for DAO were not installed correctly and it was fixed (thanks again) quickly. However, after a few hours into the game I realized that the story DLCs are not properly integrated, especially "Prisoner of Stone", "Warden's Keep" and "Return to Ostagar". In the main menu they are displayed as downloaded and enabled but they do not activate in the game when they should. 
It seems this issue has been reported with the Origin version for Windows as well and fixes using the DAO Updater service have been proposed (see here: https://answers.ea.com/t5/Dragon-Age-Origins/SOLUTIONS-UNAUTHORIZED-DLC-or-MISSING-DLC/m-p/470470/highlight/true#M1204).
Could this possibly be fixed?

Best!

**Comment by legluondunet** [comment]
Hello,
thank you again for this report, as described in your link, could try to execute this file:
DAUServiceSetup.exe ?
And tell me if it resolved this issue?

**Comment by legluondunet** [comment]
Should be fixed now.
