### ISSUE TITLE
Unable the run the installer

### ISSUE THREAD

**Issue by lsalamoun** [legluondunet/MyLittleLutrisScripts#44]
Hello,
I am sorry if this is a trivial thing. I am just new to Linux systems. I am running Fedora 32.

I have ran your script but got the 404 client error: NOt found url: https://github.com/legluondunet/MyLittleLutrisScripts/raw/master/Warcraft%20III/warcraft_iii.bmp

when started the installation on:
https://lutris.net/games/warcraft-iii-reforged/

What I did:
ThinkPad X1 Carbon 6th
Intel® Core™ i7-8650U CPU @ 1.90GHz × 8
Mesa Intel® UHD Graphics 620 (KBL GT2)

- I did installed wine (v5.12)
- I did installed Lutris
- I did run sudo dnf install vulkan-loader vulkan-loader.i686

- I couldn't run:
gnutls gnutls-devel openldap openldap-devel libgpg-error sqlite2.i686 sqlite2.x86_64
(command not found)

I started to run commands by this video:
https://www.youtube.com/watch?v=X6Vk_J3p2KA&feature=youtu.be

But when the guy got to git checkout async:
error: pathspec 'async' did not match any file(s) known to git

I tried to to run:
dxvk]$ ./package-release.sh master/home/cxf/.local/share/lutris/runtime/dxvk --no-package

realpath: unrecognized option '--no-package'

Not sure what to do now since I have ran out of tutorials :D

Any advice?

thanks

**Comment by legluondunet** [comment]
Hello @lsalamoun,
thank you for your report.
I just updated the script, your issue should be fixed now.
