### ISSUE TITLE
[Dragon Age Origins GOG] install fail : I can't move /drive_c/GOG Games/game, it does not exist

### ISSUE THREAD

**Issue by GP-S** [legluondunet/MyLittleLutrisScripts#45]
Hello, 

On archlinux, I can't install DAO. Seems like executable game file/folder is not generated ?

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/5045453/lutris.log)

Linux Pushan 5.7.12-arch1-1 #1 SMP PREEMPT Fri, 31 Jul 2020 17:38:22 +0000 x86_64 GNU/Linux

LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

**Comment by legluondunet** [comment]
Hello @GP-S,
thank you for your report.
I found something wrong in your log that can cause your issue:
```
lutris/installer/dragon-age-origins-ultimate-edition/innoextract -g -d /home/thibault/Games/dragon-age-origins-ultimate-edition/drive_c/GOG Games/ /home/thibault/Téléchargements/GOG_Galaxy_Dragon_AgeTM_Origins_-_Ultimate_Edition.exe
Running /home/thibault/.cache/lutris/installer/dragon-age-origins-ultimate-edition/innoextract -g -d /home/thibault/Games/dragon-age-origins-ultimate-edition/drive_c/GOG Games/ /home/thibault/Téléchargements/GOG_Galaxy_Dragon_AgeTM_Origins_-_Ultimate_Edition.exe
Initial process has started with pid 29076
Game is considered started.
Not a supported Inno Setup installer!
Done with 1 error.
```
"GOG_Galaxy_Dragon_AgeTM_Origins_-_Ultimate_Edition.exe" is not the correct needed file.
You need to download the file called "Bonus DLC + hotfix" on your GOG page account:
![Capture-20200808233210-764x533](https://user-images.githubusercontent.com/325405/89720146-7d305a80-d9cf-11ea-9efe-6dae46cef95e.png)

**Comment by GP-S** [comment]
Both are needed, when you don't connect to gog, the installer ask for install file which I supposeed to be GOG_Galaxy_Dragon_AgeTM_Origins_-_Ultimate_Edition.exe
Anyway I tried again with gog connected and got the error

**Comment by GP-S** [comment]
here the logs
[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/5048294/lutris.log)

**Comment by GP-S** [comment]
@legluondunet here the logs if you want to check 
[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/5048296/lutris.log)

**Comment by legluondunet** [comment]
I found this error in your log:
```
Could not extract "/home/thibault/.cache/lutris/installer/dragon-age-origins-ultimate-edition/gog/setup_dragon_age_origins_ultimate_2.1.0.4-1.bin": install `unrar` or `unar`
Done with 1 error.
Game is considered exited.
```
You should provide patch_dragon_age_origins_ultimate_2.1.1.5.exe file, not setup_dragon_age_origins_ultimate_2.1.0.4-1.bin.

**Comment by GP-S** [comment]
Which is what I did. "setup_dragon_age_origins_ultimate_2.1.0.4-1.bin" is one of the first file downloaded by lutris and stored in ".cache".

**Comment by legluondunet** [comment]
Perhaps a corrupt archive file, you should try to erase it and download it again.

**Comment by legluondunet** [comment]
I could finally reproduce this issue on a new computer:
```
Could not extract "/home/thibault/.cache/lutris/installer/dragon-age-origins-ultimate-edition/gog/setup_dragon_age_origins_ultimate_2.1.0.4-1.bin": install `unrar` or `unar`
Done with 1 error.
Game is considered exited.
```
I updated the script, could you try to install it again and tell me if it resolved your issue.

**Comment by legluondunet** [comment]
should be fixed now:
- use standard GOG installer instead innoextract.

**Comment by GP-S** [comment]
> I could finally reproduce this issue on a new computer:
> 
> ```
> Could not extract "/home/thibault/.cache/lutris/installer/dragon-age-origins-ultimate-edition/gog/setup_dragon_age_origins_ultimate_2.1.0.4-1.bin": install `unrar` or `unar`
> Done with 1 error.
> Game is considered exited.
> ```
> 
> I updated the script, could you try to install it again and tell me if it resolved your issue.

Worked like a charm ! Thanks for the fix !
