### ISSUE TITLE
[GOG][ResidualVM] The Longest Journey 

### ISSUE THREAD

**Issue by AlexanderRavenheart** [legluondunet/MyLittleLutrisScripts#46]
Installer fails to download https://www.dropbox.com/s/h2mfqt8bw7xygt2/tlj_4cd_gog_menus_sub_multi5.zip?dl=1. (404 Error)
Installer url: https://lutris.net/games/install/13883/view

**Comment by legluondunet** [comment]
Should be fixed:
- Dropbox link is again available, just blocked momentary for going over a download quota
- script could no more unarchive GOG TLP setup files: replaced innoextract 1.8 by 1.9, GOG surely updated his setup packages.
