### ISSUE TITLE
(Request) Silent Hill 3 and 4 PC with steam006 mods

### ISSUE THREAD

**Issue by Hunk4TH** [legluondunet/MyLittleLutrisScripts#47]
Hey, 

I apologize if you aren't taking requests but if you are would it be possible to make a script for these two games with the mods from Steam006 https://community.pcgamingwiki.com/files/file/1331-silent-hill-3-pc-fix-by-steam006 ?

**Comment by legluondunet** [comment]
hello, 

I'm sorry @Hunk4TH  I don't write Lutris installer scripts for game I don't own, I own only Silent Hill 2.
