### ISSUE TITLE
RollerCoaster Tycoon 2: Wrong download URL for OpenRCT2

### ISSUE THREAD

**Issue by koelle25** [legluondunet/MyLittleLutrisScripts#48]
The install scripts tries to download `https://github.com/OpenRCT2/OpenRCT2/releases/download/v0.3.1/OpenRCT2-0.3.1-linux-x86_64.gz`.

But it should be `https://github.com/OpenRCT2/OpenRCT2/releases/download/v0.3.1/OpenRCT2-0.3.1-linux-x86_64.tar.gz` (note the **.tar**.gz at the end).

I will post a PR fixing this.

**Comment by legluondunet** [comment]
Thank you for your report, fixed.
