### ISSUE TITLE
Xbox 360 triggers not recognized by the game Silent Hill 2 Enhanced Edition

### ISSUE THREAD

**Issue by GaussLeibniz** [legluondunet/MyLittleLutrisScripts#51]
So i wanted to assign the controls to my controller (Xbox 360 wireless controller), but LT RT are not recognized in Silent Hill 2 Enhanced Edition
every other button is recognized. If you got any idea, please let me know.

OS: Pop_OS 20.04
Kernel: 5.4.0-7642-generic

**Comment by legluondunet** [comment]
Hello, I see only two choices here: use defaults controls assigned (do not change anything).
Or use a keymapper like antimicro.
