### ISSUE TITLE
alone in the dark *: Could not open file "$setup"

### ISSUE THREAD

**Issue by dahabakuk** [legluondunet/MyLittleLutrisScripts#52]
hi,

im not able to use alone in the dark installer (1,2,3):

eg. alone in the dark 1:

2020-10-27 11:00:13,529: Getting game details for 1207660923
2020-10-27 11:00:13,623: Getting download info for [snip]
2020-10-27 11:00:13,768: Adding [snip]
2020-10-27 11:00:13,769: Adding [snip]
2020-10-27 11:00:13,769: Downloading file 1 of 4
2020-10-27 11:00:14,273: Downloading file 2 of 4
2020-10-27 11:00:14,778: Downloading file 3 of 4
2020-10-27 11:00:15,281: Downloading file 4 of 4
Running /home/user/.cache/lutris/installer/alone-in-the-dark-1/innoextract -d /home/user/opt/lutris/alone-in-the-dark-1 $setup
Could not open file "$setup"
Done with 1 error.
Waiting on children
Exit with returncode 2

any idea whats the issue is here or how to debug this further?

thanks

**Comment by legluondunet** [comment]
Hello @dahabakuk, thank you for your report.
I just tested alone in the dark 1 installed, everything ok, I can not reproduce your issue.
Do you manually downloaded game setup file from GOG? 
Could you try again to install AITD1 this way:
open a terminal
launch this command: lutris -d>lutris.log
try to install the game and then close Lutris and join here the lutris.log file.

**Comment by dahabakuk** [comment]
hi @legluondunet,
thanks for your fast reply - no i did not manually download anything.
just used lutris to download and install it.

see the attached lutris.log
[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/5447723/lutris.log)

**Comment by legluondunet** [comment]
What is your distribution name? version?
I saw in the log you are using Lutris 0.5.2.1 version, it's too old, you have to update it first.

**Comment by dahabakuk** [comment]
debian buster... i configured the repo like on lutris.net and updated it
installed libopusfile0 which doesnt seem to be a dependency
and now i got aitd2+3 working
for 1 i get an exception:

 

>Traceback (most recent call last):                    
 > File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 136, in on_scripts_obtained
  >  self.choose_installer()                               
  >File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 189, in choose_installer
  >  installer_picker = InstallerPicker(self.scripts)  
  >File "/usr/lib/python3/dist-packages/lutris/gui/widgets/installer.py", line 118, in __init__
   > self.add(InstallerScriptBox(script, parent=self, revealed=revealed))
  >File "/usr/lib/python3/dist-packages/lutris/gui/widgets/installer.py", line 35, in __init__
   > box.add(self.get_icon())                       
 > File "/usr/lib/python3/dist-packages/lutris/gui/widgets/installer.py", line 72, in get_icon
 >   icon.set_margin_left(6)                            
>AttributeError: 'NoneType' object has no attribute 'set_margin_left'


seems to be a missing icon:
> ERROR    2020-10-27 22:14:02,763 [utils.get_icon:91]:Unable to find icon '/usr/share/lutris/media/runner_icons/mess.png'

after copying any other png to mess.png it works as expected for aitd1 ... weird! will look into this later on...

thanks for your help and hint for updating lutris! much appreciated.
