### ISSUE TITLE
Moto Racer 1 does not start

### ISSUE THREAD

**Issue by abda11ah** [legluondunet/MyLittleLutrisScripts#53]
Hi,

I installed Moto Racer GOG version.

This file  

**please do not use or post piracy game link**

It does not works, it opens a black window that closes quickly after some seconds.

I tried to launch Moto.EXE (without dxwnd) inside a Xephyr 16bit window. It worked so i think you need to update your script.

But when i want to start a quick race in D3D mode i get a message (Not enough video memory)

**Comment by legluondunet** [comment]
Hello,
please use only official GOG setup file.

**Comment by abda11ah** [comment]
It is the same file as from GOG

**Comment by legluondunet** [comment]
I modified script, I found a bug that could cause your crash. Try again, it could work now.

**Comment by abda11ah** [comment]
I tried again, it works only when :

- without dxwnd and its shortcut arguments
- use Xephr 16BPP mode (fullscreen mode, resolution not specified)
- launching directly the MotoRacer.exe file

**Comment by legluondunet** [comment]
I just reinstall the script on 2  different computer and the game just works.
More than this I can not obtain same tests result as you.
Your GOG version seems different than the one that is today provided by GOG.

**Comment by legluondunet** [comment]
Last thing, verify you installed all needed wine dependencies:

https://github.com/lutris/docs/blob/master/InstallingDrivers.md
https://github.com/lutris/docs/blob/master/WineDependencies.md

**Comment by legluondunet** [comment]
I have an idea, do you use a computer with two graphic card? Intel + Nvidia? Do you use optimus prime?
please post here the result of this command:

`$ lspci |grep VGA`

**Comment by abda11ah** [comment]
I'm using the nvidia 390xx proprietary driver on Arch linux (not the "nouveau" driver)

**Comment by legluondunet** [comment]
ok but please give me the rsult of this command, in a terminal type:

`$ lspci |grep VGA`

**Comment by abda11ah** [comment]
01:00.0 VGA compatible controller: NVIDIA Corporation GF119 [GeForce 605] (rev a1)

hardinfo program gives me 
Driver in use : nvidia

**Comment by abda11ah** [comment]
install the package xorg-xserver-xephyr.
Enable the lutris advanced options
Runner options --> enable Windowed (virtual desktop)
Runner options --> virtual desktop resolution 640x480
System options --> use Xephyr 16BPP fullscreen (resolution not specified)

dxwnd is not needed

**Comment by legluondunet** [comment]
@abda11ah  what is your distribution and version?
Benefits of DxWnd:
- 16 bits desktop color emulation
- scale the window game to your native screen resolution
- respect native game ratio

**Comment by abda11ah** [comment]
I think It's the same behavior as Xephyr mode 16BPP in fullscreen mode.
Vous parlez français ?

**Comment by abda11ah** [comment]
(Latest archlinux)
But old nvidia card (driver 390xx)

**Comment by legluondunet** [comment]
> install the package xorg-xserver-xephyr.
> Enable the lutris advanced options
> Runner options --> enable Windowed (virtual desktop)
> Runner options --> virtual desktop resolution 640x480
> System options --> use Xephyr 16BPP fullscreen (resolution not specified)
> 
> dxwnd is not needed

Does not completely works on my computer:

![ArcoLinux_2020-12-19_18-39-02](https://user-images.githubusercontent.com/325405/102695820-08e1af80-422a-11eb-9a37-f99e692355e4.png)

As you can see the game is not scaled to my computer screen (resolution 1920x1080).

**Comment by abda11ah** [comment]
I am traveling in Morocco.
I'm not going to retest the dxwnd game before at least one month.

**Comment by legluondunet** [comment]
I reproduced some severe issues on Arch I hadn't on Debian-like distros.
I found some tweaks to make Moto Racer 1 and 2 working on Arch Linux distro:
- xp mode
- use an older wine version
Tell me if it works for you when you welcome back from Morocco.
Thank you for your report.
