### ISSUE TITLE
Warcraft 3

### ISSUE THREAD

**Issue by avindra** [legluondunet/MyLittleLutrisScripts#54]
Two suggestions for https://github.com/legluondunet/MyLittleLutrisScripts/blob/master/Warcraft%20III/README.md

1) > You can not play multiplayer games on Internet ... playing Reforged version instead.

Actually you can play on iccup, which is one of the unofficial Battle.net gateways I'm aware of:

https://iccup.com/en/
https://liquipedia.net/starcraft/ICCup

2) > Directx 11 version in 1.31 patch

There is a new project called `dxwrapper` that includes [d3d8to9](https://github.com/crosire/d3d8to9) among other hacks and shims for running old DirectX games. This allows DXVK to run on all the older versions of Warcraft 3 in Directx9 mode, which is preferable since the OpenGL backend is trash.

https://github.com/elishacloud/dxwrapper/issues/99

-----

Here is a taste of `dxwrapper` and `iccup` (and of course `dxvk`):

![ic_menu](https://user-images.githubusercontent.com/126848/100311954-02d81600-2f7f-11eb-9b83-25453993e33c.jpg)

![ic_chat](https://user-images.githubusercontent.com/126848/100311947-ff448f00-2f7e-11eb-8823-f76e11598228.jpg)

**Comment by legluondunet** [comment]
Hello @avindra, thank you for your interesting report. 

1) concerning iccup, how it works, do you have a simple tutorial link to give me?
I think you can play Warcraft III on internet with Zerotier too, another possibility to verify.

2) Honestly Warcraft III (cd version, not directx11) works well on my computer, I don't see the benefit to use another wrapper.

**Comment by avindra** [comment]
1. For iccup install, there are [some instructions here](https://thebaltazar.tv/play-dota). They ship a modified client (I guess they modified hardcoded Battle.net servers in the exes).

2. The base Wine setup is too slow for me. I checked the fps ingame by sending `/fps` to chat, and it hovers around 20FPS ingame, and dips to 11FPS. For me, I need at least 60fps at all times. 95fps+ for newer monitors is even better, and this only works for me with dxvk (and dxwrapper, since I use a pre 1.31 WC3 patch).

**Comment by avindra** [comment]
I'll also add, for online games you'll need to have the `6112-6119` range open (usually involves forwarding the port from your router to your computer).

https://iccup.com/wc_start.html

That happens to overlap with the Diablo settings, so if your router application list is missing Warcraft, Diablo can be used instead (same port range).

**Comment by legluondunet** [comment]
@avindra 
1) I don't need to add dxwrapper to my W3 script: they already use dxvk, with directx9 for CD version and directx11 for PTR/Reforged. None of my Lutris script launch Warcraft III in opengl mode.

2) About your 1.31 WC3 patch, is it freely and legally downloadable ? For CD version last downloadable patch provided by Blizzard is  1.27b

3) for the moment I didn't find time to test multiplayer game

**Comment by avindra** [comment]
[1.31](https://liquipedia.net/warcraft/Patch_1.31.0) was released last year. I'm not sure where to get the patch files, as it doesn't seem like Blizzard published the exes somewhere like they did in the past.

Interesting to see that [1.27](https://liquipedia.net/warcraft/Patch_1.27a) is running DX9 out of the box. The patch notes improved compatibility with Windows 7, 8 and 10. I have a feeling that means this is the patch where they upgraded the Dx8 renderer to DirectX9.

ICCUP currently requires 1.26, so I guess 1.26 and before are using DX8.

I guess 1.31 is the best patch of the "classic" game since it it's new and supports DX11. Based on the naming convention, it looks like 1.31 might be the last patch for classic WC3 and all updates are going to the Reforged client only.

Closing the issue for now, hopefully people can make use of all of these version details :slightly_smiling_face:

**Comment by legluondunet** [comment]
Thank you sincerely for your contribution.
