### ISSUE TITLE
Heretic II (Linux CD) Sound Issue

### ISSUE THREAD

**Issue by CPUFronz** [legluondunet/MyLittleLutrisScripts#56]
After installing Heretic II from Linux CD, I didn't have any sound (Ubuntu 20.04). 

The problem was that 64-bit ALSA wasn't working well with 32-bit OSS. As suggested on [PCGamingWiki](https://www.pcgamingwiki.com/wiki/Heretic_II#Linux), I used ``padsp``, but that didn't help either. After some research I discovered the solution [here](https://ideatrash.net/2014/06/fix-padsp-to-use-pulseaudio-on-64-bi.html).

Install 32-bit libraries:
```
dpkg –add-architecture i386
apt-get update
apt-get install libpulse0:i386 libpulsedsp:i386
```
```
sudo cp /usr/bin/padsp /usr/bin/padsp32
sudo vi /usr/bin/padsp32
```
Change the occurrences of 64-bit libraries to 32-libraries:
- in line 77 ``LD_PRELOAD=/usr/lib/x86_64-linux-gnu/pulseaudio/libpulsedsp.so`` to ``/usr/lib/i386-linux-gnu/pulseaudio/libpulsedsp.so``
- in line 79 ``LD_PRELOAD="$LD_PRELOAD /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsedsp.so"`` to ``LD_PRELOAD="$LD_PRELOAD /usr/lib/i386-linux-gnu/pulseaudio/libpulsedsp.so"``

Then use padsp32 to launch Heretic II: Right click on Heretic II in Lutris :arrow_right: System Options :arrow_right: Command prefix: ``padsp32``

Since it requires some modifications on the system, I don't really know how you could incorporate this into your script. Maybe mentioning it in the description is the best way.

**Comment by tommycw1** [comment]
Just a note here that I had the same issue.  I came to file a report and found it was already reported.  I followed these steps and it worked, I now have sound!  Thanks to @CPUFronz for the fix and thanks to @legluondunet for the set up to allow me to play my old Linux CD game.

**Comment by legluondunet** [comment]
The gaming experience with the Linux version of Heretic is today inferior to the Windows version + patch 1.7 and presents several problems that I cannot resolve, the sound problem being major.
I don't want to maintain Lutris installer scripts that don't provide a good gaming experience to users, I prefer to maintain fewer installer scripts and keep the quality.
