### ISSUE TITLE
Myst: Masterpiece Edition (GOG + Scummvm)

### ISSUE THREAD

**Issue by Gapstare** [legluondunet/MyLittleLutrisScripts#57]
Hi!

When I installed and started I got this error in the log:
`scummvm: Unrecognized game 'mohawk'. Use the --list-targets and --list-games commands for a list of accepted values.`

When I change `mohawk` to `mohawk:myst` in the launcher the game starts.

**Comment by legluondunet** [comment]
Hello @Gapstare,

thank you for your report.
Could you try with "myst" instead of "mohawk:myst"?
Does the game launch with only "myst"?
