### ISSUE TITLE
Myst: Masterpiece Edition does not start

### ISSUE THREAD

**Issue by ntrepid8** [legluondunet/MyLittleLutrisScripts#58]
When installing on Ubuntu 20.04 I see a scummvm error "Unrecognized game target 'mohawk:myst'". Should this work or do I need to change something?

It looks like there was a recent change to the launch script: 8932fc8f92086ab3d4245f9c7c5d550c170134cc

Do I need an update to Lutris or something? Currently I have `lutris-0.5.8`.

Here is my release info:
```
Linux jda-trex 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

Here is the full log:
```
Running gamemoderun /home/ntrepid8/.local/share/lutris/runners/scummvm/bin/scummvm --extrapath=/home/ntrepid8/.local/share/lutris/runners/scummvm/share/scummvm --themepath=/home/ntrepid8/.local/share/lutris/runners/scummvm/share/scummvm --aspect-ratio --no-fullscreen --gfx-mode=3x --path=/home/ntrepid8/Games/myst-masterpiece-edition --language=en --filtering mohawk:myst
Initial process has started with pid 160883
Start monitoring process.
scummvm: Unrecognized game target 'mohawk:myst'
Usage: scummvm [OPTIONS]... [GAME]

Try 'scummvm --help' for more options.
Monitored process exited.
Initial process has exited (return code: 256)
All children have exited.
Exit with returncode 256
```

**Comment by ntrepid8** [comment]
I tried changing the value of the "Game identifier" option from `mohawk:myst` to `mohawk` the game launches as expected. I haven't played all the way through the game yet, but so far with this change it seems to be working.

**Comment by legluondunet** [comment]
Hello @ntrepid8,
thank you for your report, could you try this steps:
1) uninstall Myst ME from Lutris
2) uninstall ScummVM runner
3) reinstall Myst ME from Lutris script, ScummVM version 2.2.0 runner will be automatically reinstalled during Myst ME install

Do you still have this issue after following this steps?

**Comment by legluondunet** [comment]
I tested on 3 different computers, ScummVM launched Myst with mohawk:myst, no more with only mohawk.
I think you used an old ScummVM Lutris runner version.
