### ISSUE TITLE
Syberia installer error

### ISSUE THREAD

**Issue by dandishonored** [legluondunet/MyLittleLutrisScripts#59]
Hello, I tried to install Syberia.

Lutris says "Source does not exist: /home/user/.cache/lutris/installer/syberia/app"

and innoextract in console gives error: Could not open file "$setup"

**Comment by legluondunet** [comment]
Hello @dandishonored , thank you for your report.
I just tested Syberia Lutris script and it just installed correctly.
What setup file did you use? You downloaded it from your GOG account page recently? 
Other...
Which language?
I need Lutris log:
- open a terminal and launch Lutris in debug mode 
`lutris -d>lutris.txt`
- install the game again and when you finished, close Lutris and post the lutris.txt file here

**Comment by legluondunet** [comment]
no answer from user, close.

**Comment by dandishonored** [comment]
Hello,
I just got e-mail today that case was closed. Google is upset by me disabling spying services. I just installed new version of Lutris and it works. Default version in Debian Buster is broken.

Thank you.
Dan
