### ISSUE TITLE
Age of Empires: German CD not detected

### ISSUE THREAD

**Issue by BifbofII** [legluondunet/MyLittleLutrisScripts#6]
The executable file for the installation on the german AOE CD (or at least on mine, maybe it is because of something else) is names differently (`aoesetup.exe` istead of `aoeinst.exe`).
I will open a Pull request shortly with a suggested fix, but feel free to implement a different solution.

**Comment by BifbofII** [comment]
Added the pull request with a suggested fix here: #7

**Comment by legluondunet** [comment]
Hello @BifbofII , thank you for your report and your pr.
I will try to find a way to make my installer german CD compatible.
Could you join to this thread the log of this command:
`tree /path/to/your/AOECD/>aoegermancd.log`

**Comment by BifbofII** [comment]
[aoegermancd.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/3720707/aoegermancd.log)
Here is the tree of the CD.
I also have a second CD (actually I'm not sure if it is ROR or the Gold edition, haven't had them out in years) that has the same problem. I will look into this and provide the tree for this disc and a possible fix later.

**Comment by legluondunet** [comment]
> I will look into this and provide the tree for this disc and a possible fix later.

It could help thanks.

**Comment by BifbofII** [comment]
[aoegermancd2.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/3721466/aoegermancd2.log)
Here is the tree of the second disc. As I said, I'm not sure if this is ROR or the Gold Edition, since I do not have the original CDs but only copies and you scripts identify ROR and the Gold Edition from the same file.

**Comment by legluondunet** [comment]
Gold version: you have two icons files in the cd root folder:
empires.ico and aoex.ico
ROR version: only aoex.ico
So I think you posted the ROR version.

**Comment by legluondunet** [comment]
I just modified two installers:
Age of Empires standard
and
Age of Empires Gold Edition
to recognize AOE version with aoesetup.exe.
Could you give them a try?

**Comment by BifbofII** [comment]
Unfortunitely it does not work.
Your `findaoe.sh` does find the setup file and creates a batch file that references the setup file.
However, this created batch file is named `test.bat` and located in `$GAMEDIR`. The next command in the lutris script then tries to execute `$GAMEDIR/drive_c/tmp/aoeinstall.bat` which does not exist.
Changing the reference to the batch file to `$GAMEDIR/test.bat` did however still not fix every problem.
I managed to get it to work now (See #7) and did also rewrite the `findaoe.sh` script to parse the `autorun.inf` file so it should work, even if another language should have a even more different setup file name.
I was working on updating the clean script as well, but still have an error there.

**Comment by BifbofII** [comment]
I only tested the normal version, not the gold one because I do not have a CD of the gold version.

**Comment by legluondunet** [comment]
Sorry I forgot to update my script to the last version, could you try again please.

**Comment by BifbofII** [comment]
```
Running /home/christoph/.cache/lutris/installer/age-of-empires/scriptinstall/findaoe.sh <private path>/AOE
found aoesetup.exe
~/.cache/lutris/installer/age-of-empires/scriptinstall/findaoe.sh: Line 17: drive_c/tmp/aoeinstall.bat: File or directory not found
```
It does not find the the path to write the batch file. Does the `tmp` directory already exist at that stage?

**Comment by legluondunet** [comment]
`It does not find the the path to write the batch file. Does the tmp directory already exist at that stage?`
just fixed

**Comment by BifbofII** [comment]
It does work now!
Thanks for the work you put in and again, sorry for the confusion I caused in the PR.

**Comment by legluondunet** [comment]
don' be sorry, your pr are very inetresting, but too complex to maintain for me or for other people like me that have not big development level knowledge. 
Now I have to add this script to ROR installer and delete temporary files.

**Comment by legluondunet** [comment]
- german cd compatibility: done
- remove temporary files:done
thank you for your help @BifbofII
