### ISSUE TITLE
[Issue] Beyond Good & Evil - target location of downloadables

### ISSUE THREAD

**Issue by psstoyanov** [legluondunet/MyLittleLutrisScripts#60]
> Hello, to report your issue, please follow this steps:
>     
>     1) start Lutris in debug mode, in a terminal type this command:
>     lutris -d > lutris.log
>     2) if already installed, uninstall (remove) your game
>     3) now come back to your game Lutris page installer and reinstall it. 
>     At the end of the install, try to launch the game. 
>     If the issue persists, please post the lutris.log debug file to this thread
>     4) copy/paste the results of this 2 commands:
>     uname -a
>     lsb_release -a
>     5) put the game name in the issue report title
> 
> Thank you for your issue report.

 - [] 1) start Lutris in debug mode, in a terminal type this command: **Not applicable** **X**
- [X] 2) if already installed, uninstall (remove) your game
- [X] 3) now come back to your game Lutris page installer and reinstall it. => Breaks here
- [X] 4) copy/paste the results of this 2 commands:
```➜  ~ uname -a
Linux fr0sthutpc 5.10.0-1-MANJARO #1 SMP PREEMPT Mon Nov 23 00:49:00 UTC 2020 x86_64 GNU/Linux
➜  ~ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        20.2
Codename:       Nibia
```
- [X] 5) put the game name in the issue report title

When installing Beyond Good and Evil, it appears that there is a typo in the script:

```
  "custom-name": "Beyond Good & Evil - GOG",
    "files": [
        {
            "setup": "N/A:Select the EXE downloaded from GOG"
        },
        {
            "wds": "https://github.com/legluondunet/MyLittleLutrisScripts/raw/master/Beyong%20Good%20and%20Evil/bgewidescreen.zip"
        },
        {
            "audio": "https://github.com/legluondunet/MyLittleLutrisScripts/raw/master/Beyong%20Good%20and%20Evil/dsound.dll"
        },
        {
            "gppx360": "https://github.com/legluondunet/MyLittleLutrisScripts/raw/master/Beyong%20Good%20and%20Evil/gamepad%20profiles/bge_x360.gamecontroller.amgp"
        },
        {
            "gppsteam": "https://github.com/legluondunet/MyLittleLutrisScripts/raw/master/Beyong%20Good%20and%20Evil/gamepad%20profiles/bge_steam.sccprofile"
        },
        {
            "gppreadme": "https://github.com/legluondunet/MyLittleLutrisScripts/raw/master/Beyong%20Good%20and%20Evil/gamepad%20profiles/bge_gamepad_readme.html"
        }
        
```

The setup files aren't downloading.
Cloning the repo locally to use the files instead of downloading them, does work.

**Comment by psstoyanov** [comment]
Submitted the edit for the installer script on Lutris.

The typo was in the URL:

> "github.com/legluondunet/MyLittleLutrisScripts/raw/master/Beyon<i>**g**</i>%20Good%20and%20Evil/bgewidescreen.zip"

**Comment by legluondunet** [comment]
Hello @psstoyanov, thank you for your report.
It's now fixed.
