### ISSUE TITLE
serious sam second encounter hd

### ISSUE THREAD

**Issue by Berbon9072** [legluondunet/MyLittleLutrisScripts#61]
Hello, to report your issue, please follow this steps:
    
    1) start Lutris in debug mode, in a terminal type this command:
    lutris -d > lutris.log
    2) if already installed, uninstall (remove) your game
    3) now come back to your game Lutris page installer and reinstall it. 
    At the end of the install, try to launch the game. 
    If the issue persists, please post the lutris.log debug file to this thread
    4) copy/paste the results of this 2 commands:
    uname -a
    lsb_release -a
    5) put the game name in the issue report title

Thank you for your issue report.

**Comment by Berbon9072** [comment]
Serious sam hd deuxième rencontre wine windows ne fonctionne plus
hibon @ hibon-System-Product-Name: ~ $ lutris
qt5ct: utilisation du plugin
qt5ct 2020-12-05 20: 09: 18,537: Initialisation de lutris
2020-12-05 20:09: 18 946: Runtime à jour. Initialisation terminée.
2020-12-05 20: 09: 18,952: Lutris 0.5.8.1
2020-12-05 20: 09: 18.952: Utilisation des pilotes NVIDIA 455.45.01 pour x86_64
2020-12-05 20: 09: 18.952: GPU: GeForce GTX 1660
05/12/2020 20: 09: 18,952: GPU: 10DE: 2184 1458: 3FC8 (pilotes nvidia)
05/12/2020 20: 09: 49,017: Obtention d'informations sur les coureurs pour wine
qt5ct: utilisation du plugin
qt5ct 2020-12-05 20 : 09: 54,316: Ecriture dans /home/hibon/.local/share/icons/hicolor/128x128/apps/lutris_serious-sam-hd-the-second-encounter.png
qt5ct: utilisation du plugin qt5ct
Exception ignorée dans: <function InputDevice. del at 0x7fda73cadaf0>
Traceback (dernier appel en dernier):
Fichier «/usr/lib/python3/dist-packages/evdev/device.py», ligne 159, dans del
self.close ()
Fichier «/ usr / lib / python3 /dist-packages/evdev/device.py », ligne 304, en close
super (). close ()
Fichier« /usr/lib/python3/dist-packages/evdev/eventio_async.py », ligne 54, en
boucle fermée = asyncio.get_event_loop ()
Fichier «/usr/lib/python3.8/asyncio/events.py», ligne 639, dans get_event_loop
lever RuntimeError ('Il n'y a pas de boucle d'événement en cours dans le thread% r.'
RuntimeError: Il n'y a pas boucle d'événement en cours dans le thread 'Thread-2'.
2020-12-05 20: 10: 21,060: En attente de l'arrêt de Steam…
2020-12-05 20: 10: 21,060: Arrêt de Steam
Running /home/hibon/.local/share/lutris/runners/wine/lutris- 5.7-11-x86_64 / bin / wine /home/hibon/.local/share/lutris/runners/winesteam/prefix64/dosdevices/…/drive_c/Program Files (x86) /Steam/steam.exe -no-cef-sandbox -console -shutdown
Le processus initial a démarré avec pid 8135
Démarrez le processus de surveillance.
Erreur du client wine: 0: incompatibilité de version 653/604.
Votre binaire wine n'a pas été mis à jour correctement
ou vous en avez un plus ancien quelque part dans votre PATH.
Ou peut-être que le mauvais serveur de vins fonctionne toujours?
Processus surveillé terminé.
Le processus initial s'est terminé (code retour: 256)
Tous les enfants sont sortis.
Sortie avec le code retour 256
2020-12-05 20: 10: 31,784: Forcer l'arrêt de Steam
2020-12-05 20: 10: 31,828: Tuer PID 3102
Exécution de gamemoderun /home/hibon/.local/share/lutris/runners/wine/ lutris-5.7-11-x86_64 / bin / wine /home/hibon/.local/share/lutris/runners/winesteam/prefix64/dosdevices/…/drive_c/Program Files (x86) /Steam/steam.exe -no-cef -sandbox -console steam: // rungameid / 41010
Le processus initial a démarré avec pid 8174
Démarrer le processus de surveillance.
ERREUR: ld.so: l'objet '/usr/$LIB/libgamemodeauto.so.0' de LD_PRELOAD ne peut pas être préchargé (impossible d'ouvrir le fichier d'objet partagé): ignoré.
ERREUR: ld.so: l'objet '/usr/$LIB/libgamemodeauto.so.0' de LD_PRELOAD ne peut pas être préchargé (impossible d'ouvrir le fichier d'objet partagé): ignoré.
Erreur du client wine: 0: incompatibilité de version 653/604.
Votre binaire wine n'a pas été mis à jour correctement
ou vous en avez un plus ancien quelque part dans votre PATH.
Ou peut-être que le mauvais serveur de vins fonctionne toujours?
Processus surveillé terminé.
Le processus initial s'est terminé (code retour: 256)
Tous les enfants sont sortis.
Sortie avec le code retour 256
2020-12-05 20: 10: 34,944: Jeu toujours en cours (état: en cours)
2020-12-05 20: 10: 34,945: Arrêt de Serious Sam HD: The Second Encounter (winesteam)

**Comment by legluondunet** [comment]
Salut Berbon, désolé mais je ne vais pouvoir t'aider sur ce script, je n'en suis pas l'auteur.

Concernant ces lignes:
```

Erreur du client wine: 0: incompatibilité de version 653/604.
Votre binaire wine n'a pas été mis à jour correctement
```
Elles signifient que des process de wine ne sont pas fermés et résident en mémoire. Il faut tous les "killer" avant de lancer un nouveau jeu avec wine.
