### ISSUE TITLE
Does Warcraft III require CD only or can Blizzard's installers work?

### ISSUE THREAD

**Issue by LostWanita21** [legluondunet/MyLittleLutrisScripts#62]
I used an original CD to get it working after some tinkering, which wasn't the easiest, but I was wondering if it were possible to support one of Blizzards legacy installers? at least for versions 1.27b and lower.

**Comment by legluondunet** [comment]
Hello @LostWanita21, I don't understand very well your question, what do you call "Blizzards legacy installers? at least for versions 1.27b and lower."?

**Comment by LostWanita21** [comment]
> Hello @LostWanita21, I don't understand very well your question, what do you call "Blizzards legacy installers? at least for versions 1.27b and lower."?

There's two, one is from Blizzard themselves via FTP server links they have, though I don't believe those work anymore, the links do but the file was a downloader.

The other is instillation files for 1.21, I can send a link if requested but that one is basically an old standalone installer, those go up to 1.27b

**Comment by legluondunet** [comment]
I wrote Warcraft III script  mainly for people that want to play their old cd on Linux. Legacy version is legally litigious. If there are no other legal way, it's better to download reforge.

**Comment by LostWanita21** [comment]
> I wrote Warcraft III scripts mainly for people that want to play their old CD on Linux in good conditions. Legacy version is legally litigious to distribute. If there are no other legal way, it's better to download reforge.

They used to be on Blizzards own site, you needed an original CD key to use em but they had em in their site at one time.

https://www.hiveworkshop.com/threads/warcraft-3-legacy-installer-1-21b-1-27a.307766/

**Comment by legluondunet** [comment]
Hello @Ghost, for your information, I wrote Lutris scripts for W3 digital edition 1.27, for ROC and his extension TFT.
The game are downloaded directly from an official Blizzard app.
https://lutris.net/games/warcraft-iii-reign-of-chaos/
https://lutris.net/games/warcraft-iii-the-frozen-throne/
