### ISSUE TITLE
Rayman 2 on Pi4

### ISSUE THREAD

**Issue by imsl0wer** [legluondunet/MyLittleLutrisScripts#64]
[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/5761995/lutris.log)
Linux Twister 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
Trying to run Rayman 2 on my Pi 4 and can't get it to work :c

**Comment by legluondunet** [comment]
Sorry but Linux ARM platform are not supported for the moment.
