### ISSUE TITLE
[Wayland] Beyond Good and Evil audio fix and Wayland sessions

### ISSUE THREAD

**Issue by psstoyanov** [legluondunet/MyLittleLutrisScripts#65]
1) N/A
2) N/A
3) N/A
4) copy/paste the results of this 2 commands: ☑
```
Linux fr0sthutpc 5.10.2-2-MANJARO #1 SMP PREEMPT Tue Dec 22 08:14:42 UTC 2020 x86_64 GNU/Linux
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        20.2.1
Codename:       Nibia
```
GPU: Radeon RX6800 with Mesa
Display: 3440x1440p @ 144hz 
5) put the game name in the issue report title ☑

As the name suggests, this is specific to Wayland and I'm formulating it more in the form of a question. The reason for this - the game runs as expected within X11 environment.

With Beyond Good & Evil installed on the system, I can observe the following behavior:
X11:
- The game runs as expected
- Widescreen is functioning
- There are no audio sync issue

Switching to a Wayland session (such as Plasma Wayland or Wayfire/ Sway):
- With dxvk enabled:
  - No graphical artifacts
  - Audio sync issue present - the cutscenes are sped up 
  - No audio looping
  - SettingsApplication.exe doesn't work (something I have found to happen with dxvk and d3d9 titles)
  
- With dxvk disabled:
  - Audio sync issue present - the cutscenes are sped up
  - No audio looping 
  - SettingsApplication.exe does work, however the refresh rate is seen only as 50hz (instead of the system's 144hz)
  - Graphical artifacts with the default preset (only the hair of the characters being visible for example)
  - No graphical artifacts 

I haven't found any other references online for resolving the audio sync of this game in Wayland session specifically. How to approach exploring and debugging this issue?

**Comment by legluondunet** [comment]
Hello, thank you for this report. Wayland is a young project and is not yet ready for gaming.
If you want playing games, for the moment stay on X11 until Wayland becomes more mature for gaming.

**Comment by psstoyanov** [comment]
Hi, thanks for the reply.
I understand that X11 support is more mature and I don't have issues with using it for gaming purposes. With that in mind, I would still like to explore and find how to improve the experience with Wayland.

I needed a place to write down the findings, which helped at least a bit with structuring and getting a better understanding of how to isolate the issues.

After creating the ticket, I've found the following:
- The graphical artifacts are independent from X11 or Wayland
 - The same behaviour of incorrect draw render happened with the default settings with dxvk disabled on X11 as well
 - Setting everything to maximum from SettingsApplication.exe doesn't exhibit artifacts with dxvk disabled on either session.


Further X11 behaviour:
- The SettingsApplication.exe can see 50hz/60hz/120hz but not 144hz
- The audio sync issue is present when setting the game to 120hz
- The audio sync issue is not present when setting the game to 50hz or 60hz

Further Wayland behaviour:
- While it appears that SettingsApplication.exe can see only 50hz, it behaves as 120hz on X11
- Saving the settings from the X11 session (where the game doesn't have audio sync issue), it appears as if they aren't applied or enforced when launching the game in the Wayland session. It behaved the same as if the game was set to 120hz on X11 with audio sync issue.

The game as expected is using Xwayland to run.

Final findings:
- Setting the Wayland session refresh rate to 60hz **does** allow the game run without audio sync issues

This leads me to believe that if the game is running through Xwayland, the refresh rate is set from the parent session itself and not through the individual instance.

If I could find a method to set the refresh rate for an individual Xwayland application, then there could be a more permanent fix than the workaround I have found.

**Comment by legluondunet** [comment]
Even if your research and questions are outside the current scope of this project, i must admit that i find it all very interesting. 
All infos that permet to know better how a game works interests me. All the information that allows me to better understand how a game works interests me. 
If I understood well, actually you search a solution to set the game to 60 fps. But on Wayland settings BGAE fps  has no effect, the game fps follow Wayland ones, right? What about inactivate vsync? 
Perhaps you already know it but all graphics options stored in registry in  "current user/software/gog...".

**Comment by psstoyanov** [comment]
> Even if your research and questions are outside the current scope of this project, i must admit that i find it all very interesting.
> All infos that permet to know better how a game works interests me. All the information that allows me to better understand how a game works interests me.
> If I understood well, actually you search a solution to set the game to 60 fps. But on Wayland settings BGAE fps has no effect, the game fps follow Wayland ones, right? What about inactivate vsync?
> Perhaps you already know it but all graphics options stored in registry in "current user/software/gog...".

Thank you, I share similar interest to of understanding the behaviour of the games.

> If I understood well, actually you search a solution to set the game to 60 fps. But on Wayland settings BGAE fps has no effect, the game fps follow Wayland ones, right? What about inactivate vsync?

I'm not entirely sure as I have just begun looking into it.

I have found a few references, which spiked my interest:
- The first one is about xwayland using the display refresh rate: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1103
- https://gitlab.freedesktop.org/xorg/xserver/-/issues/631
- This bug could've been handy however I don't know if I experience it and I can't find how to run BGAE in windowed mode: https://gitlab.freedesktop.org/xorg/xserver/-/issues/20

I don't know how to disable vsync for BGAE or wine. 
The used names in the BGAE settings seem a bit odd. Additionally, most of the references I have found for this game usually ask for vsync to be enabled and for some settings to be enabled through Nvidia's panel to resolve the audio sync (not helpful - Radeon user here).

>  Perhaps you already know it but all graphics options stored in registry in "current user/software/gog...".
I wasn't aware of this. Would this be a windows registry of wine setup for the game? ie /`home/<current_user>/Games/gog/<game_name>`
I have found several instances of the refresh rate being set to 50fps in the default wine config for the game which explains why the SettingsApplication.exe was seeing only 50 there. I don't recall which one I've altered to 60 but it was reflected in the SettingsApplication.exe.

As I haven't found the method to run the game in windowed mode, the first link towards xwayland using the display refresh rate in fullscreen mode seems like the most promising candidate for now.

While writing this, I got a message with this link to Collabora - wine+wayland efforts: https://www.collabora.com/news-and-blog/news-and-events/a-wayland-driver-for-wine.html . This would be something else to add to the stack of things to test in the coming weeks.

**Comment by psstoyanov** [comment]
Throwing an update here as there is a method to enforce a framerate limit with DXVK.

Adding the following environment variable in Lutris for the title, locks it and the audio is no longer faster than whats presented on the screen:
```
DXVK_FRAME_RATE=60
```
