### ISSUE TITLE
Star Wars Knights of The Old Republic (GOG) widescreen patch not applied during installation 

### ISSUE THREAD

**Issue by samxl001** [legluondunet/MyLittleLutrisScripts#67]
I installed Star Wars Knights of The Old Republic (GOG) via lutris installer. After the installation when I launch the game the wide screen patch is not applied. My screen resolution is 2560*1440. Is that why the patch is not installed? 

Here is the log for installation:

https://gist.github.com/samxl001/0517ec6cfbc53ee58537c97473c6c67e

**Comment by legluondunet** [comment]
Hello,
try this:
1) update Lutris
2) uninstall all Lutris Wine 6 version
3) reinstall "Star Wars Knights of The Old Republic (GOG)" game
4) if the issue still present, please post a new log

**Comment by samxl001** [comment]
Hello thank you for the reply. But I am afraid that I no longer have the game. I refunded the game as I couldn't play it properly on my monitor. So I can't test the installation

**Comment by legluondunet** [comment]
ok ,thank you for your answer.
