### ISSUE TITLE
[AOE] Upatch configurator messed up, and unusable

### ISSUE THREAD

**Issue by TheFrenchGhosty** [legluondunet/MyLittleLutrisScripts#69]
When installing Age of Empires (CD + DxWnd version) (and Age of Empires - Rise of Rome (CD + DxWnd version)) the Wine Desktop window appearing during the installation remains black (I tried waiting, nothing changed), if I close it the installation seems to continue, but then when running the game, I do get the Wine Desktop with the CMD prompt, but choosing the game doesn't work.

If I try to then install the "Upatch HD version" it says that it can't find the game, and from what I'm reading in the log, the file copy failed (because, I'm guessing the whole installation failed).

Note: The copy of the main game, and the Rise of Rome extension I use, is originally from "Age of Empires: Collector's Edition (Ubisoft Exclusive)" but I copied those to disk (without the Collector's Edition "installer", that just open the installer of the game included), it's the exact same thing originally included in the real CD, just in a compilation, this should be the same thing, and should cause this problem.

>uname -a / lsb_release -a:

ArchLinux x86_64 / Kernel ```linux```: 5.10.9-arch1-1

Tried on both an Intel Ivy Bridge CPU (I suspected it was the problem), and an AMD Ryzen.

The issue happen with both wine and wine-stagging installed on the system.

lutris.log (with private information redacted): [lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/5870816/lutris.log)

Edit: It worked after trying a copy of the Gold edition, I guess the copy I have is broken in some way. Now though, after using the Upatch installer the lutris install window just freeze, and when started via the Wine desktop of the game itself, it open on the menu and close instantly :(

Edit 2: Previous issue fixed by using lutris-git.

Everything is working now, except the messed up Upatch configurator, thanks a lot

**Comment by legluondunet** [comment]
> Everything is working now, except the messed up Upatch configurator, thanks a lot

Hello, uninstall all Lutris Wine 6, then reinstall Upatch.
Older Lutris Wine version does not install correctly dotnet component needed by Upatch configurator.
Good luck!

**Comment by TheFrenchGhosty** [comment]
>uninstall all Lutris Wine 6, then reinstall Upatch.

How am I supposed to do that exactly? Un-ticking lutris-6.0 from the wine runner list doesn't seem to change anything, since it's re-downloaded when I start the installation of Upatch

**Comment by legluondunet** [comment]
I would like to be sure you use the last Lutris Wine 6 version and not the previous one, 6rc1.

**Comment by legluondunet** [comment]
You could now try this: install dotnet40 with winetricks.

**Comment by TheFrenchGhosty** [comment]
>I would like to be sure you use the last Lutris Wine 6 version and not the previous one, 6rc1.

lutris-6.0 is what's used.

>You could now try this: install dotnet40 with winetricks inside age of empire wineprefix.

Will do.

**Comment by TheFrenchGhosty** [comment]
Okay, so I did install dotnet40 from inside lutris, and well, first it complained a lot:


>You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

>This package (dotnet40) may not fully work on a 64-bit installation. 32-bit prefixes may work better.

>dotnet40 does not yet fully work or install on wine.  Caveat emptor.

Then it seems to install (according to htop), but when I run the configurator again it's still broken.

After reinstalling Upatch, the configurator refuse to start, but starting the game through it seems to work (and now there's music, because yes, there were only sound effect before...).

I'm not *super* experienced with wine and co, so this really is hard for me to debug anything.

By the way, if dotnet40 is needed... why isn't it installed by the script?

**Comment by legluondunet** [comment]
"By the way, if dotnet40 is needed... why isn't it installed by the script?"
it was a test, for me the script works without dotnet40 on my computer.

**Comment by legluondunet** [comment]
You perhaps missed some wine dependencies?
Follow this tutorial:
https://github.com/lutris/docs/blob/master/WineDependencies.md

**Comment by TheFrenchGhosty** [comment]
>You perhaps missed some wine dependencies?

Nope, I had everything.

**Comment by legluondunet** [comment]
I will need more info to help you.
To create a log, first close Lutris completely. Then, open your terminal application, execute 
lutris -d 
and try to reproduce your issue (open Upatch configurator).
After that, you need to copy the output in the terminal and share it with us (all of it).
It's recommended to use this ad-free paste service: https://paste.ubuntu.com/

**Comment by legluondunet** [comment]
1°) I saw this in your log:
```
les variables --> cdname:AOE cddev:
./cdparanoia: option requires an argument -- 'd'
cdparanoia III release 10.2 (September 11, 2008)
```
script installer could not extract audio tacks from your AOE CD, it didn't find your CD device.
So you don't have music ingame.

2°) Broken Upatch window is a know issue but it should open and you can select option, even if it's hard to read lable:

![Capture d’écran de 2021-01-27 02-01-54](https://user-images.githubusercontent.com/325405/105927130-a6a77600-6043-11eb-839b-01c0124cfc97.png)

**Comment by TheFrenchGhosty** [comment]
Fresh install of the Gold Edition, and fresh install of Upatch: [lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/5877002/lutris.log) (private information redacted)

I'm not seeing anything wrong.

**Comment by TheFrenchGhosty** [comment]
> So you won't have music ingame. How did you mount your CD? Real CD/DVD device? ISO?

ISO

>2°) Broken Upatch "Settings" window is a know issue but it should open and you can select option, even if it's hard to read labels:

I'm actually getting exactly what's on the screenshot... so it's a non-issue?

**Comment by TheFrenchGhosty** [comment]
Since the broken configuration page is a non-issue, and since music works now (even though nothing changed), I guess this issue can be closed.

Unless you're seeing any more problem?

**Comment by legluondunet** [comment]
You are right, my script is not compatible with Collector's Edition.
Now that you use a compatible AOE version,  script works as expected. 
There is nothing I can do for "Settings" window, we have to wait for a better dotnet support in WIne.
We can now close this issue.

**Comment by TheFrenchGhosty** [comment]
I'm glad everything works, one step closer to never have to use windows again!

Thanks a lot for those installers by the way, and for helping me understood the issues!

**Comment by legluondunet** [comment]
Even if it is broken, you can set in "Settings" window:
- language
- your screen resolution
other options are not very important.

>  don't even know if the mod is actually running since nothing really looks "more high resolution".

Launch 3, then launch 4, you will see differences.

**Comment by TheFrenchGhosty** [comment]
>your screen resolution

Actually I just checked and it's not possible, it always revert to 800x600. 

According to the UPatch documentation ( https://upatch-hd.weebly.com/settings.html ): 

>If instead of the selected resolution, the game starts in 800x600, then the resolution you applied is not supported by your computer. Try another custom resolution.


>Launch 3, then launch 4, you will see differences.

I actually looked at the feature of UPatch on the website, and can indeed confirm that it works.

**Comment by legluondunet** [comment]
I play the game in 800x600, scale to my reslution screen 1920x1080.
640x480 ingame resolution is too pixellated and if I choose 1280x720 the game elements are too little.

**Comment by TheFrenchGhosty** [comment]
Yeah, it works correctly indeed (and I agree 800x600 is really good), it's just that the mod is supposed actually render at 1080p, so it's technically a "bug" that it doesn't work here.

**Comment by legluondunet** [comment]
interesting, I will check.

**Comment by legluondunet** [comment]
Sorry I said you mistakes, if you choose 4 in menu (Upatch), set you resolution to your screen resolution and it will render atthis resolution.
In game options, resolution will be indicated as "personnalized".
DxWnd is not use for Upatch choice 4.
I joined you a screen of the result on my computer, the size image is 1920x1080.
![Capture d’écran de 2021-01-27 02-51-43](https://user-images.githubusercontent.com/325405/105931067-d0b06680-604a-11eb-9355-dd36d6506134.png)

**Comment by legluondunet** [comment]
this discussion is not finished :D

**Comment by TheFrenchGhosty** [comment]
Well... every-time I set the game to 1920x1080p it goes back to 800x600, and in the setting it's not set to custom (but it is set to custom when I use the third "12" (it's the one that looks the best, so I'm guessing 1280x720)

**Comment by legluondunet** [comment]
try this:
--> choice 4 upatch
--> Settings
--> Choose resolution 1440x900
Start the game, is it launch in a window with a size of 1440x900?

**Comment by legluondunet** [comment]
then set again Upatch resolution to your native resolution, does it goes back to 800x600 or 1920x1080?
I think if you change resolution in others game choice it could interfere with Upatch resolution settings.

**Comment by TheFrenchGhosty** [comment]
> Start the game, is it launch in a window with a size of 1440x900?

No, it goes back to 640x480.

**Comment by legluondunet** [comment]
it's not normal, I will do some tests about this tomorrow on others computers than mine.

**Comment by TheFrenchGhosty** [comment]
I just tested this on a laptop with a 1600x900 screen, choosing "16" in the configurator (for I'm guessing 1600x900), and it also goes back to 600x480.

However, like on the other computer, choosing 1280x720 works.

**Comment by legluondunet** [comment]
I just tested on another computer and I can not reproduce your issue.  Do you use multimonitor?

**Comment by TheFrenchGhosty** [comment]
2 on the 1080p PC, but the 900p one is a laptop, so one, and the issue is also here.
