### ISSUE TITLE
RealRTCW out of date

### ISSUE THREAD

**Issue by ajshell1** [legluondunet/MyLittleLutrisScripts#71]
The current script for RealRTCW is intended for RealRTCW 3.0.

They recently released 3.1: https://www.moddb.com/mods/realrtcw-realism-mod/downloads/realrtcw-31

I tried using the current script's version with the 3.1 release, and I think there are a substantial amount of bugs involved in doing so. Notably, the text that appears during a quicksave is changed to "Mission failed: you killed a kreisau agent", and my own gunshots don't make any sounds. The menu appears to be a vanilla RTCW menu instead of the RealRTCW menu.

Normally, I wouldn't bother making this issue, but I seem to be having issues getting RealRTCW working with Luxtorpeda, and I can't seem to be able to compile it myself.

**Comment by legluondunet** [comment]
Hello,
my Lutris script install "Linux GOG + RealRTCW x64 + mod version" is only compatible with RealRTCW mod version 3.0, full or light edition, available for download at  https://www.moddb.com/mods/realrtcw-realism-mod/news/realrtcw-30-complete-edition

To use released 3.1: https://www.moddb.com/mods/realrtcw-realism-mod/downloads/realrtcw-31
You have first to install my Lutris script then replace all content form main folder by Main folder content from 3.1 version.
I just tested it works.
Tell me if it works for you.
