### ISSUE TITLE
Just Cause 2 Standalone gets laggy

### ISSUE THREAD

**Issue by schwarzrotes** [legluondunet/MyLittleLutrisScripts#73]
Hello,
after a while i get lags in Just Cause 2 every time a chaos object is destroyed, at the moment i play with mods, but im sure i had it bevor i put mods in just not that extreme
sometimes it goes after a while but then ist there again, but when it occoures all savegames are laggy, only solution is to start new than its gone
i tryed a lot, i reinstalled a few times, tested without mods but savegames still laggy
not sure what it could be

5.10.0-4-amd64 #1 SMP Debian 5.10.19-1 (2021-03-02) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/6193333/lutris.log)

**Comment by legluondunet** [comment]
Hello, thank you for your report.
Could you try to reproduce your issue with a more recent Lutris Wine version (6.14)?

**Comment by legluondunet** [comment]
Just Cause 2 is now fully supported and functional in Steam with recent Proton version.
This Lutris script is today useless.
