### ISSUE TITLE
Silent Hill 2 FMV-Audio remastered script extends wrong title

### ISSUE THREAD

**Issue by droogie** [legluondunet/MyLittleLutrisScripts#74]
The installation script is referencing the wrong title for extension, causing the installation to fail.

https://lutris.net/games/install/25978/view

`"script":{"extends":"silent-hill-2"`

should be the following instead

`"script":{"extends":"silent-hill-2-directors-cut"`

**Comment by legluondunet** [comment]
Hello @droogie , thank you for your report,just fixed!
