### ISSUE TITLE
Tomb Raider 3 - Source does not exist

### ISSUE THREAD

**Issue by julienmartinelli** [legluondunet/MyLittleLutrisScripts#76]
Hello,

I have been trying to install Tomb Raider 3 thanks to your script. Installation failed and I ran into the following error:
Source does not exist: /home/guest/.cache/lutris/installer/tomb-raider-iii-adventures-of-lara-croft/app

This seems akin to this issue: https://github.com/legluondunet/MyLittleLutrisScripts/issues/25

Here are the logs requested for the issue:

lutris.log:
INFO     2021-04-02 22:30:58,760 [application.do_command_line:315]:Lutris 0.5.8.3
INFO     2021-04-02 22:30:58,760 [startup.check_driver:57]:Running Intel Mesa driver 20.2.6 on Mesa Intel(R) UHD Graphics 620 (KBL GT2) (0x5917)
INFO     2021-04-02 22:30:58,761 [startup.check_driver:69]:GPU: 8086:5917 1028:0815 (i915 drivers)
INFO     2021-04-02 22:31:05,048 [application.do_shutdown:598]:Shutting down Lutris

uname -a:
Linux guest-Latitude-5290 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

Thank you for your help !

**Comment by legluondunet** [comment]
Hello, thank you for your report, where did you download your game setup file? Manually from GOG? Or automatically from Lutris? Which language version?

**Comment by julienmartinelli** [comment]
manually from gog ! I did not select any particular language version so I guess the default one ?

**Comment by legluondunet** [comment]
si tu es français, je vais te parler en français, ce sera bien plus simple pour moi.
J'ai besoin que tu lances Lutris, dans un terminal, avec cette commande:
lutris -d > lutris.log
puis que tu désinstalles/réinstalles le jeu.
Une fois l'installation terminée, tu lances le jeu (si l'installation s'est correctement effectuée).
Enfin tu postes ici le fichier lutris.log

**Comment by julienmartinelli** [comment]
Salut,

Le problème était côté utilisateur visiblement ... Après avoir refait une tentative d'installation du jeu via Lutris, tout fonctionne parfaitement. Merci pour le script TR3 en tout cas !!

**Comment by legluondunet** [comment]
Si tous les bugs pouvaient se résoudre aussi facilement.
