### ISSUE TITLE
Star Wars KOTOR fails: swkotor.ini and swkotor.exe missing

### ISSUE THREAD

**Issue by gjost** [legluondunet/MyLittleLutrisScripts#79]
I purchased Star Wars: Knights of the Old Republic from GOG and downloaded the installer files:
```
setup_star_wars_-_knights_of_the_old_republic_1.03_(29871).exe
setup_star_wars_-_knights_of_the_old_republic_1.03_(29871)-1.bin
```

I ran the Lutris installer but it quit with this message:
```
Source does not exist: /home/gjost/games/star-wars-knights-of-the-old-republic/drive_c/GOG Games/Star Wars - KotOR/__support/app/swkotor.ini
```

I was able to find a `swkotor.ini` file on the Internet. I created the directory structure and placed the file.
```
mkdir -p "/home/gjost/games/star-wars-knights-of-the-old-republic/drive_c/GOG Games/Star Wars - KotOR/__support/app/"
cp /tmp/swkotor.ini "/home/gjost/games/star-wars-knights-of-the-old-republic/drive_c/GOG Games/Star Wars - KotOR/__support/app/"
```
This time the installer ran to completion, but when I tried to launch the game I got the message `No file provided.`  Looking in Config > Game Options > Executable I see that the executable is supposed to be here...
```
/home/gjost/games/star-wars-knights-of-the-old-republic/drive_c/GOG Games/Star Wars - KotOR/swkotor.exe
```
Any help would be greatly appreciated!  Thanks for making all these install scripts available to the Lutris community!

**Comment by legluondunet** [comment]
Hello I just updated swkotor Lutris script.
Could you try it and tell me if yo still have this issue?

If issue persist, please follow this steps:

1) Open terminal
2) launch Lutris with this command:
lutris -d>lutris.log
3) reinstall game and try to launch it
4) upload lutris.log file here

**Comment by gjost** [comment]
It turns out this was a case of operator error.
I renamed the `setup_star_wars_-_knights_of_the_old_republic_1.03_(29871)-1.bin` because I thought the `-1` suffix was Firefox marking a duplicate file.  When I downloaded it again the install worked.
Thanks for tipping me off on the `lutris -d` switch - I'll definitely use that before reporting any more bugs.
