### ISSUE TITLE
Silent Hill 2 not launching out of the box for me

### ISSUE THREAD

**Issue by sianhulo** [legluondunet/MyLittleLutrisScripts#8]
The game simply gets stuck forever in a black fullscreen until I close the game

Unfortunately, the lutris.log doesn't contain any useful information, fortunately I was able to find what was causing the trouble. The problem comes with the dsound.dll from the enhanced edition, if I change winecfg so that wine doesn't use native dsoun, then the game launches fine, additionally, the dsound.dll offers a log: 

[dsound.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/3780110/dsound.log)

I don't know if it might be affecting things in this case, but I have faudio installed.

**Comment by sianhulo** [comment]
installing xact through winetricks fixed the issue with dsound.

**Comment by legluondunet** [comment]
Hello @sianhulo , thank you for your report. Could you give me more infos about your config:
distribution and Wine version.
Thanks.

**Comment by sianhulo** [comment]
Archlinux, kernel version 5.3.7, AMD gpu with mesa 19.2.2
I''m using lutris' wine 4.16, but my system has 4.18 staging installed

**Comment by legluondunet** [comment]
I just reinstalled the game, I didn't need to install xact whatever the Lutris WIne version I used.
Happily you found a workaround, but I would like to understand why you need xact and not me.

**Comment by sianhulo** [comment]
Could you check you dsound.log file? as this was what tipped me off about the xaudio issue

**Comment by sianhulo** [comment]
I also hadn't considered, I have faudio package installed, but not any 32 bit version available, if you had that installed I think that you wouldn't need to install xact for most games that would otherwise require it.

**Comment by legluondunet** [comment]
I can not reproduce your issue on Manjaro 18.2.
When I installed Wine and Lutris, I saw it installed some lib32 dependencies and faudio package 32 and 64 bits.

**Comment by legluondunet** [comment]
Could you try test this:
- install faudio packages 32 and 64 bits:
![Capture d’écran depuis 2019-10-31 16-54-16](https://user-images.githubusercontent.com/325405/67963633-396a2280-fbff-11e9-951c-4a2551eb58cf.png)
- reinstall again the game
- install Lutris Wine ge-protonified-4.9 no fshack
- launch Silent Hill 2 with ge-protonified-4.9 no fshack
Does all work as expected?

**Comment by sianhulo** [comment]
I checked the dependency list of wine-staging, and unlike the vanilla version, this one doesn't pull faudio, so I guess that was the problem all along.

**Comment by legluondunet** [comment]
I can confirm too that to obtain all wine dependencies (and faudio 64/32) on Manjaro you need first to install wine package.

**Comment by legluondunet** [comment]
Could we close this issue now? The game works as expected without xact once you installed faudio 32 bits?

**Comment by sianhulo** [comment]
sure, if someone else has the same problem they will be able to find the issue anyway by searching silent hill.
