### ISSUE TITLE
Star wars Kotor performace problems

### ISSUE THREAD

**Issue by somebody1121** [legluondunet/MyLittleLutrisScripts#80]
Hello,
after installing and playing the begging i notice heavy performance drops. There are parts of the first level in witch performance can drop to around 20 fps. By setting in the swkotor.ini, in [Graphics Options], Disable Vertex Buffer Objects=0 (it's 1 by default) now i'm getting 60 fps. Also adding AllowSoftShadows=1, in the same section, enables the option to configure soft shadows and works correctly.
Since you are modifying swkotor.ini with the script, I'm wondering if you could add this options in order to have a better experience out of the box.

**Comment by legluondunet** [comment]
Hello,
I would like to reproduce your issue (fps drop) and verify if I need to change this options for me too and then for everyone.
How could I reproduce it?
From where part of the game fps begin to drop?

**Comment by somebody1121** [comment]
It's on the start, on the first combat. It's most noticeable if you look in the direction of the ship front. 
I progress a little and now i am on Taris. After getting out of the first room i get

![kotor_vertex_disable](https://user-images.githubusercontent.com/82600134/114943968-1f4def80-9e47-11eb-8484-d6f350eba37f.png)

If i use Disable Vertex Buffer Objects=0

![kotor_vertex_enable](https://user-images.githubusercontent.com/82600134/114944024-355bb000-9e47-11eb-85d3-793dcdf9d743.png)

**Comment by somebody1121** [comment]
Here the save file: [000002 - Game1.zip](https://github.com/legluondunet/MyLittleLutrisScripts/files/6321352/000002.-.Game1.zip)

Just decompress in /game/instalation/folder/saves

**Comment by legluondunet** [comment]
Hello, I finally found time to make a test. I used your save file without kotor config file.
I have a nvidia so I used this variable to obtain fps:
__GL_SHOW_GRAPHICS_OSD=1

![ArcoLinux_2021-06-09_19-19-02](https://user-images.githubusercontent.com/325405/121400366-cc307e80-c957-11eb-92ad-e40e51257865.png)
I played 5 mn and i obtained 60 fps during all my test.

**Comment by somebody1121** [comment]
> Hello, I finally found time to make a test.
> I used your save file without changed kotor config file.
> I have a nvidia GPU card so I used this variable to obtain fps:
> __GL_SHOW_GRAPHICS_OSD=1
> 
> ![ArcoLinux_2021-06-09_19-19-02](https://user-images.githubusercontent.com/325405/121400366-cc307e80-c957-11eb-92ad-e40e51257865.png)
> 
> I played 5 mn and i obtained 60 fps during all my test, no drop:
> 
> ![ArcoLinux_2021-06-09_19-36-36](https://user-images.githubusercontent.com/325405/121402497-406c2180-c95a-11eb-8fa2-aa6ca89cf3d5.png)
> 
> So I think this issue could be related to your hardware?
> What is your hardware specifications?

I have a RX 580 an a R5 2600x, and on manjaro using the latest stable mesa drivers. The problem it's that the game with "Disable Vertex Buffer Objects = 1" became cpu bound. In my capture you can see that one core it's at 98% usage. With the option set to 0 the game runs at a constant 60 fps.

**Comment by legluondunet** [comment]
could be annoying for others players, look here:
https://www.pcgamingwiki.com/wiki/Star_Wars:_Knights_of_the_Old_Republic#Lag_and_CTD

what if you let "Disable Vertex Buffer Objects = 1" option to default but disable v-sync?

`V-Sync=0`

**Comment by somebody1121** [comment]
With vsync disable and Disable Vertex Buffer Objects = 1:
![Vsync_disable](https://user-images.githubusercontent.com/82600134/121436020-1c233b80-c980-11eb-9ba5-4d0611a611bb.png)

Even with the game set to minimum:
![minimum](https://user-images.githubusercontent.com/82600134/121436056-2ba28480-c980-11eb-80cc-fa79441bae40.png)

I even try "mesa_glthread = true":
![lutris_glthread](https://user-images.githubusercontent.com/82600134/121436479-f64a6680-c980-11eb-9e46-ccde414a280d.png)
![glthread](https://user-images.githubusercontent.com/82600134/121436333-acfa1700-c980-11eb-93cd-ccc2c3a32156.png)

With max settings, vsync disable and "Disable Vertex Buffer Objects = 0"

![vsync_disable_and_vertex_buffers](https://user-images.githubusercontent.com/82600134/121436780-7e307080-c981-11eb-898f-2be5832e6c95.png)

**Comment by legluondunet** [comment]
Lutris script updated with "Disable Vertex Buffer Objects = 0".
Thank you for your contribution.
