### ISSUE TITLE
[GOG] Darksiders Warmastered Edition

### ISSUE THREAD

**Issue by AlexanderRavenheart** [legluondunet/MyLittleLutrisScripts#81]
The GOG + MF version is failing to install:
![Screenshot from 2021-04-17 15-13-53](https://user-images.githubusercontent.com/7274337/115112840-000ea980-9f90-11eb-81ce-2f8c638b8915.png)

**Comment by legluondunet** [comment]
Hello Alexander,
I updated this Lutris script installer recently and it worked during my tests.
Could you reinstall it following this steps:

- open terminal
- launch Lutris with this command:
lutris -d>lutris.log
- reinstall game and try to launch it
- upload lutris.log file here

**Comment by AlexanderRavenheart** [comment]
Hello,
Here is the requested log: 
[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/6331900/lutris.log)

**Comment by legluondunet** [comment]
I just looked at your log, everything fine until this lines:
```
DEBUG    2021-04-18 21:03:12,446 [command.on_stop:180]:Process hasn't terminated yet
DEBUG    2021-04-18 21:03:12,446 [command.on_stop:182]:Process 71592 has terminated with code 0
DEBUG    2021-04-18 21:03:13,334 [interpreter._iter_commands:309]:Installer command: {'task': {'cabfile': '$HOME/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe', 'component': 'mediafoundation', 'name': 'install_cab_component'}}
ERROR    2021-04-18 21:03:13,676 [jobs.target:36]:Error while completing task <bound method CommandsMixin.task of <interpreter.ScriptInterpreter object at 0x7fdd77169a40 (lutris+installer+interpreter+ScriptInterpreter at 0x5608f40b6180)>>: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
INFO     2021-04-18 21:03:50,534 [interpreter.revert:366]:Cancelling installation of Darksiders - Warmastered Edition - GOG
DEBUG    2021-04-18 21:03:50,536 [wine.winekill:177]:Killing all wine processes: ['/home/alexandru/.local/share/lutris/runners/wine/lutris-6.0-x86_64/bin/wineserver', '-k']
DEBUG    2021-04-18 21:03:50,536 [wine.winekill:178]:	Wine prefix: /home/alexandru/Games/gog/darksiders-warmastered-edition
DEBUG    2021-04-18 21:03:50,536 [wine.winekill:179]:	Wine arch: win32
DEBUG    2021-04-18 21:03:50,541 [wine.winekill:185]:Waiting for wine processes to terminate
DEBUG    2021-04-18 21:03:50,542 [wine.winekill:201]:Done waiting.
DEBUG    2021-04-18 21:03:50,542 [system.remove_folder:220]:Removing folder /home/alexandru/Games/gog/darksiders-warmastered-edition
DEBUG    2021-04-18 21:03:51,144 [system.remove_folder:220]:Removing folder /home/alexandru/.cache/lutris/installer/darksiders-warmastered-edition
INFO     2021-04-18 21:04:12,354 [application.do_shutdown:598]:Shutting down Lutris
```
I will try to reproduce this issue on my computer.

**Comment by legluondunet** [comment]
Alexander, could you copy/paste your config here (Lutris system preferences, system information).
And python version too.

**Comment by AlexanderRavenheart** [comment]
[System]
OS:              Manjaro Linux 21.0.2 Ornara
Arch:            x86_64
Kernel:          5.11.10-1-MANJARO
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 4500U with Radeon Graphics
Physical cores:  6
Logical cores:   6

[Memory]
RAM:             15.1 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD RENOIR (DRM 3.40.0, 5.11.10-1-MANJARO, LLVM 11.1.0)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.0.1
OpenGL Core:     4.6 (Core Profile) Mesa 21.0.1
OpenGL ES:       OpenGL ES 3.2 Mesa 21.0.1
Vulkan:          Supported

Python 3.9.3

![Screenshot from 2021-04-18 22-38-07](https://user-images.githubusercontent.com/7274337/115158475-00459c80-a097-11eb-840f-a8b2b03d6cd6.png)
![Screenshot from 2021-04-18 22-38-21](https://user-images.githubusercontent.com/7274337/115158477-0176c980-a097-11eb-8245-a8ef496f4398.png)

**Comment by legluondunet** [comment]
I just tested this Lutris script installer and it installed correctly.
I'm on Arcolinux (Arch-like), Python version is Python 3.9.3.

Could you delete this folders:
~/.local/share/lutris/runtime/
~/.cache/winetricks/

Relaunch Lutris and reinstall game, the issue is still here?

**Comment by AlexanderRavenheart** [comment]
Deleted the two folders, relaunched Lutris and reinstalled game, issue still present.
Here are the new logs:
[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/6333370/lutris.log)
[lutris_terminal.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/6333372/lutris_terminal.log)

**Comment by legluondunet** [comment]
For the moment, I suspect a Python issue.
Is this package python-lxml installed on your system?
Do you have another computer you can install the game to compare results?

**Comment by AlexanderRavenheart** [comment]
Yes, python-lxml is installed.
![Screenshot from 2021-04-19 11-47-11](https://user-images.githubusercontent.com/7274337/115208260-0a05e900-a105-11eb-8c44-17ebcbe844f8.png)

No, I do not have another computer or distribution available to compare results.

Using this version of Lutris:
![Screenshot from 2021-04-19 11-49-09](https://user-images.githubusercontent.com/7274337/115208483-489ba380-a105-11eb-8169-9141f8969790.png)
![Screenshot from 2021-04-19 11-50-17](https://user-images.githubusercontent.com/7274337/115208599-6963f900-a105-11eb-9eba-22c5da80122d.png)

**Comment by legluondunet** [comment]
I just tried this script installer on another computer with Manjaro, all is ok.
I can not reproduce your issue, it should be local.
Did you change something in your Python install?
Could you try to install again the game with Lutris latest git version?

**Comment by AlexanderRavenheart** [comment]
Looking for the error on Lutris repo I found this PR: https://github.com/lutris/lutris/pull/3430
Seems like there was a change in python 3.9 that caused this issue. Should be fixed in Lutris master. Will confirm once I test it.
