### ISSUE TITLE
Witcher 2 fails to start on high-core machines without tweaks

### ISSUE THREAD

**Issue by acdcfanbill** [legluondunet/MyLittleLutrisScripts#82]
Hello, to report your issue, please follow this steps:
    
    1) start Lutris in debug mode, in a terminal type this command:
    lutris -d > lutris.log
    2) if already installed, uninstall (remove) your game
    3) now come back to your game Lutris page installer and reinstall it. 
    At the end of the install, try to launch the game. 
    If the issue persists, please post the lutris.log debug file to this thread
    4) copy/paste the results of this 2 commands:
```
bill@yggdrasil:~$ uname -a
Linux yggdrasil 5.11.0-16-generic #17-Ubuntu SMP Wed Apr 14 20:12:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
bill@yggdrasil:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute
bill@yggdrasil:~$ 
```
    5) put the game name in the issue report title

I have a 16 core, 32 thread processor and the entire install process seemed to work great, however Witcher 2 wouldn't run right 'out of the box' after install.  While the Launcher.exe runs fine, if I try to launch the game from the launcher, then Witcher 2 hangs when trying to start and it apparently balks at the core/thread count of my machine.  If I use `taskset -c 0-7` in Lutris -> Witcher 2 -> Configuration -> System options -> Command prefix then the Witcher 2 process will be restricted to 8 threads and it starts normally.  I tested it up to `taskset -c 0-30` and that worked, but `taskset -c 0-31` did not, so I concluded that the game needs to be set to use less than 32 threads.  If this is not something that can be added to the install script, then please feel free to delete my issue report.

**Comment by legluondunet** [comment]
Hello, thank you for your report.
What version did you install? GOG Windows or Linux version?

**Comment by acdcfanbill** [comment]
GOG Windows version so it launched using WINE.  I'm not 100% sure if it's a Witcher 2 issue, or a combination Witcher 2 + WINE issue because while most games run through WINE just fine for me, I ran into a couple (Witcher 2 and Tomb Raider Undeworld) that crash if you give them all 32 threads.

**Comment by legluondunet** [comment]
Valve fixed this issue in Proton:
https://www.gamingonlinux.com/2024/03/proton-experimental-updated-for-the-finals-red-alert-2-deals-with-high-core-count-cpus

I modified Lutris scriptinstaller: limit cores number to 30 maximum

Thank you for your contribution.
