### ISSUE TITLE
Moto Racer runner out of date (no longer available?)

### ISSUE THREAD

**Issue by Magicrafter13** [legluondunet/MyLittleLutrisScripts#85]
Cannot install the game. When the install button is clicked (when selecting your installation script), after choosing the install directory, this pops up:
> Failed to retrieve wine (lutris-4.21-x86_64) information.

At which point, the installer does not continue, with the only option being to cancel.

Checking this page: https://lutris.net/runners/
I do not see lutris-4.21 in the list of wine versions.

**Comment by legluondunet** [comment]
Hello @Magicrafter13 , thank you for your report, should be resolved now.

**Comment by Magicrafter13** [comment]
Thank you for fixing it so quickly, glad to be able to play this game again.
