### ISSUE TITLE
[Request] SiN

### ISSUE THREAD

**Issue by rea987** [legluondunet/MyLittleLutrisScripts#88]
Given the excellent Lutris script of another **Quake II** engine game **Heretic II** from _MyLittleLutrisScripts_, I would like to ask the possibility of having Lutris scripts for **SiN** and **Kingpin: Life of Crime**. Both of them were natively available for Linux back in the day; I can assist acquiring game iso/data.

**SiN**

It requires `ln -s .../path/libGL.so` command to link 32 bit OpenGL libraries and then `+set gl_driver .../path/libGL.so` argument to be able to use hardware accelerated renderer on modern distros. However, latest know Linux version is v1.10 whose resolution support is limited and widescreen support is non-existed to my best knowledge. Later versions for Windows have 1st and 3rd party patches and tweaks for that;

https://www.pcgamingwiki.com/wiki/SiN

**Kingpin: Life of Crime**

It does require `MESA_EXTENSION_MAX_YEAR=2003` to be able to launch with modern Mesa drivers. Just like SiN, it's plagued with lack of modern resolutions and widescreen support. Latest available Linux version is v1.20 whereas Windows is now at v1.21. LIFLG installer offers `+set gl_mode x` for limited resolutions but neither of them are widescreen.

Kingpin uses very old implementation of OSS which doesn't work with osspd-pulseaudio, padsp (i386) or alsa-oss (aoss). I don't know what else can be done about the sound.

https://www.pcgamingwiki.com/wiki/Kingpin:_Life_of_Crime

**Comment by legluondunet** [comment]
Hello @rea987 could you contact me by private message on Lutris forum or twitter?

**Comment by rea987** [comment]
> Hello @rea987 could you contact me by private message on Lutris forum or twitter?
> https://forums.lutris.net/u/legluondunet/
> https://twitter.com/legluondunet

For unknown reason I am unable to send anyone a message, would you send me a message? Perhaps that's because I never posted anything with my Lutris account.

https://forums.lutris.net/u/rea987/

**Comment by legluondunet** [comment]
Hello @rea987 ,  @Keenanweaver wrote a Lutris script installer for Kingpin: Life of Crime, could you test it?
https://lutris.net/games/kingpin-life-of-crime/

**Comment by legluondunet** [comment]
Hello @rea987 , @keenanweaver wrote a Lutris script installer for Kingpin: Life of Crime, could you test it?
https://lutris.net/games/kingpin-life-of-crime/

**Comment by keenanweaver** [comment]
Submitted an installer for Sin Gold (GOG version) here: https://lutris.net/games/install/30712/view

**Comment by rea987** [comment]
> Hello @rea987 , @keenanweaver wrote a Lutris script installer for Kingpin: Life of Crime, could you test it? https://lutris.net/games/kingpin-life-of-crime/

Greetings,

Thanks for the effort and great work. I appreciate the fact that after such a long time, Lutris contributes took their time for these games. However, as  I mentioned in the OP, I pointed the native Linux versions of these games just like native Linux version of Heretic II which works flawlessly on modern distros thanks to Lutris.

https://github.com/legluondunet/MyLittleLutrisScripts/issues/88#issue-964901447

However, it looks like both Kingpin and SiN scripts seem to use Windows versions via Wine, not native Linux versions. I tried GOG version of Kingpin with the linked script; it install fine but fails to launch.

![resim](https://user-images.githubusercontent.com/1547646/144638428-b291b129-3096-488e-abb8-71155ec557a4.png)
****

```
$ lutris
2021-12-03 18:33:49,628: Starting Lutris 0.5.9.1
2021-12-03 18:33:49,666: No cores found
2021-12-03 18:33:51,052: Startup complete
2021-12-03 18:33:51,054: Running AMD Mesa driver 22.0.0 on AMD RENOIR (LLVM 13.0.0, DRM 3.40, 5.11.0-40-generic) (0x1636)
2021-12-03 18:33:51,054: GPU: 1002:1636 1D05:109F (amdgpu drivers)
2021-12-03 18:34:02,154: Unable to load libGLX_nvidia.so.0
2021-12-03 18:34:02,154: Unable to locate libGLX_nvidia
Started initial process 20621 from gamemoderun ~/.local/share/lutris/runners/wine/lutris-fshack-6.21-5-x86_64/bin/wine ~/Games/kingpin-life-of-crime/drive_c/GOG Games/Kingpin - Life of Crime/kingpin.exe
Start monitoring process.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
esync: up and running.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
recursive shutdown
Monitored process exited.
Initial process has exited (return code: 256)
Exit with return code 256
2021-12-03 18:34:12,225: Game still running (state: running)
2021-12-03 18:34:12,225: Stopping Kingpin: Life of Crime (wine)
```

**Comment by keenanweaver** [comment]
Are you using the latest GOG installer, and also the default install path? It's a fairly simple script, so I'm not sure what else could cause this issue.

**Comment by rea987** [comment]
> Are you using the latest GOG installer?

No, I have the Steam version of the game, to not to purchase it again, I downloaded an outdated GOG version from _places_.

> Do you have a patchreadme.txt in the game folder?

Yes.

**Comment by keenanweaver** [comment]
I can only assume that the old build has different behavior/structure from the current version. I wrote the script using the current installer from my GOG account. Info on builds here: https://www.gogdb.org/product/9#builds

I know there are separate Lutris installers based on which GOG installer is used (example: https://lutris.net/games/wing-commander/), but it makes me wish Lutris had more Ansible-like functionality, like conditionals.

**Comment by rea987** [comment]
> I can only assume that the old build has different behavior/structure from the current version. I wrote the script using the current installer from my GOG account. Info on builds here: https://www.gogdb.org/product/9#builds

Most probably.

I thank you for the work but I wish to be able to play the native version properly.

**Comment by legluondunet** [comment]
@rea987 I don't own this game and I don't play it.
@keenanweaver wrote a Lutris script installer for the GOG edition.
Now that there is a Lutris script installer for this game, I close this issue.

**Comment by legluondunet** [comment]
@keenanweaver could you add a screenshot on the game's Lutris page?
