### ISSUE TITLE
Future Pinball on Xubuntu 18.04

### ISSUE THREAD

**Issue by sophom** [legluondunet/MyLittleLutrisScripts#9]
Hello,

I really appreciate what you did. The installer made future pinball playable and I'm very very happy. I have a couple issues with Xubuntu 18.04 and I've come up with a few workarounds below:

When using the default version of wine that comes with 18.04 (3.0) and trying to load the back to the future table from the command line as the installer does, the game crashes and I get a pagefault in the logs. Switching to a newer version of wine fixes this. I'm currently using lutris-nofshack-4.18-x86_64. BTW the problem does not occur if you run FuturePinball using the "Run EXE inside wine prefix". In other words the page fault only occurs when trying to load the table directly from the command line. 

Also, I switched to using the shift keys on the keyboard. I can't stand playing pinball with a mouse. When I did this while playing with either using the 3.0 version of wine that came with ubuntu or a earlier lutris version of wine, I noticed that the shift keys get ignored sometimes and I was draining the ball. lutris-nofshack-4.18-x86_64 seems to fix this as well.

Maybe you can do something in the script to fix this.

As a side note, you're the reason I've started using Lutris now. I'm thinking of creating a VPX installer now unless you beat me to it that is...

**Comment by legluondunet** [comment]
Hello @sophom, thank you for your encouragement and your report.
Future Pinball did have a significant keyboard problem with several versions of Wine: the keyboard did not respond or had a high latency, which is why I redirected control over the mouse or advised players to play with a joystick.
I just try with WIne 4.18 and I can not reproduce this issue, thank you again to alert me, it's time to update my installer and remap controls to default (shift).

**Comment by legluondunet** [comment]
updated:
* shift keys for flipper
* install and use wine 4.18

thank you for your contribution.

**Comment by legluondunet** [comment]
Futur Pinball bug: impossible to press shift keys in the same time, only one key at a time, sometimes you press a key multiple times it will not always respond..
workaround: use mouse buttons for flipper
4.5 bug present
4.13 bug present
4.15 bug present
4.16 bug present
4.17 bug present
4.18 bug NOT present
4.19 bug NOT present
4.20 bug NOT present
4.21 bug NOT present
5.0 bug present
5.2 bug present
5.4 bug present
5.6.2 bug present

**Comment by legluondunet** [comment]
I reopen this issue:
- report bug on winehq: 
https://bugs.winehq.org/show_bug.cgi?id=49048

**Comment by legluondunet** [comment]
This issue is still present in more recent wine version.
But installing dinput8.dll native,builtin with winetricks resolved it.
Lutris script just updated.
