### ISSUE TITLE
[Request]  Kingpin: Life of Crime

### ISSUE THREAD

**Issue by legluondunet** [legluondunet/MyLittleLutrisScripts#91]

**Comment by legluondunet** [comment]
Hello @keenanweaver , I just published it, could you add a screenshot? thank you for your contribution.

**Comment by legluondunet** [comment]
Hello @rea987 , @keenanweaver wrote a Lutris script installer for Kingpin: Life of Crime, could you test it?
https://lutris.net/games/kingpin-life-of-crime/

**Comment by keenanweaver** [comment]
> Hello @keenanweaver , I just published it, could you add a screenshot? thank you for your contribution.

Submitted several screenshots.

**Comment by legluondunet** [comment]
Now that there is a Lutris script installer for this game, I close this issue.
