### ISSUE TITLE
Star Wars - The Old Republic 144 FPS - G-Sync not working

### ISSUE THREAD

**Issue by edwinb77** [legluondunet/MyLittleLutrisScripts#93]
I installed the game and most working as intended except missing G-Sync and 144 FPS (60 is available) 

I also installed the game through Steam and there 144 FPS is available, but also no G-Sync. When starting something like WarThunder I have G-Sync available, so system perspective it's working. War Thunder is also available as Linux client, so may be a bit flawed, however I also have the Windows game through Steam called Endzone and that is also working with g-sync, so unsure why swtor cannot have it available. 

Anything in the script possible to make this working?

**Comment by legluondunet** [comment]
Hello, thank you for your report.
I regret, but I can not help you to add this feature, I don't have a G-Sync compatible screen.
For fps, I only have 60 fps too as my screen do not have capacity to produce more.
For the moment, there is nothing I can do for G-sync compatibility and increasing fps in SWTOR.
Perhaps in future when I will use a more modern screen.
