### ISSUE TITLE
Warcraft 3 Reforged - No Orc background on Versus Window

### ISSUE THREAD

**Issue by TuskiDuski** [legluondunet/MyLittleLutrisScripts#94]
When selecting the versus mode all the other races have the animated 2D background but not Orc.

CPU - i5 10600KF 
GPU - RTX 3070 8GB
OS - PopOS 21.04

Humans and every other race working: 

![animated](https://user-images.githubusercontent.com/88945671/133846187-3a5ae45e-25b2-45a3-8141-5f50a13d90c0.png)

Orc just have a still black background : 

![not working](https://user-images.githubusercontent.com/88945671/133846247-31598484-37c8-4dab-833b-fc1cc99bf55e.png)

**Comment by legluondunet** [comment]
Hello @TuskiDuski , is this issue still relevant?

**Comment by legluondunet** [comment]
No answer from user.
