### ISSUE TITLE
Can't resolve dxwnd download link

### ISSUE THREAD

**Issue by ryanfantus** [legluondunet/MyLittleLutrisScripts#96]
https://github.com/legluondunet/MyLittleLutrisScripts/blob/954b5d0652f967f7e589acbb46b9bc3fb43abed4/Quest%20for%20Glory%20V%20-%20Dragon%20Fire/Quest%20for%20Glory%20V%20-%20Dragon%20Fire.txt#L5

Hi, I wanted to let you know the download link referenced above does not resolve for me and I had to manually download the file from Sourceforge to get the installation of qfg5 to complete. Thanks for writing this script!

**Comment by legluondunet** [comment]
Hello, thank you for your report. I can not reproduce your issue, I just tested script install and all was ok, DxWnd downloaded as expected. 
What if you try to donwload this url with wget?
wget https://freefr.dl.sourceforge.net/project/dxwnd/Latest%20build/v2_05_64_build.rar 
Does it download correctly?

**Comment by ryanfantus** [comment]
It does not! It resolves to an ipv6 address that isn't connecting for me. Strange. Oh well, chalk it up to weirdness on my end *shrug*. Sorry for the report here.

**Comment by legluondunet** [comment]
Effectively, I don't think your issue is related to Lutris or my script.
Perhaps you have a bad rule on your rooter or a dns issue...
You could change your dns to 8.8.8.8 (Google dns) and try again to download DxWnd.
