### ISSUE TITLE
The Secret of Monkey Island - Special Edition GOG

### ISSUE THREAD

**Issue by svpace** [legluondunet/MyLittleLutrisScripts#97]
Game launches, but crashes when I select "Play New Game" in the main menu.

[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/7314969/lutris.log)

uname -a:
Linux freespace 5.10.70-1-MANJARO #1 SMP PREEMPT Thu Sep 30 15:29:01 UTC 2021 x86_64 GNU/Linux

lsb_release -a:
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.1.5
Codename:	Pahvo

**Comment by legluondunet** [comment]
Hello @svpace , thank you for your report.
I can reproduce your issue and it seems this game now needs d3dcompiler_47 dll.
I just modified Lutrs script installer.
Could you reinstall the game ans tell me if the updated script fixed your issue?

**Comment by svpace** [comment]
Thank you very much for the quick response. Unfortunately the game crashes right away now, no main menu. Here the new logs:
[lutris.log](https://github.com/legluondunet/MyLittleLutrisScripts/files/7316629/lutris.log)

**Comment by legluondunet** [comment]
Please try this:
1) change Wine version, use an older Lutris Wine version
does it work?
Still no, so try:
2) change Wine version, use an older Lutris DXVK version
does it work?
Still no, so try:
3) install XACT, d3dcompiler_47 with winetricks
does it work?
Still no, so let another log here.

**Comment by legluondunet** [comment]
another thing, verify you have the same options as me:

![ArcoLinux_2020-12-19_17-35-25](https://user-images.githubusercontent.com/325405/136685404-04cf5c54-0793-4e19-8cc7-9ac5c8236b38.png)

**Comment by svpace** [comment]
Adding d3dcompiler_47 with winetricks did the job. It sometimes freezes when I skip cut-scenes and the sound effects are a little bit off, nonetheless it is playable.

Thank you

**Comment by svpace** [comment]
This is great!!!

Stable, sound effects are good, works even on system Wine (6.16).

Thanks
